### ISSUE TITLE
🐞 NG0600 on set tui-loader.showLoader=true when child tui-textfield is focused

### ISSUE THREAD

**Issue by MillerSvt** [taiga-family/taiga-ui#10019]
### Reproduction url

https://stackblitz.com/edit/angular-rivigpgk?file=src%2Fapp%2Fapp.component.ts

### Description

```html
<tui-root> 
  <tui-loader [showLoader]="isLoading()">
    <tui-textfield>
      <label tuiLabel>Код</label>
      <input
          #input
          tuiTextfield
          [formControl]="control"
      />
    </tui-textfield>
  </tui-loader>
</tui-root>
```

1. Focus tui-textfield
2. Programmatically change isLoading to true

> Error: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.

 
3. Programmatically change isLoading to false

> Input looks focused.

### Taiga UI version

4.18.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
That's weird. We only have this for effect really, and I don't think we ever do setting of value in computed:
https://github.com/taiga-family/taiga-ui/pull/9810
Could it be the case that signals lag somehow and reading the signal in computed triggers some effect?

**Comment by MillerSvt** [comment]
The component template is in effect. I am working on it.
