### ISSUE TITLE
🐞 - ThumbnailCard experimental broken card number indentation on Safari

### ISSUE THREAD

**Issue by BiancoBrigante** [taiga-family/taiga-ui#10043]
### Reproduction url

N/A

### Description

For Taiga UI 3.99.0 and Safari version 18.1.1 (20619.2.8.11.12)!

When using `Thumbnail Card` from `experimental` the card number has no indentation on the left.
Screenshot from Taiga UI docs:

![Image](https://github.com/user-attachments/assets/3766f36d-9861-4d60-b11e-a206d6263b9a)

### Taiga UI version

3.99.0

### Browser Used

Safari

### OS Used

macOS

**Comment by nsbarsukov** [comment]
Not reproducible for `v4`

**Comment by nsbarsukov** [comment]
Closed by:
* https://github.com/taiga-family/taiga-ui/pull/10049
