### ISSUE TITLE
🐞 - TuiFilter broken truncating when use custom content

### ISSUE THREAD

**Issue by ArioShaman** [taiga-family/taiga-ui#10059]
### Reproduction url

https://stackblitz.com/edit/angular-stgx3sqd

### Description

When you are using custom content (relates to badges https://taiga-ui.dev/components/filter#badge) and this content is long - text are not trucated as usual and trying to line break on next line. This is is a reason of broken layout of tui-filter

As hypothesis: the reason is in that when you are using custom content that projected are not wrapper by span.t-text as in regular case without cusom content. But when i try to wrap content manually - this does't help me. In demo I've tryied to reporduce this case

### Taiga UI version

4.17.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by vladimirpotekhin** [comment]
Default style for text in filter is `overflow: hidden` and `text-overflow: ellipsis`. But if custom content is used this can be undesirable behavior. You can simply add this style to your custom content like here https://stackblitz.com/edit/angular-stgx3sqd-ph5zboel?file=src%2Fapp%2Fapp.style.less

**Comment by waterplea** [comment]
Sounds reasonable, not sure we want to enforce this behavior. Also don't forget that default behavior is implemented for primitives, if you only want to get a particular string transformation you can pass a handler as content: `({ $implicit }) => $implicit.name` or even use `tuiStringify` pipe if it's one key and not a concatenation like `name + last_name`. See this example:
https://stackblitz.com/edit/angular-stgx3sqd-tscvnzkf
