### ISSUE TITLE
🐞 - TuiFilter - not updated component state when use the same control more than once

### ISSUE THREAD

**Issue by ArioShaman** [taiga-family/taiga-ui#10060]
### Reproduction url

https://stackblitz.com/edit/angular-stgx3sqd

### Description

When I'm using the same control more the once and try to select control value - another component with the same control does't change the state.

And another case:
If on component 1 select value and on the component 2 - select another value - value will rewrited.

More clarified:
Step: 1

Comp1 - select value "Text 1"
formValue result: [{ "text": "Text" }] 
active badge only on Comp1

Step 2
Comp2 - select value "Text 2"

AS IS

formValue result: [{ "text": "Text2" }] 
active badge on Comp1 - "Text", on Comp2 - "Text2"

TO BE
formValue result: [{ "text": "Text" }, { "text": "Text2" }]
active badge on Comp1 - "Text" and "Text2", on Comp2 - "Text" and "Text2"

### Taiga UI version

4.17.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Apparently this is Angular bug, updating form control does not trigger any event for another component using the same formControl (should call its `writeValue`):
https://stackblitz.com/edit/stackblitz-starters-435ebnom
https://github.com/angular/angular/issues/43484
