### ISSUE TITLE
🚀 - Make tuiTextfieldCleaner fire output event

### ISSUE THREAD

**Issue by redisotschek** [taiga-family/taiga-ui#10075]
### Description

In a feature im working on rn analytics need to receive an event when field was cleared by clicking on tuiTextfieldCleaner
I could not find any documentation on this event being available. 
Something simple like (tuiTextfieldCleanerClicked)

**Comment by waterplea** [comment]
This is not something we plan adding. In new textfield it is very easy to make your custom cleaner:
https://stackblitz.com/edit/angular-mv538jrn
