### ISSUE TITLE
[FEATURE] UI-Dimmer

### ISSUE THREAD

**Issue by WuglyakBolgoink** [taiga-family/taiga-ui#111]
# 🚀 Feature request

will be great to have the same component

https://fomantic-ui.com/modules/dimmer.html

**Comment by WuglyakBolgoink** [comment]
ups...

**Comment by waterplea** [comment]
We checked with the design team and for now there's no interest in shipping such component. It's fairly easy to implement by altering `Loader` if you need one :)
