### ISSUE TITLE
Colleagues, can you be trusted? :-)

### ISSUE THREAD

**Issue by ghost** [taiga-family/taiga-ui#146]
Good day!
The question is in the headline without a catch.

I follow your project, I really like it.

I am looking for a library for Angular and yours is very encouraging.

Libraries that I looked at have a number of disadvantages:
1. a small number of components;
2. long-term elimination of errors;
3. "curve" design.

I would like to use one ecosystem to build the interface.

I like Quasar (https://quasar.dev/), but he Vue.

And I'm interested in: NX - Angular - NestJs

Question: are you planning Taiga UI - complete ecosystem?
If so, what are the dates?

Thank you :-)

**Comment by MarsiBarsi** [comment]
Hey! 👋
Thank you for the interest in our library!

You can use our components with NX and NestJS. They all are ready for SSR and we'll continue to support it.

What "ecosystem" features do you want to see else?

**Comment by Vladislav-wn** [comment]
Thanks a lot for the quick response!
I'll start using your library and write suggestions / questions here.
I hope for your patience :-)

**Comment by waterplea** [comment]
Hello Vladislav. Please use Discussions for such topics 🙂
https://github.com/TinkoffCreditSystems/taiga-ui/discussions
Feel free to add suggestions and questions there
