### ISSUE TITLE
[FEATURE] File icons

### ISSUE THREAD

**Issue by fynnfeldpausch** [taiga-family/taiga-ui#150]
# 🚀 Feature request

### Is your feature request related to a problem?

For a given file type I would like to display a little icon to make the file easily recognizable. Think of a folder listing on the browser or a simple list of files that could be prefixed with such a component.

### Describe the solution you'd like

A simple icon component wrapper that receives the MIME type as an input and displays the respective icon. A set of icons is predefined (e.g. for image, video, audio, text, ...) bit additional icons can be configured using a provider.

**Comment by fynnfeldpausch** [comment]
Not sure if this is in the scope of this framework though

**Comment by waterplea** [comment]
Yes, sounds like it could be just a pipe for `src` for `MarkerIcon`  that would map MIME to a dictionary of icons. And since Taiga UI does not have those icons it is out of scope, at least until we decide to extend the iconset :) Do you feel like this should be closed?
