### ISSUE TITLE
[FEATURE]Material Theme

### ISSUE THREAD

**Issue by awtkeithlin** [taiga-family/taiga-ui#192]
# 🚀 Feature request

Now I am trying to use taiga  from devexpress ui kit.
(https://devexpress.github.io/ThemeBuilder/advanced/generic/darkmoon/base.common/)
I read this article .Input change to material appearance .
https://taiga-ui.dev/wrapper
Because of taiga build in ui design it is hard to maintain css and customize to material design.
Is there any way fast apply material design in taiga all components.

**Comment by waterplea** [comment]
Hello. This is out of scope of Taiga UI. We provide ability to create custom themes, but we do not include themes based off other libraries.
