### ISSUE TITLE
[BUG] FieldError not showing for FormGroup level validator

### ISSUE THREAD

**Issue by tobang** [taiga-family/taiga-ui#195]
# 🐞 Bug report

### Description

I have a reactive form with two password fields, one for password and one for confirm password. I have validator at the FormGroup level that checks if the passwords are equal. When I look at the documentation, there is a FieldError component which takes a property called formGroupName? When I give it my form name I get the following error

`NgControl not injected in TuiFieldErrorComponent! Use [(ngModel)] or [formControl] or formControlName for correct work.
ERROR Error: Cannot find control with name: 'signupForm'
`

### Reproduction

https://stackblitz.com/edit/taiga-starter-k5pqgu?file=src%2Fapp%2Fapp.component.html

### Expected behavior

The error component should be shown when the FormGroup level validator fails to validate the password inputs.

### Versions

-   OS: mac
-   Browser [chrome]
-   Angular [11]
-   Package []

**Comment by WynieCronje** [comment]
Hi.

I had a look at the stackblitz :)

I see `formGroupName="signupForm"` in HTML should be `[formGroup]="signupForm"` :

```html
<tui-field-error formGroupName="signupForm"></tui-field-error>
```
```html
<tui-field-error [formGroup]="signupForm"></tui-field-error>
```

**Comment by waterplea** [comment]
Looks like this is resolved.
