### ISSUE TITLE
[FEATURE] Cross component validation

### ISSUE THREAD

**Issue by tobang** [taiga-family/taiga-ui#217]
# 🚀 Feature request

### Is your feature request related to a problem?

 I'am using Transloco, and I have a URL custom validator. At the moment I'am showing the error text with a template and a Transloco pipe. Like this:

![Skærmbillede 2021-02-07 kl  11 25 47](https://user-images.githubusercontent.com/5670500/107184797-88e1f580-69e1-11eb-92f7-26188a19923d.png)
But I would like to reuse the error across components. Hope its clear what I mean
The way it is done right now seems to be limited to one single component.

### Describe the solution you'd like

 A possibility to reuse validation solution across components.

**Comment by waterplea** [comment]
This can be done with `TUI_VALIDATION_ERRORS` token. Please take a look at this example:
https://taiga-ui.dev/tui-field-error#customMessages
