### ISSUE TITLE
🐞 -  Не работает автодоскролл табов Tabs, если активный таб находится вне видимой области экрана в мобильной версии

### ISSUE THREAD

**Issue by costarev** [taiga-family/taiga-ui#2182]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Is this issue blocking you?

Non-Blocking

### Description

Возможный сценарий, когда изменяется ширина вьюпорта с планшетного/десктопного до мобильного

### Angular version

11.2.14

### Taiga UI version

2.54.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [X] Android

**Comment by waterplea** [comment]
I believe it's fixed now, if not, feel free to open a new issue with a reproduction on fresh v4
