### ISSUE TITLE
🚀 - Easier support for FontAwesome or Material Icon Sets

### ISSUE THREAD

**Issue by arndwestermann** [taiga-family/taiga-ui#2340]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

icons

### Description

Since FontAwesome or Material Icons are more commonly used, easier support for setting those as icon set would be helpful. Right now it is rather complicated and the documentation is not very clear about it.

**Comment by loxy** [comment]
https://github.com/Tinkoff/taiga-ui/discussions/1413
