### ISSUE TITLE
🐞 - `Tree` programmatic control problems

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#2658]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/tree-programatic-control-bug?file=src/app/app.component.html

### Is this issue blocking you?

Non-Blocking

### Description

1. Open https://stackblitz.com/edit/tree-programatic-control-bug?file=src/app/app.component.html
2. Press "Toggle Topmost" button
3. Press "Toggle Child №1" button
4. Press "Toggle Child №2" button

**Expected behaviour:**
<img width="617" alt="expected" src="https://user-images.githubusercontent.com/35179038/189352445-fbda8293-8b3d-48b1-8f9e-2aa759a00101.png">

**Actual behaviour:**
<img width="617" alt="actual" src="https://user-images.githubusercontent.com/35179038/189352559-c9beb0d4-0e5e-4706-843c-eab47a54f860.png">
(the second child is still collapsed)

5. Press "Toggle Topmost" button
6. Press "Toggle Topmost" button (again, yep)
(all children are opened despite the fact that the second child was collapsed on the previous step. It is expected behaviour).
<img width="617" alt="result" src="https://user-images.githubusercontent.com/35179038/189353354-59bc79c8-351c-4814-986e-5087ad3ae655.png">

### Angular version

any

### Taiga UI version

3.1.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Link: https://github.com/Tinkoff/taiga-ui/pull/1737

**Comment by waterplea** [comment]
We will fix this under https://github.com/Tinkoff/taiga-ui/issues/3958

**Comment by waterplea** [comment]
This is fixed, now we only have this issue: https://github.com/taiga-family/taiga-ui/issues/6834
