### ISSUE TITLE
🚀 - `InputTime` support higher input times than 23:59

### ISSUE THREAD

**Issue by 0xphilipp** [taiga-family/taiga-ui#270]
# 🚀 Feature request

Support Input Time with higher value than 23:59. It would be great if the max value could be specified. Then the control can also be used to select a time range like in X hours, Y minutes (50 hours, 30 minutes)
Or even a different control like TuiInputTimeRange.

**Comment by nsbarsukov** [comment]
Our internal teams also requires `min`/`max` input props for this input

**Comment by waterplea** [comment]
The linked issue https://github.com/Tinkoff/taiga-ui/issues/1229 is probably going to be fixed under this ticket, but I'll keep it open and separate just in case.

**Comment by waterplea** [comment]
I believe the issue is fixed now, however I'll keep this ticket open for 3 reasons:

1. No mention of `min`/`max` on the API page
2. Arrow navigation is still limited to 24 hours and 60 minutes/seconds
3. It needs to be revisited with new mask

**Comment by shatanov** [comment]
is this issues relevant? Is it possible to try to take his?
