### ISSUE TITLE
🤖 - `@taiga-ui/eslint-plugin` Typescript support

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#2700]
### Description

We have a big dream to add Typescript support for our local `eslint-plugin` package.

We should find the such solution that will satisfy the following acceptance conditions: 

1. Eslint should always work for our local development. It is easy to compile Typescript-files into JS-ones, place them inside `dist/eslint-plugin`-folder and use locally this `dist/eslint-plugin`-folder as dev-dependency). But it is difficult to ensure that we don't forget to do it again and again. I think it can become annoying problem for all external contributors that eslint does not work until building of our local package `eslint-plugin`.

2. **Developer A** can change something inside `projects/eslint-plugin` and push it to `master`. **Developer B** pulls these changes. Eslint should use new version of our rules.

3. IDEs (for example, Webstorm) has a [killer-feature "Actions on save"](https://www.jetbrains.com/help/webstorm/saving-and-reverting-changes.html#actions-on-save). It can run `eslint --fix` when you press `cmd + s`. It is rather convenient. For example, imagine that you write code and you know that eslint can auto-fix something, you could just save file and see changes NOW (without wait for the nearest pre-commit hook). This IDE's feature should continue to work.

**Comment by splincode** [comment]
@ddubrava fyi
