### ISSUE TITLE
📚 - Find a way to reuse logic with all host-declarations between public and proprietary `demo`-apps

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#2707]
### Description
We often have bugs in our proprietary demo that we forget to sync public **app.template.html** with proprietary **app.template.html**.

https://github.com/Tinkoff/taiga-ui/blob/8c72e478e3d6907a98e48b52551d77b46d50e88c/projects/demo/src/modules/app/app.template.html#L40-L44

Find a solution to reuse this the same logic between public and proprietary demo.

**Comment by splincode** [comment]
@waterplea is it actual?

**Comment by waterplea** [comment]
Let's close it if it's not bothering is anymore
