### ISSUE TITLE
[BUG] Underline component memory leak 

### ISSUE THREAD

**Issue by makkaronis4e** [taiga-family/taiga-ui#282]
# 🐞 Bug report

### Description

animationFrame$ in underline component constantly emits values even on idle page. It triggers infinite recalculations 
in width$ and transition$ 

-   Browser [chrome]
-   Angular [11]

**Comment by waterplea** [comment]
It does that to resync position. There are many cases that can affect it like changing width of the tab, resizes, CSS transitions etc. Are you seeing any performance issues related to that or just the fact? It does so outside NgZone and if values stay the same, it does not affect DOM. Also animationFrame$ is a singular shared `requestAnimationFrame` based observable, so multiple tabs still use the same single stream.
