### ISSUE TITLE
🚀 - Allow dynamic changes to `TUI_NUMBER_FORMAT`

### ISSUE THREAD

**Issue by theorlovsky** [taiga-family/taiga-ui#2900]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core

### Description

Different locales have different decimal separators, so it would be good to be able to change it dynamically on language change. Maybe change it to `InjectionToken<TuiNumberFormatSettings | Observable<TuiNumberFormatSettings>>`, this way it will be backward compatible with the previous versions.

**Comment by waterplea** [comment]
That's a good suggestion. Will you be willing to make a PR for it?

**Comment by theorlovsky** [comment]
sure, will take a look

**Comment by ddubrava** [comment]
Hi! Any ideas for the implementation? It seems that `TUI_NUMBER_FORMAT` is used in many places, so it's not trivial.
