### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by 500x500** [taiga-family/taiga-ui#293]
# 🚀 Feature request

### Is your feature request related to a problem?
Yes) It can help make the work of team faster.

In our projects we are often use same tables for solving some same problems. 
Every time when we are create a table we need copy paste same code.

### Describe the solution you'd like
There is in my project 10 or 15 same tables which I use by config.
The config include this params:
-column name (for header)
-column description (just a little hint for table header)
-column value (the value from backend which I take from obj) 
-css (it can include color of column or line, size/width, shrink maybe or other params for visuality style)
-some params like editable/disable/ cell
-checkboxes
-additional actions

Also in table we are use some buttons, but it can hard to make table more universal (and not includes in logic of tables), but it can be a little feature for.

Why this need? It can help to create table faster just by create a component-wrapper which include some &lt;app-table&gt; with main logic and we throw to component config with names and other parameters.

It's a killer feature ! :)

### Describe alternatives you've considered
There is no alternatives) It's just a feature which speed up production. 

### Additional context
Also, you can not include it in main part of library or in code, but you can it describe in site like a solution or example.

**Comment by jonsamwell** [comment]
@500x500 surely this is a component you would implement yourself in you application, this library gives you all the building blocks to do that and couldn't possibility cater for everyone's needs like you suggest.

**Comment by waterplea** [comment]
@500x500 I'm afraid @jonsamwell is right, Taiga UI is more of a low level library with lots of building blocks and focus on combining them effortlessly like Lego. So this is out of scope. You can create a separate package based on our new table addon :)
