### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by 500x500** [taiga-family/taiga-ui#294]
# 🚀 Feature request
One more killer feature!
### Is your feature request related to a problem?
Customizer of the component. 
You have a great API which I have never see before. When we can just change the parameters and in can change the component. It's very easy and user-friendly. 

 I'm always frustrated when...

### Describe the solution you'd like
Create the customizer of the component. 
As example I consider the button:
it can be flat, rounded, icon-button, gradient or more else. 
Customizer suggest create your own style of button (with other color and other border/border-radius) and copy this style (maybe css code) from the customizer to project in one click.
And it can help not only with buttons. Every component can customize like we want without hours of trying custom css-code.
In material I often use some constructions like ng-deep :'( to create some custom in my component. (and it will be super-good if they create customizer for community, but I think it newer will)
I think, customizer can make more user-friendly taiga-kit for new users.

I think, customizer can make more user-friendly taiga-kit for new users. :)

**Comment by waterplea** [comment]
I think creating a full customiser is out of our scope and we already have interactive API pages that you can change and share via url.
