### ISSUE TITLE
🚀 - Open Calendar in Year View

### ISSUE THREAD

**Issue by jonsamwell** [taiga-family/taiga-ui#3120]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

Is there a way that the calendar (TuiCalendarMonthComponent etc) could open in the year view?

Perhaps it could support an open mode?

**Comment by spicy-tomato** [comment]
Just click on year label
https://github.com/Tinkoff/taiga-ui/blob/9ae15c7f4387c1ee5e378414cbe808c6d697ab31/projects/kit/components/calendar-month/calendar-month.template.html#L25
https://github.com/Tinkoff/taiga-ui/blob/9ae15c7f4387c1ee5e378414cbe808c6d697ab31/projects/kit/components/calendar-month/calendar-month.component.ts#L201

**Comment by jonsamwell** [comment]
@spicy-tomato I require the calendar to open up on the year view rather than open up on the day or month view which then requires the user to click on the year.

**Comment by waterplea** [comment]
Makes sense. We have this input in data components: `defaultActiveYearMonth` (in `InputDateRange` it is accidentally called `defaultViewedMonth`, we gotta deprecate it and rename it to `defaultActiveYearMonth` too). It is `TuiMonth`, which means it can be `TuiMonth` or just `TuiYear`. It is then passed to `Calendar` as `month: TuiMonth`. How about we add a check:
```ts
get isYear(): boolean {
  return this.month instanceof TuiYear && !(tui.month instanceof TuiMonth);
```
and if it's true we will open calendar in year mode? Seems like it only makes sense to open in year mode up until we have an actual value selected, right?

**Comment by jonsamwell** [comment]
@waterplea that makes sense to me!

**Comment by zarghamkhandev** [comment]
Hi, I would like to create PR for this. Just to understand properly, we need to do isYear check on the `value` input to `TuiCalendarMonthComponent`, right ?

**Comment by waterplea** [comment]
> Hi, I would like to create PR for this. Just to understand properly, we need to do isYear check on the `value` input to `TuiCalendarMonthComponent`, right ?

I believe so.

**Comment by zarghamkhandev** [comment]
I don't think this gonna work, not able to pass `TuiYear` as `value` input.

```value: TuiMonth | TuiMonthRange | null = null;```

**Comment by zarghamkhandev** [comment]
If I change type signature, it breaks existing code, either we need to add more type checks or introduce new input to the component, and I will vote for new input e.g `initialView: 'monthView' | 'yearView'`
