### ISSUE TITLE
[BUG] Compile time error while using Taiga UI Table Component

### ISSUE THREAD

**Issue by pravinambekar** [taiga-family/taiga-ui#325]
# 🐞 Bug report

### Description

Getting an error while trying to use Taiga UI Table component, Chart component, 

![image](https://user-images.githubusercontent.com/41193836/113505358-ec108400-955b-11eb-99c0-ac52392cebbb.png)

I am referring the StackBlitz sample for Taiga UI Table component and trying to implement feature in my application
https://vqdwnc--run.stackblitz.io/ 
### Reproduction

- Installed all required dependencies for Taiga Table Component and other required component
- Initialized value for table in component

### Expected behavior

Table should display expected data on UI, but getting compile time error as shown in screenshot

### Versions

-   OS: Windows
-   Browser Chrome
-   Angular 11.1.2
-   Package [e.g. @taiga-ui/cdk@2.0.0] 

### Additional context

- Getting same error for component like tui-axes line chart, but when i provided static value in html it is got working
- few other errors are :  
      1) Type 'null' is not assignable to type 'readonly User[]',  
      2) Type 'null' is not assignable to type 'TuiComparator<User>'

Any help appriciated

**Comment by waterplea** [comment]
Hello there. These are type issues related to our strict approach.
1. We never mutate our data so we operate with readonly arrays. Yours does not have type explicitly defined so TS assumes it's `string[]`, just add `: readonly string[]` to the definition.
2. This is `strictNullCheck` of TypeScript. Make sure there's no chance of `null` slipping into your values. Like if you request your server for some value `async` pipe emits `null` until the actual value comes. You can either hide component with `*ngIf` or add `startWith` to your `Observable` chain so there's some fallback value that makes sense (like empty array or something like that).
