### ISSUE TITLE
🚀 - `Range`, `InputRange` add `[margin]` & `[limit]`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#3434]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

## Range
We should add new `@Input()`-properties for [Range](https://taiga-ui.dev/components/range)-component:

* `margin` - the minimum distance between the thumbs.
See https://refreshless.com/nouislider/slider-options/#section-margin

* `limit` -  the maximum distance between two thumbs.
See https://refreshless.com/nouislider/slider-options/#section-limit

## InputRange
Should we just duplicates the same input properties ?

Maybe it is better to pass `Range`-component  inside `InputRange` ?
```html
<tui-input-range>
    <input tuiTextfield />

    <tui-range [margin]="5" [limit]="30"></tui-range>
</tui-input-range>
```
(we need to discuss it and probably create the separate issue for `InputRange`)

**Comment by LarisaGl** [comment]
Hi! I`ll take it
