### ISSUE TITLE
🚀 - InputTime hide dropdown list items by settings flag

### ISSUE THREAD

**Issue by hzsenko** [taiga-family/taiga-ui#3519]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Which @taiga-ui/* package(s) are relevant/releated to the feature request?
kit

### Description
When I using InputTime component with  [items] and [strict] properties, I have a dropdown list of items, and rounding to nearest value from items list.
I want to suggest making it possible to disable the display of the dropdown menu by input.

**Comment by waterplea** [comment]
The way I read it is you want **an option to round `InputTime` value upon focus loss**. Is that correct?

**Comment by hzsenko** [comment]
Yes, but without the dropdown appearing.
