### ISSUE TITLE
🚀 - New eslint rule `@taiga-ui/no-invalid-icon-name`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#3566]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

eslint-plugin

### Description

Check that all icons inside our components are actually exists.

### Suggested solution
1. Look for all occurence of `tuiIcon...` inside `projects/**` and NOT inside `['projects/icons/**', 'projects/demo/**']`
(all these paths should be configurable parameters because they will be different for our proprietary repo)
2. Check that this icon exits inside `projects/icons/constants/icons.ts`
(this path should be configurable parameter because it will be different for our proprietary repo) 

### Examples
Valid ✅
```ts
get icon(): string {
    return this.isPasswordHidden ? 'tuiIconHideLarge' : 'tuiIconShowLarge';
}
```

Invalid ❌
```ts
get icon(): string {
    return this.isPasswordHidden ? 'tuiIconNotShowLarge' : 'tuiIconShowLarge';
                                    ~~~~~~~~~~~~~~~~~~~~
}
```

___

Valid ✅
```html
<tui-svg src="tuiIconChevronDown"></tui-svg>
```

Invalid ❌
```html
<tui-svg src="tuiIconChevroletDown"></tui-svg>
              ~~~~~~~~~~~~~~~~~~~~
```

**Comment by ddubrava** [comment]
isn't it possible to achieve this with typescript?

**Comment by waterplea** [comment]
> isn't it possible to achieve this with typescript?

You can use public icons or proprietary icons, names don't necessarily match.

**Comment by ddubrava** [comment]
well, I can work on this

**Comment by waterplea** [comment]
> well, I can work on this

That would be of great help 🙂

**Comment by ddubrava** [comment]
I'm not sure but it seems that we need `tcs` to read `icons.ts`.
https://github.com/Tinkoff/taiga-ui/issues/2700

**Comment by splincode** [comment]
https://github.com/taiga-family/linters/issues/38
