### ISSUE TITLE
🚀 - Secondary buttons using --tui-secondary-text instead of --tui-link 

### ISSUE THREAD

**Issue by KhaledGabr** [taiga-family/taiga-ui#3586]
### Description

Just like primary button has **--tui-primary-text** and accent color has **--tui-accent-text.** 
Secondary buttons should probably also have **--tui-secondary-text**. 

**Links** could be blue in the application .. but **secondary buttons** can be of different color.

**Comment by splincode** [comment]
@waterplea is actual?
