### ISSUE TITLE
🐞 - Table server-sorting (sortBy and direction) happens separately as two different events

### ISSUE THREAD

**Issue by pandamorphism** [taiga-family/taiga-ui#3694]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

When you switch sorting from one column to another you expect to create one request to backend with { sortBy: strring, direction: -1: 1 }. But Taiga's API is currently designed in a way that you have to handle two Outputs and somehow combine them into one single event to be able to execute in one transaction.
`(tuiSortByChange)="sorter$.next($event!)"
  (directionChange)="direction$.next($event)"` 

  It would be  more convenient if there were 1 event  that emitted an object ` { sortBy: string, direction: -1 : 1 } ` by clicking on the sort icon

### Angular version

all

### Taiga UI version

all

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I believe it's the same issue as https://github.com/Tinkoff/taiga-ui/issues/3915 so I will close it as the other is already scoped for Q2. If I misunderstood something, please let me know.
