### ISSUE TITLE
📚 - Documentation redesign

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#3709]
### What is the affected URL?

https://taiga-ui.dev

### Description

https://www.figma.com/file/e7haZlhOm9DjupCkq5UIMe/Taiga-3.0?node-id=31602%3A136510&t=6zYP6BtXIzsghQbH-11

<img width="877" alt="image" src="https://github.com/user-attachments/assets/8601be16-e794-4690-9e61-dab8257960cf">

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by mdlufy** [comment]
Add page with all components
<img width="840" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/87331898/c6b8b568-3dad-4e92-a61e-809544074bbc">

**Comment by splincode** [comment]
Add left menu similar to notion

<img width="842" alt="image" src="https://github.com/user-attachments/assets/b76c63eb-8c85-498a-ad0e-3c3e54d5375f">
