### ISSUE TITLE
🐞 - tui-svg does not resize dynamically

### ISSUE THREAD

**Issue by meridos** [taiga-family/taiga-ui#3716]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-wfvjar?file=src%2Fapp%2Fapp.component.html

### Is this issue blocking you?

Non-Blocking

### Description

An SVG (with the viewBox and without width, height attributes) can dynamically resize. But in a `tui-svg` composite, the dimensions will be maximal when they first appear.

For example: the `tui-svg` is rendered 100px wide, we can change the width to `50px` with css, but when we change it to `200px`, the svg will remain `100px` wide.

In the Safari browser, `tui-svg` does not render.

But if we add the width and height attributes, all cases are resolved.

### Angular version

12.2.16

### Taiga UI version

2.74.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Seems to not reproduce anymore:
https://stackblitz.com/edit/angular-fsqpug
Except for the scaling in tui-svg is vertically centered, but I believe that's intentional.
