### ISSUE TITLE
🐞 - Table rows aren't rendered in unit tests

### ISSUE THREAD

**Issue by FranckG28** [taiga-family/taiga-ui#3755]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Please provide a link to a minimal reproduction of the bug

https://github.com/FranckG28/taiga-table-testing

### Is this issue blocking you?

Blocking

### Description

To reproduce this bug, i've literally copy-paste the code from the [TuiTable documentation](https://taiga-ui.dev/components/table#custom) and created a dummy unit test that only print the rendered HTML.

When running the test with `npm run test`, the rendered table body looks like this : 
```html
<tbody
  tuitbody=""
  _nghost-a-c331=""
  ng-reflect-data="[object Object],[object Object"
>
  <tr tuitr=""></tr>
  <tr tuitr=""></tr>
</tbody>
```
Note that all required modules are imported in the test. (`TuiTableModule`, `TuiRootModule`, `TuiLetModule`).

The problem seems to be between `TuiCellDirective`, `TuiTrComponent` and `TuiTdComponent`.

Removing only one of the attribute `*tuiCell`, `tuiTr` or `tuiTd` doesn't fix the problem. We really need to remove all of theses 3 attributes for the content to be rendered correctly : 
```html
<tbody
  tuitbody=""
  _nghost-a-c331=""
  ng-reflect-data="[object Object],[object Object"
>
  <tr>
    <td id="userName">1. Michael Palin</td>
  </tr>
  <tr>
    <td id="userName">2. Eric Idle</td>
  </tr>
</tbody>
```

Unit test engine : Jest

## What i've tried
- Not importing TuiTableModule and letting the test throwing import error doesn't let the content to be rendered.
- Creating mocked component & directives for `TuiTableModule`, `TuiRootModule`, `TuiLetModule` didn't worked as well.

For the moment, I haven't found any workaround. The project i'm working on requires unit tests, but this issues prevent me to write unit test for any component using a table.

## Repro steps : 

Since Stackblitz isn't made for running unit tests, i've reproduced the bug in [this repo](https://github.com/FranckG28/taiga-table-testing).

1. Clone repo & install dependencies
```bash
git clone https://github.com/FranckG28/taiga-table-testing
cd taiga-table-testing
npm i
```

2. Run unit tests :
```bash
npm run test
```

The only unit test doesn't expect anything. It's only logging the rendered HTML in the console.

### Angular version

15.2.0

### Taiga UI version

3.19.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by vladimirpotekhin** [comment]
The current workaround is to call detectChanges() in unit test twice like this:

```
    fixture.detectChanges();
    await fixture.whenStable()
    fixture.detectChanges();
```

(it is necessary to update all internal QueryLists)

<img width="893" alt="Снимок экрана 2024-01-17 в 12 08 47" src="https://github.com/taiga-family/taiga-ui/assets/46284632/80724c0f-574a-4183-b5b9-8325f72e8151">
