### ISSUE TITLE
🐞 - dropdown expands screen width on mobile

### ISSUE THREAD

**Issue by KovalenkoNikita** [taiga-family/taiga-ui#3788]
### Which @taiga-ui/* package(s) are the source of the bug?

core, cdk

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-snjqgy-tqkorh?file=src/app/app.component.html

### Is this issue blocking you?

Non-Blocking

### Description

<img width="470" alt="Снимок экрана 2023-03-02 в 12 35 02" src="https://user-images.githubusercontent.com/29602340/222389891-f9141378-d4ee-418a-83dd-3d5f0e4cfda9.png">

### Angular version

12.2.17

### Taiga UI version

2.64.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Also related:
https://taiga-ui.dev/v2/components/data-list
The last example in v3 seem to not limit width properly.

**Comment by splincode** [comment]
4.x, is it actual now?

https://github.com/user-attachments/assets/79a2f0f2-6ab3-49e7-9cf4-cdff8365b397
