### ISSUE TITLE
[BUG] Dialog from component - example is broken

### ISSUE THREAD

**Issue by RobotCherries** [taiga-family/taiga-ui#383]
# 🐞 Bug report

### Description

The stackblitz example for the [Dialog from component](https://taiga-ui.dev/services/dialog-service#component) doesn't work.

### Reproduction

https://stackblitz.com/edit/angular-taiga-dialog-from-component-broken-example
### Expected behavior

Working stacklitz example

**Comment by waterplea** [comment]
I've created a blanket issue for Open on StackBlitz problems:
#673
