### ISSUE TITLE
🐞 - Default hint should be light in night theme

### ISSUE THREAD

**Issue by waterplea** [taiga-family/taiga-ui#3882]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

We need to make hints appear light in dark theme out of the box.

### Angular version

Any

### Taiga UI version

3.20.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Lowering this issue priority because we cannot really fix this without possible breaking changes at this point and CSS variables pallet is coming soon, after which we will revisit this task.

**Comment by splincode** [comment]
@waterplea now we have the new palette in proprietary kit, what to do next?
