### ISSUE TITLE
🚀 - `InputPhoneInternational` add conditional masking support

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#3900]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

Some international phones require conditional mask:
* **Brazilian**:  `+(55) XXXX-XXXX` or `+(55) XXXXX-XXXX`
* **Mauritius**: `+230 XXX XXXX` OR `+230 XXXX XXXX`
* **Argentina:** `+54(###) ###-####` OR `+54(###) ####-####`

**Learn more:**
* https://twitter.com/renatoaraujoc/status/1630537485926256640?s=20
* https://github.com/Tinkoff/taiga-ui/issues/3897
* https://github.com/Tinkoff/taiga-ui/blob/ca8a441f546f3c758132671e79963ff5faefb2cb/projects/kit/components/input-phone-international/tokens/countries-masks.ts#L34
* https://github.com/Tinkoff/taiga-ui/blob/ca8a441f546f3c758132671e79963ff5faefb2cb/projects/kit/components/input-phone-international/tokens/countries-masks.ts#L141
* https://github.com/Tinkoff/taiga-ui/blob/6ed30773a9aa07f0c60ec8fb5e9c3149b52e0863/projects/kit/tokens/countries-masks.ts#L15

**Comment by waterplea** [comment]
This issue would be relevant: https://github.com/Tinkoff/maskito/issues/323
Maybe we can even close this one in favor of the linked maskito one.
