### ISSUE TITLE
📚 - tuiTableFilters doesn't work with FormArray

### ISSUE THREAD

**Issue by Killjoyer** [taiga-family/taiga-ui#3925]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-4tmzqc-gaann9?file=src/app/app.component.ts

### Is this issue blocking you?

Blocking

### Description

In the example "add" button modifies inner structure, but table won't update. It works without " | tuiTableFilters | async" (it errors, but still shows new rows).

### Angular version

12.2.17

### Taiga UI version

3.20.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Per personal discussion it was determined it is not a bug in Taiga UI but rather a configuration issue. But we need to add an example to the demo so people can use it more easily.

**Comment by gennadiipetrov** [comment]
Hello. I will take it.
