### ISSUE TITLE
[BUG] Broken example on stackblitz for icon-set

### ISSUE THREAD

**Issue by Goodzonchik** [taiga-family/taiga-ui#393]
# 🐞 Bug report

When open StackBlitz example from https://taiga-ui.dev/icon-set example is broken

`
export class AppComponent {
            provide: TUI_ICONS_PATH,
            useValue: iconsPath,
        },
    ],
})
`

Collision between Providers and AppComponent

**Comment by waterplea** [comment]
I've created a blanket issue for Open on StackBlitz problems:
https://github.com/TinkoffCreditSystems/taiga-ui/issues/673
