### ISSUE TITLE
[BUG] TuiBadge component not disaplying icon

### ISSUE THREAD

**Issue by marcoripa96** [taiga-family/taiga-ui#394]
# 🐞 Bug report

### Description

The TuiBadge component is not disaplying custom content or icon.

### Reproduction

From the documentation itself, the example doesn't display icons or custom content:

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.html

### Expected behavior

Custom content / icon should be projected correctly and it should show it inside the badge.

### Versions

-   OS: Windows 10
-   Browser: v.90.0.4430.212
-   Angular 11
-   Package @taiga-ui/kit@2.8.2

**Comment by waterplea** [comment]
Yes, demo shows current main branch, this would become available after a release later today, sorry for the confusion.
