### ISSUE TITLE
🐞 - Broken icons via CDN

### ISSUE THREAD

**Issue by constantant** [taiga-family/taiga-ui#4026]
### Playground Link

impossible to show it on playground

### Description

If you deploy an app to CDN by [the docs](https://angular.io/guide/deployment#the-deploy-url) a browser breaks icons due to security reason (` Unsafe attempt to load URL <URL> from frame with URL <URL>. Domains, protocols and ports must match.`)

Note that `<base>` and [APP_BASE_HREF](https://angular.io/api/common/APP_BASE_HREF) are different in that case

### Angular version

15.2

### Taiga UI version

3.22.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by constantant** [comment]
as workaround
```ts
        {
          provide: TUI_SVG_OPTIONS,
          useFactory: () => {
            const baseHrefFromDOM = inject(DOCUMENT).getElementsByTagName(`base`)?.[0]?.href;
            const path = tuiIconsPathFactory(`${baseHrefFromDOM}assets/taiga-ui/icons`);
            return {
              ...TUI_SVG_DEFAULT_OPTIONS,
              path,
            };
          },
        },
```

**Comment by splincode** [comment]
@constantant hi, you can use `TUI_ENSURE_BASE_HREF` instead of `const baseHrefFromDOM = inject(DOCUMENT).getElementsByTagName(`base`)?.[0]?.href;`

**Comment by constantant** [comment]
@splincode nope, it is not working

**Comment by splincode** [comment]
could you create a simple github repository with an example of how you build a project to check if everything is working fine on it

**Comment by constantant** [comment]
@splincode you can check it [here](https://konstantin.kharitonov.nl/cdn-i18n-routing-issue/en/) and look at the code [here](https://github.com/constantant/cdn-i18n-routing-issue/tree/taiga-ui-icons-issue)
