### ISSUE TITLE
[BUG] Ringchart twitches when hovering

### ISSUE THREAD

**Issue by starteNCS** [taiga-family/taiga-ui#407]
# 🐞 Bug report

### Description

I wanted to check out the ring chart and saw that the example is twitching arround when hovering.
![hhRN8dsy3B](https://user-images.githubusercontent.com/30404993/118497540-733d4400-b725-11eb-81c2-0bd6d02fc7e0.gif)
its even worse for the labled one

### Reproduction

https://taiga-ui.dev/components/ring-chart

### Expected behavior

I would suggest to either always (when hovering) fill the ring or never

### Versions

-   OS: Windows 10
-   Browser: Chrome
-   Angular: i guess 11?
-   Package: the latest?

**Comment by waterplea** [comment]
Hello @starteNCS. This is a Chrome bug with SVG masks and transitions:
https://bugs.chromium.org/p/chromium/issues/detail?id=1187487
It will be fixed in Chrome 91 which is expected on May 25
