### ISSUE TITLE
🐞 - tui-multi-select shaking when changing width

### ISSUE THREAD

**Issue by Oleg979** [taiga-family/taiga-ui#4130]
### Playground Link

https://stackblitz.com/edit/angular-gsdaw7?file=src%2Fapp%2Fapp.component.ts

### Description

When i try to change width of tui-multi-select(try to select any element in multy-select dropdown) - it doesnt it smoothly, but shakes first.

Works fine on taiga v2: https://stackblitz.com/edit/taiga-starter-2-jojodq?file=src%2Fapp%2Fapp.component.ts

### Angular version

12.2.17

### Taiga UI version

3.23.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Can you record a video of the issue? I'm not sure what you mean.

**Comment by Oleg979** [comment]
> Can you record a video of the issue? I'm not sure what you mean.

Please just try to select any element in multy-select dropdown

**Comment by waterplea** [comment]
> > Can you record a video of the issue? I'm not sure what you mean.
> 
> Please just try to select any element in multi-select dropdown

I did and I see no shaking. In v2, however, I see vertical shaking of the drop-down.

**Comment by Oleg979** [comment]
> > > Can you record a video of the issue? I'm not sure what you mean.
> > 
> > 
> > Please just try to select any element in multi-select dropdown
> 
> I did and I see no shaking. In v2, however, I see vertical shaking of the drop-down.


![2](https://user-images.githubusercontent.com/33599959/230314600-c8ad23ab-7c6f-479b-b327-6259d6cf5f7b.gif)

**Comment by splincode** [comment]
I have horizontal shaking in 3.x

Left (3.x) / Right (2.x)


https://user-images.githubusercontent.com/12021443/230316725-54571ae5-8007-49b3-805f-1b51a4ef5a15.mov

**Comment by waterplea** [comment]
Doesn't shake on my Windows laptop, does shake on Mac. I'll look into it.
