### ISSUE TITLE
🐞 - ng update misses some migrations

### ISSUE THREAD

**Issue by ddubrava** [taiga-family/taiga-ui#4242]
### Playground Link

https://taiga-ui.dev/stackblitz

### Description

There are several issues with ng update @taiga-ui/cdk:

1. ~~`tui-field-error` migrates to `tui-error`, but `TuiErrorModule` is not imported~~ 
2. There is no migration for `TUI_ICONS_PATH` to `TUI_SVG_OPTIONS`
3. ~~There is no migration for `TuiPreviewService` from `@taiga-ui/proprietary-banking`.~~  ✅ 
4. ~~There is no migration for `tui-preview-pagination[lastIndex]` from `@taiga-ui/proprietary-banking`~~  ✅ 
5. There is no migration for `tuiHintOptionsProvider({ tooltipIcon: '...' })`
6. ~~There is no migration for breakpoints (`@mobile`, `@tablet`) when they are in `styles.scss` (global)~~  ✅ 
7. ~~`@taiga-ui/addon-mobile` version is not bumped during migration~~  ✅ 
8. ~~`<tui-table-bars-host ngProjectAs="tuiOverNotifications">` should be `<tui-table-bars-host   ngProjectAs="tuiOverAlerts">`~~  ✅ 
9. ~~There is not migration for `tui-tooltip[direction]`, e.g. `top-middle` -> `top`~~  ✅ 

### Angular version

12.2.18

### Taiga UI version

3.24.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@ddubrava are you interested in contributing some of them?

**Comment by ddubrava** [comment]
> @ddubrava are you interested in contributing some of them?

I can give it a try

**Comment by GrinJ** [comment]
Hello, after update from 2.83 to 3.26 I've found a few more bugs with migration script:

1) in modules there are no TODO/warnings about changes of `TuiInputFileComponent -> TuiInputFilesComponent`
2) no conversions with old enum `TuiFileState` (e.g. `TuiStatus` - ok)
3) no TODO/warnings about `TuiDecimalT`
4) `TuiFieldError -> TuiErrorModule` doens't work with standalone-components (project on Angular 15)
5) we had double import like with 
```
import {isPresent, tuiIsPresent} from '@taiga-ui/cdk';
```

and after migration import duplicates:
```
import {tuiIsPresent, tuiIsPresent} from '@taiga-ui/cdk';
```

6) there are no convertion of `TuiFieldErrorComponent -> TuiErrorComponent` in `*spec.ts` files
7) imports from same lib duplcates (lib name), before:
```
import {isNumber, TuiValidationError} from '@taiga-ui/cdk';
import {TuiIdentityMatcher} from '@taiga-ui/cdk/types/matcher';
```

after: 
```
import {tuiIsNumber, TuiValidationError} from '@taiga-ui/cdk';
import {TuiIdentityMatcher} from '@taiga-ui/cdk';
```

8) no TODO/warnings about import of 
`import {TuiDirection} from '@taiga-ui/core';`

9) no TODO/warnings about `tuiIsIe`

10) no conversion of `PolymorpheusOutletComponent` in `PolymorpheusOutletDirective` in spec-files, no TODO/warnings

11) no replacements of `TuiTabDirective -> TuiTabsDirective` in `*.spec.ts` files

12) no TODO/warnings about `TuiHintmanualDirective` in `*.spec.ts` files

13) no replacements of `polymorpheus-outlet` in inline-components
```
@Component({
    template: `
      <div polymorpheus-outlet [content]="component" [context]="context"></div>
    `,
  })`
  ```

14) no warnings/replacements with `@media @mobile-m` in `less` files

15) no TODO/warnings about `TuiOrientationT`

16) Duplicates of placeholders, before:
```
<tui-combo-box tuiTextfieldExampleText="example text">
      Text text text
      <input tuiTextfield
        placeholder="another text"
      />
</tui-combo-box>
```

after:
```
<tui-combo-box>
      Text text text
      <input tuiTextfield
        placeholder="another text"
        placeholder="example text"
      />
</tui-combo-box>
```
