### ISSUE TITLE
🚀 - Add close dialog with swipe down

### ISSUE THREAD

**Issue by Reactiver** [taiga-family/taiga-ui#4470]
### Description

It would be great to have opportunity to swipe down mobile dialog for closing

**Comment by waterplea** [comment]
We are shifting design guidelines to automatically use SheetDialog on mobile and regular Dialog on desktop with this new service:
https://taiga-ui.dev/components/sheet-dialog#responsive
Mobile view for desktop dialog is going away so this issue is no longer actual.

**Comment by Reactiver** [comment]
Ok, thank you!
