### ISSUE TITLE
🐞 - TuiRating min property not work correctly

### ISSUE THREAD

**Issue by volvachev** [taiga-family/taiga-ui#4657]
### Playground Link

https://taiga-ui.dev/components/rating/API

### Description

On the official site in the rating component. The property min does not block the choice in any way, by setting the value of 2, you can choose 1 star. This option works with the keyboard, but it does not update immediately, but only when the unfocused

https://github.com/Tinkoff/taiga-ui/assets/34657605/12e8d22d-e34a-4879-91c5-fab881936c13

### Angular version

12.2.17

### Taiga UI version

3.31.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I think `min` was added by mistake, because rating is basically styled `input type='range'` and it has `min`. What is the use case of enforcing minimal value on rating UI?

**Comment by volvachev** [comment]
> On the other hand, we can enable it pretty easily. We just need to disable pointer events for all icons with index < min. Would you be interested in contributing a PR?

The `pointer events none` does not work correctly - due to disabling the star hover effect
