### ISSUE TITLE
[FEATURE] [Charts] Combination chart

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#474]
# 🚀 Feature request

### Is your feature request related to a problem?

Sometimes for comparing data it's required to use a combination chart. For example, a combination of line and bar chart.

### Describe the solution you'd like
Allow setting series type (line, bar, scatter, etc)

### Describe alternatives you've considered

Some simple way to draw different chart types one on top of the other.

### Additional context

![Combination chart](https://user-images.githubusercontent.com/768105/121161743-9606d800-c84d-11eb-9b9e-19f2dbe3cab3.png)

**Comment by waterplea** [comment]
This can be achieved by absolutely positioning:
https://stackblitz.com/edit/taiga-combine-charts
