### ISSUE TITLE
🐞 - Changing Font Style/Text justification in the text editor throw Change Expression after Text

### ISSUE THREAD

**Issue by ggreenleaf** [taiga-family/taiga-ui#4788]
### Playground Link

https://stackblitz.com/edit/angular-zf91z1

### Description

Using an ngIf to hide the editor will cause an expression change after checked error when clicking some of the options like font style/text alignment

`ERROR
Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '_hosted_dropdown_focused': 'false'. Current value: 'true'.. Find more at https://angular.io/errors/NG0100`

Steps to reproduce.

1.Using the provided stackblitz
2. click the toggle button to display the editor
3. Change the font style to be bold 
4. Observer error.

### Angular version

12.2.17+

### Taiga UI version

3.34.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@ggreenleaf please, use
`changeDetection: ChangeDetectionStrategy.OnPush`

**Comment by waterplea** [comment]
> @ggreenleaf please, use
> `changeDetection: ChangeDetectionStrategy.OnPush`

Shouldn't cause errors in default though 😀

**Comment by splincode** [comment]
workaround))

**Comment by splincode** [comment]
The same problem

<img width="971" alt="image" src="https://github.com/Tinkoff/taiga-ui/assets/12021443/f47a18b9-71af-45ad-995a-ae362a803ae7">

**Comment by splincode** [comment]
Paid some attention to the issue but it seems there is a more complex problem
