### ISSUE TITLE
[BUG] ng build failing

### ISSUE THREAD

**Issue by benfl3713** [taiga-family/taiga-ui#485]
# 🐞 Bug report

### Description

When I run `ng build --configuration production` on a brand new angular app, it fails with the following error:
![image](https://user-images.githubusercontent.com/44288013/121943867-e9938d00-cd49-11eb-8a6a-a880a13ceafe.png)

I have narrowed it down to being a problem with the **taiga-ui-theme.less** file, as if I remove this file from angular.json the build will succeed.

Following the error location in the outputted styles file in the dist folder, the error points to this
![image](https://user-images.githubusercontent.com/44288013/121944452-9837cd80-cd4a-11eb-95ef-24660e85b8c5.png)

### Reproduction

1. Create new app: `ng new test-app` (I enabled routing and chose css as the styling option)
2. Install taiga-ui following the instructions on <https://taiga-ui.dev/getting-started>
3. Run `ng build --configuration production` and it will eventually fail

### Expected behavior

The build should succeed without failing

### Versions

-   OS: Windows 10
-   Browser chrome
-   Angular 12.0.3
-   Package @taiga-ui/core@2.11.2

### Additional context

I have recreated the issue on both an existing project that I am migrating the UI to taiga and also a brand new angular application

**Comment by hakimio** [comment]
It's not `taiga-ui` bug. It's [angular-cli bug](https://github.com/angular/angular-cli/issues/20760).
Workaround is to disable `inlineCritical` in `angular.json`:
```json
              "optimization": {
                "scripts": true,
                "styles": {
                  "minify": true,
                  "inlineCritical": false
                },
                "fonts": false
              },
```

**Comment by benfl3713** [comment]
Cheers @hakimio that worked and I can now build a production build successfully 👍

**Comment by Aqirito** [comment]
> It's not `taiga-ui` bug. It's [angular-cli bug](https://github.com/angular/angular-cli/issues/20760). Workaround is to disable `inlineCritical` in `angular.json`:
> 
> ```json
>               "optimization": {
>                 "scripts": true,
>                 "styles": {
>                   "minify": true,
>                   "inlineCritical": false
>                 },
>                 "fonts": true
>               },
> ```

this work for me thx a lot

**Comment by PRINCIE-KIDKAY** [comment]
this fix is not working for me, using angular 19

**Comment by waterplea** [comment]
@PRINCIE-KIDKAY could you make a little repository with reproduction?

**Comment by hakimio** [comment]
I can confirm that everything is working fine with Angular `19` (both `19.0` and `19.1`). 
Following `angular.json` build config gets rid of the warning reported in this thread:
```json
{
    "configurations": {
        "production": {
            /* ... */
            "optimization": {
                "fonts": true,
                "scripts": true,
                "styles": {
                    "inlineCritical": false,
                    "minify": true,
                    "removeSpecialComments": true
                }
            }
        }
    }
}
```

and this one gets rid of the new sass `@import` deprecation warnings:
```json
{
    "builder": "@angular/build:application",
    "options": {
        /* ... */
        "stylePreprocessorOptions": {
            "includePaths": [
                "./src"
            ],
            "sass": {
                "silenceDeprecations": ["import"]
            }
        }
    }
}
```
