### ISSUE TITLE
🤖 - Migrate e2e tests to Playwright

### ISSUE THREAD

**Issue by waterplea** [taiga-family/taiga-ui#4912]
### Description

1. It seems to be much faster than Cypress.

2. Remove unit test and use Playwright for

- [ ] swipe.directive.spec.ts
 - [ ] mobile-calendar.component.spec.ts
- [ ]  elastic-sticky.directive.spec.ts
- [ ]  pan.directive.spec.ts
- [ ]  zoom.directive.spec.ts
- [ ]  static-request.service.spec.ts
- [ ]  get-clipboard-data-text.spec.ts
- [ ]  get-element-obscurers.spec.ts
- [ ]  avatar.component.spec.ts
- [ ]  input-phone.component.spec.ts
 - [ ] range.component.spec.ts
 - [ ] sliders-key-steps.spec.ts
 - [ ] tag.component.spec.ts
 - [ ] tabs.component.spec.ts

**Comment by splincode** [comment]
<img width="834" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/02288037-37e3-41e3-bb90-812192ac24b5">

**Comment by nsbarsukov** [comment]
![Screenshot 2023-09-07 at 17 17 46](https://github.com/taiga-family/taiga-ui/assets/35179038/6d5e7072-271e-4a4b-b6c5-d7bcf1962114)

**Comment by VidhiRambhia** [comment]
I'm interested in working on this issue. How do I start contributing?

**Comment by nsbarsukov** [comment]
> I'm interested in working on this issue. How do I start contributing?

@VidhiRambhia Sorry for late response!

We are glad to any contribution.
Thanks for your interest to become part of it!

___

Algorithm of contribution is the following:
1. Take any group of tests from any of [these folder](https://github.com/taiga-family/taiga-ui/tree/main/projects/demo-cypress/cypress/tests)
2. Rewrite test using Playwright and Page Object pattern 
3. Put all new tests inside [this folder](https://github.com/taiga-family/taiga-ui/tree/main/projects/demo-playwright/tests)
4. Don't take screenshot of the whole page without a necessity. Many our previous Cypress screenshots is rather large (it takes a lot of time to make snapshot of the whole page).
5. Open PR with contribution

**Comment by VidhiRambhia** [comment]
> > I'm interested in working on this issue. How do I start contributing?
> 
> @VidhiRambhia Sorry for late response!
> 
> We are glad to any contribution. Thanks for your interest to become part of it!
> 
> Algorithm of contribution is the following:
> 
> 1. Take any group of tests from any of [these folder](https://github.com/taiga-family/taiga-ui/tree/main/projects/demo-cypress/cypress/tests)
> 2. Rewrite test using Playwright and Page Object pattern
> 3. Put all new tests inside [this folder](https://github.com/taiga-family/taiga-ui/tree/main/projects/demo-playwright/tests)
> 4. Don't take screenshot of the whole page without a necessity. Many our previous Cypress screenshots is rather large (it takes a lot of time to make snapshot of the whole page).
> 5. Open PR with contribution

Thank you, @nsbarsukov. I have started taking a look at this!

**Comment by AtharvChandratre** [comment]
Hi @nsbarsukov, I'd also love to contribute to this! Will follow the algorithm for contribution you've laid out above.

**Comment by VidhiRambhia** [comment]
Hi @n-barsukov,

I have an initial PR for one of the tests - https://github.com/AtharvChandratre/taiga-ui/pull/1
Please let me know if this is the right way to go about it. Looking forward to your feedback!

**Comment by VidhiRambhia** [comment]
Hi @nsbarsukov 

Thanks for your feedback! I've raise another PR to the main repo - https://github.com/taiga-family/taiga-ui/pull/5584

**Comment by splincode** [comment]
Flaky:

![image](https://github.com/taiga-family/taiga-ui/assets/12021443/6bf54c09-9dda-42c4-9ccb-ab0de5384000)
