### ISSUE TITLE
🐞 - TuiComboBox incorrectly gets width parameter

### ISSUE THREAD

**Issue by Formaceft** [taiga-family/taiga-ui#4935]
### Playground Link

https://stackblitz.com/edit/angular-eiecws-1krhgo?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.less

### Description

If u set tuiDropdownLimitWidth="auto" instead of [tuiDropdownLimitWidth]="'auto'" - combobox ignore it. It's working only without additional inner <input / parameter passed throught ng-content. 

### Angular version

12.2.17

### Taiga UI version

latest (3)

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like an issue with Angular:
https://github.com/angular/angular/issues/51642
