### ISSUE TITLE
🐞 - paddings in MultiSelectGroups with lable

### ISSUE THREAD

**Issue by RandyVegas** [taiga-family/taiga-ui#4967]
### Playground Link

https://stackblitz.com/edit/angular-nkjfa2-buexsz?file=src%2Fapp%2Fapp.component.html

### Description

The first group has padding in the labeled multiselect, but the next group does not.
![Screenshot_2](https://github.com/Tinkoff/taiga-ui/assets/34606740/cd642f93-2c3e-420e-9864-8151bf28138d)

### Angular version

12.2.17

### Taiga UI version

3.37.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nitin-pandita** [comment]
@RandyVegas I am up for it
