### ISSUE TITLE
🐞 -  Part of the tree node nesting guidance line not rendered after collapse / expand 

### ISSUE THREAD

**Issue by KimAlexander** [taiga-family/taiga-ui#4988]
### Playground Link

https://b7ariy--run.stackblitz.io/

### Description

Tree component example, custom [section](https://taiga-ui.dev/components/tree#custom) 
When expanding / collapsing parts of the tree nodes, nesting guidance line is disappearing 
<img width="231" alt="Screenshot 2023-07-25 at 13 44 00" src="https://github.com/Tinkoff/taiga-ui/assets/9423333/ee6c357b-4659-4145-8d98-a471c107c3be">

After expand / collapse no guidance line 

<img width="299" alt="Screenshot 2023-07-25 at 13 43 50" src="https://github.com/Tinkoff/taiga-ui/assets/9423333/d76108ac-7be1-40e8-b781-fefe27e57fd6">

### Angular version

12.2.17

### Taiga UI version

3.38.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux
- [X] iOS
- [X] Android

**Comment by waterplea** [comment]
That is some weird bug I couldn't trace to anything. Somehow it's like there's `overflow: hidden` applied to internal wrapper of the expand component, but nothing helps against, even explicitly stating it visible.

**Comment by splincode** [comment]
@waterplea is it still relevant? I can't reproduce

**Comment by waterplea** [comment]
> @waterplea is it still relevant? I can't reproduce

Yeah, looks like it's fixed. It was a browser bug, anyway, probably. I investigated it a bit and found no reason for the line to not be visible back in the day.
