### ISSUE TITLE
🐞 - AnalogJS - Failed to import @tinkoff/ng-dompurify when starting the server

### ISSUE THREAD

**Issue by Rafaelz2516** [taiga-family/taiga-ui#4993]
### Playground Link

https://github.com/Rafaelz2516/pitaya

### Description

What i am using?
[Analogjs](https://analogjs.org/)

Steps:
1. npx create-nx-workspace@latest --preset=@analogjs/platform - [Integration](https://analogjs.org/docs/integrations/nx)
2. npm i taiga-ui 
3. nx g taiga-ui:ng-add
4. nx serve pitaya (or the name of the project)

Error after opening the localhost?
![image](https://github.com/Tinkoff/taiga-ui/assets/24444427/737740b2-b69a-4f3f-bb42-f429bc2394d0)

### Angular version

16.1.0

### Taiga UI version

3.37.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@waterplea need to build all libraries with ng-packagr 13+
<img width="1063" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/c1652749-c01f-40bb-9511-dec1b6b7287d">

**Comment by waterplea** [comment]
> @waterplea need to build all libraries with ng-packagr 13+
> <img width="1063" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/c1652749-c01f-40bb-9511-dec1b6b7287d">
> 

Ok, this will have to wait for Taiga 4.0 and a bump to Angular 14.

**Comment by splincode** [comment]
Fixed by `@taiga-ui/dompurify`
