### ISSUE TITLE
🐞 - tui-root scrollbar stick to mouse in iframe when mouseup event happens outside iframe

### ISSUE THREAD

**Issue by Aden-git** [taiga-family/taiga-ui#5027]
### Playground Link

https://stackblitz.com/edit/angular-pxy8jl?file=src%2Fapp%2Fapp.component.html

### Description

Hello guys!
I got an issue with page scrollbar, used inside tui-root.
It happens inside iframe.

#### Conditions:
Use tui-root inside iframe.

#### Steps to reproduce:
1. Click on scroll bar handle and hold it ("mousedown" event)
2. Move mouse outside of iframe
3. Make "mouseup"
4. Move mouse back to iframe

#### Result:
Scroll bar handle stuck to mouse ("mousemove" event still handling) until next click ("mouseup" event)

### Angular version

15.2.7

### Taiga UI version

3.37

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Hi @Aden-git. Thank you for filing this issue. Would you be willing to try this approach?
https://stackoverflow.com/questions/66703382/how-to-keep-watching-mouse-move-outside-iframe
I haven't tested it, but it seems that if we replace preventDefault on scrollbars with CSS user-select: none it should start working properly.
