### ISSUE TITLE
🚀 - Оглавление в редакторе 

### ISSUE THREAD

**Issue by kanufrieva** [taiga-family/taiga-ui#5028]
### Description

Использовать стили, чтобы собирать оглавление
Пример из Google Docs
![image](https://github.com/Tinkoff/taiga-ui/assets/141236589/f7f74900-501d-456a-ba55-ba7f1abb9978)

**Comment by splincode** [comment]
Moved to https://github.com/taiga-family/tui-editor/issues/104
