### ISSUE TITLE
🐞 - Issue with multiselect element

### ISSUE THREAD

**Issue by jokery23** [taiga-family/taiga-ui#5029]
### Playground Link

https://stackblitz.com/edit/angular-pxy8jl-cwvuuh?file=src%2Fapp%2Fapp.component.html

### Description

Hi guys!
I got an issue with multi-select element
Not sure if it is a bug, maybe only an improvement

Clear the first value in the 'Multiselect' field by clicking on the [x] icon
**Actual result:** Values moved left, the drop-down list is opened and the first value doesn't delete after clicking on the 'x' icon in the multi-select, cursor goes to search input

![image](https://github.com/Tinkoff/taiga-ui/assets/12272060/ac046580-9f8f-4cd5-8312-326034f319f7)

**Expected result:** Value is deleted after clicking on the 'x' icon

The issue is reproduced after force reloading page when tags have long names and are hiding behind a multi-select wrapper

Multiselect work correctly when tags fit inside a container(on the screenshot):
![image](https://github.com/Tinkoff/taiga-ui/assets/12272060/a9f3669d-2e19-41eb-ba85-4b1e45a3958d)

### Angular version

15

### Taiga UI version

3.9

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I suppose it focuses the input on mousedown, container is scrolled and click does not happen on the cross icon. Good find. Would you be interested in trying to make a PR for this?
