### ISSUE TITLE
🚀 - Disable autoscroll in Stepper component

### ISSUE THREAD

**Issue by itPiligrim** [taiga-family/taiga-ui#5040]
### Description

Stepper component use autoscroll when active element changes.
See: https://github.com/Tinkoff/taiga-ui/blob/96c3b677cb38f01aff834a204298caf9cf7f79f4/projects/kit/components/stepper/stepper.component.ts#L51

Please add input in API to disable this. In my project, there are filters that change the navigation elements. When filters are applied, the active element may disappear (-1 value). At that moment an unnecessary scroll occurs.

**Comment by waterplea** [comment]
I don't think it is ever necessary to disable scroll to active element. Instead it just should ignore -1 or any other index that is not resolved to a step.
