### ISSUE TITLE
🤖 - left menu opens when scrolling horizontally in a multiselect

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#5045]
### Description

https://github.com/Tinkoff/taiga-ui/assets/12021443/7883fa42-5705-4b1b-b2f7-91cd25404580

**Comment by nitin-pandita** [comment]
@splincode I would like to work on it

**Comment by nitin-pandita** [comment]
@splincode hope you are doing well, would you like to link me to the component where this issue is occurring
