### ISSUE TITLE
Unable to change the UI component color when using CSS as the default styling 

### ISSUE THREAD

**Issue by HuzaifaJH** [taiga-family/taiga-ui#5052]
### Playground Link

-

### Description

I am using button component from taiga UI and I am unable to change the color of it.
I have tried defining the color in background & background-color, even passing the **!important** flag but still the color wont apply.
I have tried applying the bg-color styling in the component.css as well as the main styles.css.

Can anyone guide me on what am I doing wrong?

p.s. I know its not a bug.

### Angular version

16.1.7

### Taiga UI version

3.39.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
For non-issues it's better to seek help in the Discussions section. Here's an example of a custom button style:
https://taiga-ui.dev/components/button#custom

You create a custom «appearance» in global styles so you can reuse it later. If you want to just define styles in place once, you can pass `appearance=""` to reset built-in styles, then you can just define them as usual with color/background CSS rules.
