### ISSUE TITLE
🐞 - InputDateTime - placeholder overlapping with value

### ISSUE THREAD

**Issue by zergunteg** [taiga-family/taiga-ui#5098]
### Playground Link

-

### Description

Problem in `basic` example at proprietary demo portal.

1. Choose a date
2. Enter first digit of timestamp
3. See that placeholder `H` is still visible and overlaps value

### Angular version

any

### Taiga UI version

3.40.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by zergunteg** [comment]
<img width="323" alt="Screenshot 2023-08-14 at 13 22 17" src="https://github.com/taiga-family/taiga-ui/assets/19213538/30b7b103-77d9-4118-b472-3a989654b681">

**Comment by vladimirpotekhin** [comment]
the problem was with the Sentry `Breadcrumbs` plugin in the app
