### ISSUE TITLE
🐞 - Unexpected width narrowing in page-sized dialog

### ISSUE THREAD

**Issue by Gleb1nho** [taiga-family/taiga-ui#5126]
### Playground Link

https://stackblitz.com/edit/angular-9fuxpx?hideExplorer=1

### Description

Page-sized dialog's width narrows when its content's height exceeds some limit.
Please make Stackblitz demo-window wider for better experience.
[Here](https://stackblitz.com/edit/angular-9fuxpx?file=src%2Fapp%2Fsecond-table-component%2Fsecond-table.component.ts%3AL60&hideExplorer=1) you can try to change count of elements (e.g.  when `range(0, 3)` is used everything works as expected, but if you use `range(0, 10)` some unexpected right padding/stripe shows up).

### Angular version

14.0.0

### Taiga UI version

3.41.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by pwespi** [comment]
I have the same issue in Chrome on macOS, although I had to increase to `range(0,15)` to reproduce it in the linked Stackblitz in a fullscreen window (my display is 2560 x 1440).

Interestingly the bug doesn't appear in Firefox.

**Comment by pwespi** [comment]
I think it's related to the pseudo ::scrollbar element that takes up space but doesn't actually display a scrollbar.

**Comment by waterplea** [comment]
Indeed, looks like `overflow: overlay` stopped working, which is a pity:
https://caniuse.com/css-overflow-overlay
We will need to fix our custom CSS scrollbar mixin. This code is inside CDK package so we did not use our scrollbar component and instead relied on CSS to make it look similar.
