### ISSUE TITLE
🐞 - Top level `tuiMode` is not accessible in lazy routes

### ISSUE THREAD

**Issue by constantant** [taiga-family/taiga-ui#5168]
### Playground Link

https://stackblitz.com/edit/angular-ireadt?file=src%2Fapp%2Flazy-loaded-module%2Fbusiness.service.ts

### Description

![mode-di](https://github.com/taiga-family/taiga-ui/assets/5537730/a17fbbc3-3638-4f40-8312-827f786e15b1)

### Angular version

14

### Taiga UI version

3.41.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
It is reproducible on the stackblitz above though. Let's keep it open and come back to it in 4.0 RCs, once we update Angular to 14.

**Comment by constantant** [comment]
Then we should give a workaround here: simply provide the needed services in a `Component` instead of a `Module`

https://stackblitz.com/edit/angular-ireadt-ka1goi?file=src%2Fapp%2Flazy-loaded-module%2Fpage.component.ts

**Comment by waterplea** [comment]
Fixed in v4
