### ISSUE TITLE
🐞 - Компонент SheetDialog сам собой закрывается в мобиле

### ISSUE THREAD

**Issue by evoytenkoapps** [taiga-family/taiga-ui#5174]
### Playground Link

https://taiga-ui.dev/components/sheet-dialog

### Description

Сам собой закрывается компонент, см видео.
advanced
Телефон xiaomi a2 android 10
Браузер Opera 76.2.4027.73374

https://github.com/taiga-family/taiga-ui/assets/26488952/761a2a25-8dc5-4e26-9d88-f6ea4f77ea9c

https://taiga-ui.dev/components/sheet-dialog

### Angular version

последний наверное

### Taiga UI version

последняя наверное

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [x] Android

**Comment by evoytenkoapps** [comment]
Заметил что так происходит через раз, каждое второе открытие само-сабой закрывается

**Comment by evoytenkoapps** [comment]
Opera 76.2.4027.73374

**Comment by splincode** [comment]
fixed in 3.43
