### ISSUE TITLE
🐞 - Не могу запустить проект если есть импорт TuiSheetDialogService

### ISSUE THREAD

**Issue by evoytenkoapps** [taiga-family/taiga-ui#5176]
### Playground Link

https://github.com/evoytenkoapps/rnd-swipe/blob/f9cc44b9d66a7941c924971424b38d9bdcb91c42/src/app/app.component.ts#L2

### Description

Создал новый проект на 15 ангуляре
ng new rnd-swipe

Angular CLI: 15.0.3
Node: 14.20.1
Package Manager: npm 9.7.1
OS: darwin x64

Ноды 16 и 18 

Поставил тайгу 
ng add taiga-ui

После импорта TuiSheetDialogService в компонент, проект не запускается
Убираем импорт и проект запускается
```
./node_modules/@taiga-ui/addon-mobile/fesm2015/taiga-ui-addon-mobile-components-mobile-calendar.js:13:0-45 - Error: Module not found: Error: Can't resolve '@angular/cdk/scrolling' in '/Users/e.voytenko/Documents/Work/Angular/rnd-swipe/node_modules/@taiga-ui/addon-mobile/fesm2015'

Error: node_modules/@taiga-ui/addon-mobile/components/mobile-calendar/mobile-calendar.module.d.ts:4:21 - error TS2307: Cannot find module '@angular/cdk/scrolling' or its corresponding type declarations.

4 import * as i3 from "@angular/cdk/scrolling";
                      ~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@taiga-ui/addon-mobile/components/mobile-calendar/mobile-calendar.strategy.d.ts:1:65 - error TS2307: Cannot find module '@angular/cdk/scrolling' or its corresponding type declarations.

1 import { CdkVirtualScrollViewport, VirtualScrollStrategy } from '@angular/cdk/scrolling';
                                             ~~~~~~~~~~~~~~~~~~~~~~~~
```

### Angular version

15.0.0

### Taiga UI version

3.41.1

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Проблема написана явно — нет пакета `@angular/cdk`. Нужно его ставить руками, если флаг -legacy-peer-deps или не через опросник.

**Comment by evoytenkoapps** [comment]
А я пробовал ставить @angular/cdk не помогало, возникали новые ошибки.
