### ISSUE TITLE
🚀 - Лучше задокументировать TuiDay (нумерация Month)

### ISSUE THREAD

**Issue by syrok0010** [taiga-family/taiga-ui#5187]
### Description

Было бы правильно задокументировать такую важную особенность, как нумерация месяцов с 0, в определении класса и/или на поле month TuiMonth.
При использовании конструктора TuiDay документация конструктора TuiMonth не видна, что мешает получению информации об этом нестандартном поведении

**Comment by waterplea** [comment]
Closing this as not planned since it behaves the same way as native `Date` type
