### ISSUE TITLE
🐞 - TuiTree after expanding several elements inwards programmatically hides the elements of the next level

### ISSUE THREAD

**Issue by John-Pier** [taiga-family/taiga-ui#5189]
### Playground Link

https://stackblitz.com/edit/angular-msppzx-u3lkok?file=src%2Fapp%2Fapp.component.ts

### Description

The TuiTree, after expanding several elements inward, programmatically hides the elements of the next level. The analysis shows that this is due to the fact that the `tui-expand` puts down an incorrect internal state. As a result, a hard-coded `style.height` constraint is set.
Steps:
1) Press expand button
2) Then Expand `Next level 1` manually
3) Then items `Next level 2` and ` Next level 3` will hidden

### Angular version

14, 15.1.0

### Taiga UI version

3.41.1

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
fixed in last version v3.70

https://stackblitz.com/edit/angular-mprfsr?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html&hideExplorer=1
