### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by qortex** [taiga-family/taiga-ui#521]
# 🐞 Bug report

### Description

I can't get DialogService to work.

Whatever I try, the dialog does not show (just the background drop), with just a text `[object Object]` displayed. DOM is not populated as you can see:

![image](https://user-images.githubusercontent.com/37897072/123999680-11822200-d9d3-11eb-8766-0c05cb9dee92.png)

I use the code from the example and can't tell what is different from the demo stackblitz, except I use Tailwind.

```ts
this.dialogService
      .open('This is a plain string dialog', { label: 'Heading', size: 's' })
      .subscribe();
```

What could be causing this?

There is no error in the browser Console.

I tried stripping all from my app to leave just a simple `AppComponent` but in vain, the issue still arises. I tried populating `packages.json` with all modules that are used in Stackblitz, in vain.

### Reproduction

I use Nx & Tailwind. Unfortunately, I don't know how to reproduce this environment in Stackblitz.
When trying with a simple example in Stackblitz, it works as expected.

### Expected behavior

The dialog should show up.

### Versions

-   OS: Fedora 34
-   Browser Chrome
-   Angular 12.1.0
-   Package Taiga 2.1.0

**Comment by qortex** [comment]
Note: Notification Service works ok.

**Comment by waterplea** [comment]
Hi @qortex! Please try bumping versions of all Taiga packages to the latest version in package.json, remove package-lock and node_modules and do clean npm i.

**Comment by qortex** [comment]
Thanks! Thought I tried, must have failed, it magically solved the issue!
ah js... I'm both relieved and frustrated I lost 4 hours because of damn `node_modules` :)

Thanks for the awesome lib
