### ISSUE TITLE
🐞 - incorrect carriage position when focusing in tui-input-number

### ISSUE THREAD

**Issue by Vadim-A** [taiga-family/taiga-ui#5233]
### Playground Link

https://stackblitz.com/edit/angular-xqf5ex?file=src%2Fapp%2Fapp.component.less

### Description

There is an tui-input-number with a postfix. when focusing on this tui-input-number, the caret moves before postfix. it is ok.
Then, there is a tui-select. Step to reproduce:
1) Open tui-select dropdown
2) move mouse over the items of tui-select dropdown, but not choose anithyng
3) close dropdown
4) try to focus on tui-input-number

Expected: when focusing on this tui-input-number, the caret moves before postfix
Real: the caret stay after postfix and it is not able to enter a value
![tui-bug](https://github.com/taiga-family/taiga-ui/assets/19825549/b11ad8ca-d7d3-408e-89c1-18ab7f1daf1e)

### Angular version

12.2.17

### Taiga UI version

3.42.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
Check this issue after update `@maskito/kit@1.5.0`
