### ISSUE TITLE
🐞 - Не полностью закрывается SheetDialog

### ISSUE THREAD

**Issue by evoytenkoapps** [taiga-family/taiga-ui#5244]
### Playground Link

https://taiga-ui.dev/components/sheet-dialog#advanced

### Description

 Иногда шторка при свайпе вниз не закрывается полностью. Возникает примерно 1 раз из 10 попыток.
iPhone XR, iOS 16.1.1
Браузер Chrome, версия 116.0.5845.118

https://github.com/taiga-family/taiga-ui/assets/26488952/ae4e4c27-973a-4f83-9055-1b3726b463cc

https://github.com/taiga-family/taiga-ui/assets/26488952/664fe119-44ee-4727-8bdb-84302467b84c

### Angular version

последний наверное

### Taiga UI version

последняя наверное

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by waterplea** [comment]
By design - это пример на фиксированные уровни "раскрытости", на которых скролл останавливается специально. Если повторно свайпнуть вниз, то всё закрывается.
