### ISSUE TITLE
🐞 - Icons not loading properly in Firefox when using with bootstrap

### ISSUE THREAD

**Issue by Mohid123** [taiga-family/taiga-ui#5246]
### Playground Link

https://depa-frontend.pages.dev/auth/login

### Description

I am using Taiga UI in my Angular project. The Icons from taiga ui are not being rendered properly, when used in conjunction with bootstrap styles. This occurs only in Firefox. In Chrome, Edge and Safari, they render fine. It doesn't matter what icons are used (tuiSvg or any input fields with predefined icons such as search bar), they all don't render.
This is what the result looks like in Firefox:
![Screenshot_2](https://github.com/taiga-family/taiga-ui/assets/61119217/89b0ed5e-b912-4d8c-8ee6-350f0a6d5b7e)
And this is what it is supposed to look like (as it does in Chrome and the rest):
![Screenshot_4](https://github.com/taiga-family/taiga-ui/assets/61119217/e70afea2-caf0-4858-8b1a-803161ed3df5)
When I remove my bootstrap import from styles.scss, the icons start displaying fine. But I need bootstrap for this project as it is a dependency for a form builder component I am using in this project. Is there a way to fix this issue? 
P.S My firefox version is up to date (117.0, at the time of writing)
P.P.S. The link I provided is a login page that suffers from the same issue. The checkbox icon doesn't render (in Firefox only)

### Angular version

15.2.1

### Taiga UI version

3.20.0

### Which browsers have you used?

- [X] Chrome
- [X] Edge
- [X] Firefox
- [X] Safari

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
<img width="704" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/d49853bd-a4f9-4dfe-b7cc-89dd524407e9">
how to login?

**Comment by Mohid123** [comment]
Hi. You can't login because this dashboard isn't connected to a backend server. This page is just for demo purposes. If you open this page in Firefox, you'll see the checkbox icon will appear incorrectly (I am using tui-checkbox). This happens throughout the dashboard for all taiga ui components which use icons (search bars, buttons, select boxes etc.).
This screenshot is from Firefox:
![Screenshot_20230831_120829](https://github.com/taiga-family/taiga-ui/assets/61119217/63ca7530-64ce-4e0c-ad04-a9eeb93f1566)

**Comment by splincode** [comment]
@Mohid123 
<img width="809" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/014d8180-c49c-41d0-aef7-4aa23a98022f">

why do you have `svg { overflow: hidden }` ?

<img width="576" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/fde6a9c5-3e54-4121-9553-427736b534d7">

**Comment by Mohid123** [comment]
@splincode I am not applying this style. I haven't applied any custom styles on svg elements at all. Might be that Bootsrap is applying this style on svg elements by default. Is this what's causing the issue?

**Comment by splincode** [comment]
`Is this what's causing the issue?` yes
 
https://stackoverflow.com/questions/51566796/svg-being-overflowhidden-by-bootstrap-why

**Comment by Mohid123** [comment]
Right. It was an issue with bootstrap after all. Using svg with `overflow: visible!important` solves it. But why does it happen in Firefox only?

**Comment by splincode** [comment]
yep

**Comment by Mohid123** [comment]
Issue occurred because Bootstrap styles conflicted with svg elements.
