### ISSUE TITLE
🐞 - `Textarea` has problem with character descenders inside placeholder

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#5271]
### Playground Link

https://maskito.dev/recipes/textarea#latin

### Description

* https://taiga-ui.dev/components/textarea#native
* https://maskito.dev/recipes/textarea#latin

![Screenshot 2023-09-01 at 16 12 47](https://github.com/taiga-family/taiga-ui/assets/35179038/fca28a69-8ffa-469e-8ee4-3de5c161c8b9)

### Angular version

12

### Taiga UI version

3.42.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Mentioned it in another Textarea ticket in the same area, let's fix all at once:
https://github.com/taiga-family/taiga-ui/issues/5211
