### ISSUE TITLE
🐞 - doubling dropdown in tui-tabs-with-more

### ISSUE THREAD

**Issue by markus621** [taiga-family/taiga-ui#5272]
### Description

https://taiga-ui.dev/navigation/tabs#complex

If the menu has several elements with submenu, then when the screen is reduced, when part of the elements from the submenu goes to the more block. When you try to open this submenu, it doubles.

![screen](https://github.com/taiga-family/taiga-ui/assets/7774127/480e0315-501b-48f9-9d62-f89720f52011)

### Angular version

16.2.3

### Taiga UI version

3.42.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by giowhatever** [comment]
#5677 dropdown in tui-tabs can't be opened

**Comment by waterplea** [comment]
I have fixed the dual dropdown but active zone closes the dropdown when you hover over the nested one. We will only be able to fix in in 4.0 and Angular 15, when templates would allow passing injector.
