### ISSUE TITLE
Taiga ui inputFiles

### ISSUE THREAD

**Issue by anisha-bajra** [taiga-family/taiga-ui#5274]
### Discussed in https://github.com/taiga-family/taiga-ui/discussions/5263

<div type='discussions-op-text'>

<sup>Originally posted by **anisha-bajra** September  1, 2023</sup>
How do I get the file and set it to FormData?
file = {} as TuiFileLike;

submit(){
   const formData = new FormData();
   formData.append('file', this.file as File, this.file.name)
}

this does not seem to work</div>

**Comment by splincode** [comment]
https://github.com/taiga-family/taiga-ui/discussions/5263#discussioncomment-6950415

I'm closing this because it fits into the discussion category.
