### ISSUE TITLE
🐞 - `LineClamp` breaks cdk virtual scroll

### ISSUE THREAD

**Issue by KarimovDev** [taiga-family/taiga-ui#533]
# 🐞 Bug report

### Description

When tui line clamp is using together with virtual scroll, virtual scrolling behavior is broken

### Reproduction

https://stackblitz.com/edit/taiga-line-clamp-virtual-scroll
Try to scroll down with little speed. You will see something like this:
https://drive.google.com/file/d/13TtkfVXZw_Fx0IAW_SFmNc6QC03JmsZT/view?usp=sharing

It is especially noticeable if template cache size sets to 0

### Expected behavior

Tui line clamp should not break virtual scroll

### Versions

-   Angular 12.1.1
-   Package @taiga-ui/kit@2.13.0

**Comment by splincode** [comment]
<img width="749" alt="image" src="https://github.com/user-attachments/assets/712c938e-68d9-46db-bfd1-e64848c4ead5">

use `appendOnly`
