### ISSUE TITLE
🐞 - DataListWrapper during the search in the dialog, an ExpressionChangedAfterItHasBeenCheckedError occurs

### ISSUE THREAD

**Issue by AlcatrazALT** [taiga-family/taiga-ui#5393]
### Playground Link

https://stackblitz.com/edit/angular-ojdhbm?file=src%2Fapp%2Fpopup%2Fpopup.template.html

### Description

Steps to reproduce:
1. open the dialog
2. start the search

### Angular version

15.2.9

### Taiga UI version

3.40.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by bpioge** [comment]
Hello, I have the exact same issue. 

Note that it appears only when the tui-combo-box (or tui-multi-select) is used in a dialog.
You can easily reproduce the error by pressing two keys at the same time in the search but also just by typing something and then deleting it..
It seems the problem come from the usage of tuiFilterByInputWith.

Angular version : 16.2.5
Taiga UI version : 3.49.1

Sorry if I shouldn't be commenting on this issue.

Thank you for your help !

**Comment by splincode** [comment]
@bpioge could you provide stackblitz repro please?

**Comment by bpioge** [comment]
> @bpioge could you provide stackblitz repro please?

The one provided in the issue is not enough ? https://stackblitz.com/edit/angular-ojdhbm?file=src%2Fapp%2Fpopup%2Fpopup.template.html
I can reproduce my error on this stackblitz (by pressing two keys at the same time in the search but also just by typing something and then deleting it).

**Comment by splincode** [comment]
@bpioge sorry

I don't see a problem when parent have OnPush

<img width="610" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/36311047-6cf6-4151-9108-04c46b3aeca1">

**Comment by bpioge** [comment]
@splincode ok I see. 

I created this stackblitz https://stackblitz.com/edit/stackblitz-starters-k87hjy?file=src%2Fapp%2Fpopup-dynamic%2Fpopup-dynamic.component.html

It's based on Angular 16.5.2 and Taiga 3.49.1.

Since my use case is a little more complicated, I added another button that open a modal with a component that dynamically create a component. Anyway, in this stackblitz, everything is OnPush and the bug appears even with the code of the other stackblitz.

Can you confirm me that you can reproduce it ?

**Comment by bpioge** [comment]
Hello,

Any news on this ? Do you confirm that you reproduce the bug in my stackblitz ?

Thank you for your help.

**Comment by splincode** [comment]
`Do you confirm that you reproduce`

yes
<img width="550" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/f0ba37e8-2b49-4b56-9e84-b9b24428ddcd">

**Comment by waterplea** [comment]
Not reproducible in v4 using the same stackblitz
