### ISSUE TITLE
🐞 - `tuiDropdownHover`: closes after canceling the selection in `tui-select`

### ISSUE THREAD

**Issue by olegnowikow** [taiga-family/taiga-ui#5395]
### Playground Link

https://stackblitz.com/edit/angular-fwx3yj-hhg8tt?file=src%2Fapp%2Fapp.component.html

### Description

This bug is related to #4056

https://github.com/taiga-family/taiga-ui/assets/2184564/f3fa9a16-7df5-4935-99b8-b2af2340d21e

### Angular version

16.2.5

### Taiga UI version

3.44.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Another case where hover closes:
https://stackblitz.com/edit/angular-q1gc25
