### ISSUE TITLE
🐞 - Unexpected scroll behaviour in Dialog component

### ISSUE THREAD

**Issue by anton-marchenko** [taiga-family/taiga-ui#5459]
### Description

1) go to https://taiga-ui.dev/components/dialog#header
2) open dialog
3) click to some text inside the dialog
4) press Page Down button on your keyboard

Actual result: the page outside the dialog has been scrolled down
Expected result: scroll should be allowed only inside the dialog

### Taiga UI version

3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Will be fixed in the upcoming 4.0
