### ISSUE TITLE
🐞 - Dialog opens with 'jump' animation

### ISSUE THREAD

**Issue by ivashchvlad** [taiga-family/taiga-ui#5485]
### Description

1. Go to https://taiga-ui.dev/components/dialog#string
2. Use mobile version of page
3. Open dialog

Actual result: dialog "jumps" (inconsistently)
Expected result: dialog slides from bottom

https://github.com/taiga-family/taiga-ui/assets/54116984/426806d6-4e03-4039-917d-f66ff9c97ac3

### Taiga UI version

3.46.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
[This PR](https://github.com/taiga-family/taiga-ui/pull/5488) fixes it on Android. iOS is, as usual, less cooperative.
