### ISSUE TITLE
🚀 - More type safe MapperPipe

### ISSUE THREAD

**Issue by Frequency21** [taiga-family/taiga-ui#5506]
### Description

The mapper pipe works perfectly, but currently, it's not type safe for more than one arguments, because of any[] varargs.

### Proposed Solution

Since typescript 4.0 we can use variadic tuple types to solve this problem.

(This unfortunately also includes a breaking change in the `TuiMapper` type)

```ts
// helper type
type Arr = unknown[];

export type TuiMapper<T extends Arr, G> = (...args: T) => G;

@Pipe({
  name: "mapper",
})
export class MapperPipe implements PipeTransform {
  transform<T extends Arr, V, G>(
    value: V,
    mapper: TuiMapper<[V, ...T], G>,
    ...args: T
  ): G {
    return mapper(value, ...args);
  }
}
```

This is breaking, because if someone used the type `TuiMapper` in component file, then it must be changed like the following.

```diff
- export type TuiMapper<T, G> = (item: T, ...args: any[]) => G;
+ export type TuiMapper<T extends Arr, G> = (...args: T) => G;

- const mapper: TuiMapper<number, string> = (a,, b) => `${a + b}`;
+ const mapper: TuiMapper<[number, number], string> = (a, b) => `${a + b}`; 
```

**Comment by waterplea** [comment]
Hi @Frequency21. Thank you for this suggestion, would you be willing to make a PR for it?

**Comment by Frequency21** [comment]
Yes, of course

**Comment by Frequency21** [comment]
Hi @waterplea are the pipes broken or I did something?
