### ISSUE TITLE
[BUG] Project not build when TuiDialogService imported to a component

### ISSUE THREAD

**Issue by alexander-kiriliuk** [taiga-family/taiga-ui#554]
# 🐞 Bug report

### Description

Project not build when `TuiDialogService` imported to a component.

### Reproduction

```
  constructor(
    @Inject(TuiDialogService) private readonly dialogService: TuiDialogService,
    @Inject(Injector) private readonly injector: Injector) {
  }
```

> Error: node_modules/@taiga-ui/core/components/dialog/dialog.service.d.ts:7:24 - error TS2416: Property 'component' in type 'TuiDialogService' i
> s not assignable to the same property in base type 'AbstractTuiDialogService<TuiDialogOptions<any>>'.
>   Type 'PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>' is not assignable to type 'PolymorpheusContent<TuiDialog<TuiDialog
> Options<any>, any>>'.
>     Type 'PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>' is not assignable to type 'PolymorpheusComponent<object, TuiDial
> og<TuiDialogOptions<any>, any>>'.
>       Types have separate declarations of a private property 'injector'.
> 
>   protected readonly component: PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>;

### Expected behavior

Build should complete successfully

### Versions

Angular CLI: 12.1.2
Node: 14.16.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 12.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.2
@angular-devkit/build-angular   12.1.2
@angular-devkit/core            12.1.2
@angular-devkit/schematics      12.1.2
@schematics/angular             12.1.2
rxjs                            7.2.0
typescript                      4.3.5
@taiga-ui/cdk 2.12.0
@taiga-ui/core 2.12.0
@taiga-ui/icons 2.12.0
@taiga-ui/kit 2.12.0
@tinkoff/ng-polymorpheus 4.0.0

### Additional context

After install `@tinkoff/ng-polymorpheus` package to project appears this error

**Comment by AlexanderKiriluyk** [comment]
Conflict versions @tinkoff/ng-polymorpheus

**Comment by brianpooe** [comment]
I am getting the very same error tried two different versions of the package. (@tinkoff/ng-polymorpheus 4.0.0 and 3.1.12)

TS2345: Argument of type 'PolymorpheusComponent<LoginComponent, TuiBaseDialogContext<boolean> & TuiDialogOptions<any>>' is not assignable to parameter of type 'PolymorpheusContent<TuiBaseDialogContext<boolean> & TuiDialogOptions<any>>'.   Type 'PolymorpheusComponent<LoginComponent, TuiBaseDialogContext<boolean> & TuiDialogOptions<any>>' is not assignable to type 'PolymorpheusComponent<object, TuiBaseDialogContext<boolean> & TuiDialogOptions<any>>'.     Types have separate declarations of a private property 'injector'.

How did you resolve this?

@AlexanderKiriluyk

**Comment by waterplea** [comment]
You do not need to install polymorpheus on your own. Remove it from your package.json, remove package-lock.json and node_modules and do a clean npm i

**Comment by brianpooe** [comment]
Hi @waterplea thanks for the swift reply but that did not help an import was still required. Managed to get it working by installing version with a lower patch. To assist anybody with the same problem here are the versions i am using that got it working.

    "@taiga-ui/cdk": "^2.23.0",
    "@taiga-ui/core": "^2.23.0",
    "@taiga-ui/icons": "^2.23.0",
    "@taiga-ui/kit": "^2.23.0",
    "@tinkoff/ng-polymorpheus": "^3.1.11",
