### ISSUE TITLE
🐞 - Разные поведения при закрытии выпадающего списка с использованием tuiTextfieldCleaner

### ISSUE THREAD

**Issue by zavod008** [taiga-family/taiga-ui#5598]
### Playground Link

https://stackblitz.com/edit/angular-grj9sv?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html&hideExplorer=1

### Description

При сбросе значения через крест, в select компоненте происходит закрытие списка и сброс значения.

При сбросе значения в комбобоксе, происходит автофокус на инпут и список снова выпадает.

### Angular version

12.2.17

### Taiga UI version

3.48.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by ddubrava** [comment]
Hi! I can work on this, if @waterplea says which variant is the right one

**Comment by waterplea** [comment]
> Hi! I can work on this, if @waterplea says which variant is the right one

Select is the correct one, clicking the cleaner icon should not alter the drop-down state.

**Comment by zavod008** [comment]
@ddubrava, hi,  your pull request work in multiselect?

**Comment by ddubrava** [comment]
> @ddubrava, hi, your pull request work in multiselect?

it fixes `multi-select`, `combo-box` and `input-tag`

**Comment by waterplea** [comment]
Looks like it might be by design, though. I'm checking with our design team.
