### ISSUE TITLE
🐞 - Copying into InputDate/InputDateRange

### ISSUE THREAD

**Issue by raukouski** [taiga-family/taiga-ui#5615]
### Playground Link

https://taiga-aukpah.stackblitz.io/

### Description

It would be great if we copy dates like 11.9.2022 or 7.10.2020 (month or/and day contains only one number) into InputDate/InputDateRange and we have this date into the input as a result.
Now copied value converts like this: 11.9.2022 -> 11.09.022, that's not user friendly.

### Angular version

15.2

### Taiga UI version

3.46

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
The issue will be solved in this issue https://github.com/taiga-family/maskito/issues/593
