### ISSUE TITLE
🐞 - tui-accordion. Баг при раскрытии вложенного контента

### ISSUE THREAD

**Issue by AlekseyPortnyagin** [taiga-family/taiga-ui#5625]
### Playground Link

https://stackblitz.com/edit/angular-wtt9av?file=src%2Fapp%2Fapp.component.html

### Description

При раскрытии внутри аккордеона другого вложенного контента не обновляется `height` у родительского `tui-expand`

### Angular version

16.1.0

### Taiga UI version

3.48.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
А в чём баг? У меня с виду всё работает корректно в этом стэкблице. По завершение анимации у expand выставляется height: auto, так что он и не должен обновлять высоту. Правда он полагается на transitionend событие и с отключенными анимациями оно не наступает — это баг. У вас там, случайно, не выключены анимации?

**Comment by AlekseyPortnyagin** [comment]
При раскрытии вложенного аккордеона контент в нём обрезается из-за некорректной высоты у родителя
![image](https://github.com/taiga-family/taiga-ui/assets/72370575/e9c852e1-614d-4e14-9f4f-54e2990e7f88)
Если его закрыть, то у родительского выставляется не корректная высота для этого состояния. Такая высота должна быть когда вложенный аккордеон открыт
![image](https://github.com/taiga-family/taiga-ui/assets/72370575/c2df2940-60ec-4e7f-aa01-ba7907d1134e)

**Comment by waterplea** [comment]
Но на стэкблице же не так, там после раскрытия вообще убирается явно проставленная высота (корректное поведение) 🤔

**Comment by waterplea** [comment]
Это скрины прямо с него? А какая версия Хрома у вас? Какой Windows?

**Comment by AlekseyPortnyagin** [comment]
Скрины прямо с него были
Версия хрома была 117. Сейчас зашёл, обновил до 118.0.5993.71, стало всё норм...
Windows 10 Pro 10.0.19044

**Comment by AlekseyPortnyagin** [comment]
И действительно не было анимации совсем. Сейчас работает норм 🤔

**Comment by waterplea** [comment]
Тогда закрываю, видимо какое-то временное помутнение. У Хрома 117 вообще не первый и не второй какой-то такой глюк странный, которого раньше не было.
