### ISSUE TITLE
🐞 - `Table` disappearing borders

### ISSUE THREAD

**Issue by waterplea** [taiga-family/taiga-ui#5645]
### Playground Link

https://taiga-ui.dev/components/table

### Description

Sometimes when resizing the table or reordering rows/columns, borders might disappear. Retriggering `isolation: isolate` or any other paint related CSS seems to bring them back:

![image](https://github.com/taiga-family/taiga-ui/assets/11832552/dbc5be6e-202f-4765-8207-c9ab40bc4dff)

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Drogenix** [comment]
@waterplea I figured that removing the `transform: translate3d(0,0,0)` in th and td elements fixes this bug: borders always appear. You can see this in the video:

https://github.com/taiga-family/taiga-ui/assets/101005283/a930ce2b-5b67-4fb3-baab-95fc88aa7666

**Comment by waterplea** [comment]
> @waterplea I have found that removing the `transform: translate3d(0,0,0)` in th and td elements fixes this bug: borders always appear. You can see this in the video:
> 
>  fix.mp4

That's great! We use it to establish new containing block for fixed positioned border on controls inside table. Please see if any of the following options (4th bullet) are a suitable replacement:
https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block

**Comment by Drogenix** [comment]
So i checked them all, `filter: opacity(1)`, for example, works well, but tables with sticky header are still broken... I don't know, how we can fix this :)

**Comment by Drogenix** [comment]
No, they are just broke, even with `transform: translate(0)`. `filter` doens't have any affect on them

**Comment by Drogenix** [comment]
@waterplea I didn't find any better solution then using `filter` and animation for th element (which we discussed earlier in telegram) to force the browser to repaint our table. Animation look like this:
```css
@keyframes repaint{
    100%{
        tab-size: 1;
    }
}
```
What do you think?

**Comment by waterplea** [comment]
> @waterplea I didn't find any better solution then using `filter` and animation for th element (which we discussed earlier in telegram) to force the browser to repaint our table. Animation look like this:
> ```css
> @keyframes repaint{
>     100%{
>         tab-size: 1;
>     }
> }
> ```
> What do you think?

Ok, let's go for it for the time being.

**Comment by Drogenix** [comment]
Sure, we don't have any reason to rush with adding of this "solution". I'll try to find any other way to fix this problem :)

**Comment by waterplea** [comment]
I've merged fix for regular cells for now, thank you for the PR 👍

**Comment by Drogenix** [comment]
@waterplea I think we should undo my PR. because no any properties but `transform` that won't cause this problem with establishing new containing block. I checked them all, and even if they work, they have low support (in Safari especially)

**Comment by waterplea** [comment]
> @waterplea I think we should undo my PR. because no any properties but `transform` that won't cause this problem with establishing new containing block. I checked them all, and even if they work, they have low support (in Safari especially)

How about we return transform only for Safari?

**Comment by Drogenix** [comment]
>How about we return transform only for Safari?

It'd be great, i think :)

**Comment by Drogenix** [comment]
I also noticed some weird behaviour, is it normal? It does appear always, no matter we use `transform: translate3d(0, 0, 0)` or `filter: opacity(1)` or any other similar property for th/td element

https://github.com/taiga-family/taiga-ui/assets/101005283/be4fcb07-4111-45fb-b377-cdeb93d3514d

**Comment by splincode** [comment]
@waterplea Hello, is this still a problem?

**Comment by waterplea** [comment]
> @waterplea Hello, is this still a problem?

I think it is fixed for most of the cases, but but not for all. Let's leave it open for now.

**Comment by waterplea** [comment]
Closing this as it seems to be fixed for most cases and in v5 we will completely drop the transform after we drop all legacy controls
