### ISSUE TITLE
🐞 - dropdown in tui-tabs can't be opened

### ISSUE THREAD

**Issue by giowhatever** [taiga-family/taiga-ui#5677]
### Description

The bug can be reproduced by visiting [https://taiga-ui.dev/navigation/tabs#complex](url)  by shrinking the screen in dev mode and clicking on the collaborators tab will not expand as expected.
![bug report taiga-ui-tab](https://github.com/taiga-family/taiga-ui/assets/51022467/53c93d8f-054d-4892-a75e-00b5c57ab3fb)

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
No longer reproduced

**Comment by splincode** [comment]
What about 

<img width="374" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/318daa4e-b438-4dab-ab2a-594e1a58a8df">

**Comment by waterplea** [comment]
It's a separate issue I'm looking into: https://github.com/taiga-family/taiga-ui/issues/5272
