### ISSUE TITLE
🚀 - Change status-bar color when opening dialog

### ISSUE THREAD

**Issue by zergunteg** [taiga-family/taiga-ui#5685]
### Description

When dialog and sheetDialog are used in PWA applications, there is an issue that the status bar remains the same color as the main background of the application. It would be better to dynamically change the color of the status bar when the dialog is opened. 

`document.querySelector('meta[name="theme-color"]')?.setAttribute('content', content)`

i suggest using а `#404040` or `#333` color

**Comment by splincode** [comment]
@waterplea Is it should be a tui service for dynamic changes meta color?

```ts
service = inject(TuiMetaColorService);

// ...

service.setColor('red');
```

**Comment by waterplea** [comment]
> @waterplea Is it should be a tui service for dynamic changes meta color?
> 
> ```ts
> service = inject(TuiMetaColorService);
> 
> // ...
> 
> service.setColor('red');
> ```

Sounds good. It should also allow getting it so that dialogs can restore it after they are closed. Also we need to think if it should be always on, maybe some apps have it configured to some color that works well with open dialogs 🤔
