### ISSUE TITLE
🐞 - Dialog service (Polymorpheus Content)

### ISSUE THREAD

**Issue by alexKefa** [taiga-family/taiga-ui#5698]
### Description

Dialog window does not show up. Just a blank transparent black effect like it used to but without any content.  

![image](https://github.com/taiga-family/taiga-ui/assets/44241878/29dd6d02-6e66-4adf-9786-a348bec7087f)

### Angular version

16.2`

### Taiga UI version

3.49

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by alexKefa** [comment]
Recompiled and magically fixed..

**Comment by spicy-tomato** [comment]
For anyone stuck in this issue, it can be resolved by upgrading @tinkoff/ng-polymorpheus to v4.1.0 or upper.
