### ISSUE TITLE
🐞 - Notification - handle long label text without spaces

### ISSUE THREAD

**Issue by r0ss0neri** [taiga-family/taiga-ui#5714]
### Playground Link

https://stackblitz.com/edit/angular-gxvq2z?file=src%2Fapp%2Fapp.component.ts

### Description

<img width="1098" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/24474497/c615c974-68f6-47f6-b21d-fed8ba3f1629">

### Angular version

16.2.4

### Taiga UI version

3.49.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Which prefer?

1.

<img width="344" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/d3985e38-4e5b-4ea1-b51d-556da7573e7c">

2.
<img width="349" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/e8596238-5324-425d-a17a-bccbd25c650f">

**Comment by waterplea** [comment]
Second is fine, I think
