### ISSUE TITLE
🐞 - PolymorpheusComponent import does not resolved when using pnpm

### ISSUE THREAD

**Issue by hatsantos** [taiga-family/taiga-ui#5715]
### Git Repo Link

`git clone https://hatsbytes@bitbucket.org/hatslab/taigauipnpm.git`

### Description

When using pnpm as the dependencies manager the import: 

`import { PolymorpheusComponent } from '@tinkoff/ng-polymorpheus'; `

is not resolved.

If dependencies are installed using npm the import is resolved without any additional dependencie declared in the package.jon.

This can be reproduced with a sample app angular app:

1) Install pnpm: npm install -g pnpm
2) Start a new angular cli project: ng new
3) Add taigaui framework: ng add taiga-ui (add/selected all features for example)
4) Add the import import { PolymorpheusComponent } from '@tinkoff/ng-polymorpheus'; and check that can be resolved;
4) Remove node_modules e package-lock.json
5) Install dependencies with pnpm: pnpm install
6) Check the import: ` import { PolymorpheusComponent } from '@tinkoff/ng-polymorpheus';`  is not resolved;

### Angular version

16.2.x

### Taiga UI version

3.49.1

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Could you provide your git repo for reproduce?

**Comment by hatsantos** [comment]
I have updated the initial message with the repo link: 

`git clone https://hatsbytes@bitbucket.org/hatslab/taigauipnpm.git`


When installing dependencies with npm:

![image](https://github.com/taiga-family/taiga-ui/assets/36542752/6c5e6048-8777-4601-8da1-27727b067475)

When installing dependencies with pnpm:

![image](https://github.com/taiga-family/taiga-ui/assets/36542752/c93436fe-cddb-4bc1-a7bf-9accb2ea85c1)
