### ISSUE TITLE
🚀 - Illustration Theming

### ISSUE THREAD

**Issue by uladzimir-miadzinski** [taiga-family/taiga-ui#5727]
### Description

Привет, как насчёт того чтобы на уровне библиотеки предоставить `InjectionToken` для темы чтобы можно было запровайдить через него то, какая активная тема на сайте.

А то сейчас чтобы такое сделать надо писать свой собственный компонент-костыль который получает тему, дописывает в конце строки иллюстрации `Dark`/`Light`, и такое не очень поидее делать...

Было б классно передавать в темплейте названия иллюстраций без `Dark`/`Light`, а просто, к примеру 
```
<img [src]="'suitcasePlus' | tuiIllustration: 'invest'"/>
```

И где-нибудь в провайдерах было б классно переопределять тему через функцию предоставляемую вашим же пакетом типа `provideTuiIllustrationTheme(theme: TuiIllustrationTheme)`, где `TuiIllustrationTheme = Dark / Light` или через `provide: TUI_ILLUSTRATION_THEME_TOKEN, useValue...`

Так же предложение выставлять наружу `enum TuiIllustration` с возможными изображениями, чтобы не писать всё строчками в коде и не суппортить свою enum содержащую эти строки.
Таким образом юзейдж будет такой:
```
// *.component.html
<img [src]="'TuiIllustration.SuitcasePlus' | tuiIllustration: 'invest'"/>

// main.ts
bootstrapApplication(RootComponent, {
  providers: [
    provideTuiIllustrationTheme(TuiIllustrationTheme.Light)
  ]
});
```
Ну или аналогичное решение к примеру через `@Pipe` как нибудь, тоже сойдет, хоть и менее привлекательное, хотя как вторую опцию одновременно существующую с первой и более приоритетную я бы тоже рассматривал :slightly_smiling_face:

Спасибо за внимание :slightly_smiling_face:

**Comment by splincode** [comment]
release in v3.51 in proprietary core

**Comment by loxy** [comment]
Can you please give more insights here? Will there be documentation for it? Or is this something which will not be general available?

**Comment by waterplea** [comment]
> Can you please give more insights here? Will there be documentation for it? Or is this something which will not be general available?

Sorry, this got spilled here by accident, it's regarding a proprietary pipe for our internal set of illustrations used in our apps.
