### ISSUE TITLE
Duplicate Code 52 When Inputting Digit '2' After Clearing

### ISSUE THREAD

**Issue by timurcosta** [taiga-family/taiga-ui#5787]
### Playground Link

https://taiga-ui.dev/components/input-phone/API?countryCode=%2B52&tuiTextfieldCleaner=true🐞 - 

### Description

**Steps to Reproduce:**

1. Select the country code +52 and enable tuiTextfieldCleaner. 
2. Enter any number into the field.
3. Click on the 'x' icon to clear the input.
4. Input the digit '2'. The code '52' is duplicated (both in the mask and in the value). `+52 (52`

### Taiga UI version

3.5.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Link: https://github.com/taiga-family/maskito/issues/595

**Comment by sabeliam** [comment]
Is it correct for **tuiTextfieldCleaner** to clear everything, including country code?

**Comment by nsbarsukov** [comment]
## Expected behaviour:

When user click on `x`-icon:

* If `InputPhone` has `[allowText]=false` => textfield value equals to `[countryCode]`.
* If `InputPhone` has `[allowText]=true` => textfield value equals to empty string.
