### ISSUE TITLE
🐞 - dialogs not working on iOS after upgrade from 3.46.0 to 3.51.0

### ISSUE THREAD

**Issue by VictorienTardif** [taiga-family/taiga-ui#5794]
### Description

I'm sorry I don't have time right now to provide a reproduction but after upgrading to last version (3.51.0) dialogs were not displayed on iOS (native platform) and downgrading to our current version (3.46.0) fixed the issue.

The overlay is displayed but dialog section is empty and there's no way to close the dialog.

### Angular version

16.2.7

### Taiga UI version

3.51.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by splincode** [comment]
Need provide a reproduction

**Comment by waterplea** [comment]
It's probably this:
https://github.com/taiga-family/taiga-ui/issues/5732#issuecomment-1776928591
