### ISSUE TITLE
🤖 - 4.0 migrations

### ISSUE THREAD

**Issue by vladimirpotekhin** [taiga-family/taiga-ui#5808]
### Description

In this discussion we will be listing breaking changes we plan for the next major version. No clear forecast on when it will happen yet. Besides obviously dropping all deprecated stuff, these things will also take place:

- [x] Update Angular to 15/16 (https://github.com/taiga-family/taiga-ui/issues/6158)
- [x] Refactor all CSS variables according to new internal design system
- [x] Move all dependencies to peerDeps to avoid issues with new versions (read ng-polymorpheus issues we constantly face)
- [x] Bump browser support (https://github.com/Tinkoff/taiga-ui/discussions/3232)
- [x] Refactor dialogs/alerts so you won't need to add modules to global module
- [x] Refactor input-files so that there is no built-in rejection mechanism, provide utils for external file processing
- [x] Make all i18n dynamic (number format, date format, etc.)
- [x] Use `--tui-radius-l` on large controls

This list will be updated as we collect more necessary migrations.

We need to cover as many breaking changes with migrations as possible. 

# Migration list

## Experimental

- [x] `Badge`
- [x] `BadgedContent`
- [x] `ThumbnailCard`
- [x] `Avatar`
- [x] `Checkbox`
- [x] `Radio`
- [x] `Radio` identityMatcher? 
- [x] `Toggle`
- [x] `Button`

## CDK

- [x] `TuiMapper / TuiMatcher` 
- [x] `TuiPreventDefault` -> `(event.prevent)="0"`

## Core

- [x] `PrimitiveTextfield` - prefix, postfix, filler
- [x] `TuiAlertOptions` - autocloseTimer, hasIcon
- [x] `HostedDropdown` -> `DropdownOpen`

## Kit
- [x] `InputCount`  --> `InputNumber`
- [x] `InputNumber, InputSlider` -  prefix, postfix
- [x] `InputTag`, `Multiselect`, `InputDateMulti` -  [expandable]=false --> [rows]=1
- [ ] [nativeId] --> id. (toggle, checkbox, etc)
- [ ] InputNumber. [precision][decimal] --> [tuiNumberFormat]={decimalMode, precision}
- [x] progress-segmented  
- [ ] date format
- [x] rating
- [x] thumbnail-card
- [x] Prompt renamed to Confirm
- [x] tuiMobileTabs --> segmented
- [x] `Action` -> `CardLarge`
- [x] marker icon -> avatar
- [ ] `Tag` -> `Chip`

## Addon-table
- [x] `TablePagination` pageChange, sizeChange --> paginationChange

**Comment by waterplea** [comment]
We need to change `--tui-radius-xl` to 1rem and add xxl for 1.5rem

**Comment by waterplea** [comment]
# Migration for `HostedDropdown`.

Before:
```html
<tui-hosted-dropdown
  [content]="template"
  [sided]="sided"
  [canOpen]="canOpen"
  [(open)]="open"
>
  <button>One</button>
  <button tuiHostedDropdownHost>Two</button>
</tui-hosted-dropdown>
<ng-template #template>Wow</ng-template>
```

After:
```html
<div
  [tuiDropdown]="template"
  [tuiDropdownSided]="sided"
  [tuiDropdownEnabled]="canOpen"
  [(tuiDropdownOpen)]="open"
>
  <button>One</button>
  <button #tuiDropdownHost>Two</button>
</div>
<ng-template #template="polymorpheus" polymorpheus>Wow</ng-template>
```

1) Template needs to use `polymorpheus` now
2) `tuiHostedDropdownHost` is now `#tuiDropdownHost`
3) `sided` is now `tuiDropdownSided` directive
4) `content` is now `tuiDropdown` directive
5) `canOpen` input is now `tuiDropdownEnabled` input
6) `open` banana is now `tuiDropdownOpen` banana
7) If wrapping just one element — directives can be moved directly on that element
8) If `open` tracking is not needed, it can be just attribute `tuiDropdownOpen` without any binding

**Comment by waterplea** [comment]
### ResizeObserver

PR: https://github.com/taiga-family/taiga-ui/pull/6537

- Migrate `(tuiResize)` to `(waResizeObserver)`
- Migrate `TuiResizeModule` to `ResizeObserverDirective` (once we update to standalone)
- Migrate `TuiResizeService` to `ResizeObserverService`

**Comment by waterplea** [comment]
Duration -> Speed:
https://github.com/taiga-family/taiga-ui/pull/6542

**Comment by waterplea** [comment]
# Portals and Popovers

- [ ] Remove `tuiAsDialog`, `tuiAsAlert`
- [ ] `*tuiPortal`/`<ng-template [tuiPortal]="x"` directive is renamed to `*tuiDropdown`/`<ng-template [tuiDropdown]="x"`
- [ ] `autoClose: false` is changed to `autoClose: 0` in alerts
- [ ] `tuiOverPortals` content projection changed to `tuiOverDropdowns`
- [ ] `TUI_NOTIFICATION_OPTIONS` changed interface and got broken down to `TUI_NOTIFICATION_OPTIONS` and `TUI_ALERT_OPTIONS`

## Renamed tags
- [ ] `tui-dialog-host` to `tui-dialogs`
- [ ] `tui-alert-host` to `tui-alerts`
- [ ] `tui-dropdown-host` to `tui-dropdowns`

## Changes to abstract dialog class

It used to be `defaultOptions` and this:
```ts
@Injectable({
    providedIn: 'root',
})
export class TuiDialogService extends AbstractTuiDialogService<TuiDialogOptions<any>> {
    protected readonly component = DIALOG;
    protected readonly defaultOptions: TuiDialogOptions<any> = {
        ...inject(TUI_DIALOG_OPTIONS),
        data: undefined,
    };
}
```
Now it is `options` and this:
```ts
@Injectable({
    providedIn: 'root',
    useFactory: () =>
        new TuiDialogService(TUI_DIALOGS, TuiDialogComponent, inject(TUI_DIALOG_OPTIONS)),
})
export class TuiDialogService extends TuiPopoverService<TuiDialogOptions<any>> {}
```

**Comment by waterplea** [comment]
# InputFiles

- [ ] `InputFiles` now moved to `TuiFilesModule`
- [ ] `accepts` renamed to `accept`
- [ ] `removed` output on `tui-file` now renamed to `remove`
- [ ] `src` no longer creates a link inside `tui-file`. Instead use `<a tuiFile ...`
- [ ] `reject` event now always fires an array of rejected files and **rejected files remain in the control**
- [ ] Use `tuiFileRejected` pipe to display rejected file with a formatted reason
- [ ] Native input inside is now required and the wrapper has changed from `<tui-input-files` to `<label tuiInputFiles`, control moved to native input

See examples for the last 3 points, they are probably not 100% migratable so we will need some comment added.

**Comment by splincode** [comment]
- [] Remove TuiRoutableDialogModule

**Comment by vladimirpotekhin** [comment]
## Progress segmented

### before 
```
<tui-progress-segmented
      [colors]="color"
      [max]="max"
      [size]="size"
      [value]="value"
 >
```

### after
```
<progress
    tuiProgressBar
    [segments]="max"
    [tuiProgressColorSegments]="color"
    [max]="max"
    [size]="size"
    [value]="value"
></progress>
```

**Comment by vladimirpotekhin** [comment]
## Rating

### before 
```
<tui-rating
    iconFilled="tuiIconHeartLarge"
    iconNormal="tuiIconHeart"
    class="red"
    [(ngModel)]="thirdRate"
></tui-rating>
```

### after
```
// TODO: for custom icons see example ...
<tui-rating
    [icon]="icon"
    class="red"
    [(ngModel)]="thirdRate"
></tui-rating>

// TODO: for rating size and gap customization use css, see example ...
--tui-rating-size
--tui-rating-gap
```

**Comment by waterplea** [comment]
## Buttons migration:

- [ ] icon -> iconLeft
- [ ] TuiButtonLoadingComponent from kit if [loading] is used
- [ ] shape="rounded" -> [style.border-radius.%]="100"
- [ ] `showLoader` -> `loading`

**Comment by splincode** [comment]
## Color migration:

- [ ] use variables from design tokens for proprietary scope

**Comment by waterplea** [comment]
- [ ] `TUI_ARROW` content now replaced by `tuiChevron` directive

**Comment by waterplea** [comment]
# Link

- [ ] `icon` + `iconAlign` now changed to `iconLeft` / `iconRight`
- [ ] `--tui-link-icon-size` changed to `--tui-icon-size`
- [ ] `iconRotated` changed to `tuiChevron`
- [ ] `tuiMode` no longer relevant, use `appearance="icon"` to imitate it

**Comment by waterplea** [comment]
- [ ] If we see some customization to `tui-svg` we need to put a TODO reminding people that all internal icons moved to `tui-icon`

**Comment by vladimirpotekhin** [comment]
## tag to chip 

disabled, separator, leftContent - ?

### before
```
 <tui-tag
    [size]="size"
    [status]="status"
    [value]="item"
/>
```

### after
```
<tui-chip
    [size]="size"
    [appearance]="status"
>{{ value }}</tui-chip>
```

`editable`, `removable`, `hoverable`, `maxLength` ---> `<input tuiChip />`, `<button tuiChip />` see [interactive example](https://taiga-ui.dev/next/experimental/chip#interactive)

**Comment by splincode** [comment]
## replace tui-table-pagination outputs

### before

```
<tui-table-pagination
    [total]="237"
    [(page)]="page"
    [(size)]="size"
></tui-table-pagination>
```

### after

```
 <tui-table-pagination
    [page]="page"
    [size]="size"
    [total]="237"
    (paginationChange)="page = $event.page; size = $event.size"
></tui-table-pagination>
```

**Comment by waterplea** [comment]
- [ ] `tuiOverscroll` directive removed, just use `overscroll-behavior` CSS rule instead

**Comment by splincode** [comment]
- [ ] Migrate TuiMobileCalendarDialogModule

### Before 

```ts
imports: [TuiMobileCalendarDialogModule]
```

### After

```
providers: [
    {
        provide: TUI_MOBILE_CALENDAR,
        useValue: TuiMobileCalendarDialogComponent,
    },
],
```

**Comment by waterplea** [comment]
- [ ] `[tuiFocusable]="focusable"` to `[tabIndex]="focusable ? 0 : -1"`

**Comment by splincode** [comment]
Proprietary

- [ ] feeditem - tuiCell
- [ ] feeditemDetails - tuiBlockDetails
- [ ] feeditiemAction - tuiButtonVertical

**Comment by splincode** [comment]
- [ ] `@tinkoff/tui-editor` -> `@taiga-ui/editor`
- [ ] `ng-morph` -> `@taiga-ui/morph`

**Comment by waterplea** [comment]
- [ ] `ActiveZone` no longer needed in nested dropdowns, needs to be removed. `let-close="close"` can be changed to `let-close` since it is now `$implicit`.

**Comment by splincode** [comment]
- [ ] `TuiLetDirective` -> `TuiLet`
- [ ] `TuiButtonDirective` -> `TuiButton`
- [ ] `TuiCardMediumDirective` -> `TuiCardMedium`
- [ ] `TuiCardLargeDirective` -> `TuiCardLarge`

**Comment by waterplea** [comment]
- [ ] change provide of `TUI_NUMBER_FORMAT` to `Observable`

**Comment by waterplea** [comment]
- [ ] change `iconLeft`/`iconRight` to `iconStart`/`iconEnd`

**Comment by waterplea** [comment]
🎉
