### ISSUE TITLE
🐞 - tuiFade incorrectly displayed when the height is reduced

### ISSUE THREAD

**Issue by MillerSvt** [taiga-family/taiga-ui#5814]
### Playground Link

/experimental/fade/API?tuiFadeOffset=4em&tuiFadeHeight=50%25

### Description

<img width="631" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/143048525/a17e3902-e240-448d-9a38-e1a843a6aa0a">

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That is expected, you need to use absolute values like ems, rems or pixels.

**Comment by MillerSvt** [comment]
ok, thank you
