### ISSUE TITLE
🚀 - Sort the menu items in the documentation

### ISSUE THREAD

**Issue by MillerSvt** [taiga-family/taiga-ui#5815]
### Description

Now some of the menu items are arranged in random order, which makes it difficult to navigate through the menu. I suggest sorting all the menu items in alphabetical order and sticking to it in the future.

<img width="151" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/143048525/e4093a90-ee92-49ad-8a11-ecda7326902c">
<img width="214" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/143048525/a8a41e89-e32d-427e-8e5c-4a69605033d0">
<img width="229" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/143048525/62e3da9a-92fa-4c42-839d-3b4d92c576be">
<img width="251" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/143048525/d70c4b83-81ab-47ea-ade7-c136aa2e0f05">

**Comment by waterplea** [comment]
Good idea. Would you be willing to make a PR for it?

**Comment by MillerSvt** [comment]
Yes, I will.
