### ISSUE TITLE
🐞 - Input not blur in Firefox when click outside iframe

### ISSUE THREAD

**Issue by Goodzonchik** [taiga-family/taiga-ui#5845]
### Playground Link

https://stackblitz.com/edit/js-9bqmek?file=index.html

### Description

**Steps:**

1. Open application in iframe.
2. Set focus in tui-input.
3. Click outside iframe.

**Actual:**
Application nothing reaction

**Expected:**
Input set blur state and validation work.

**Description:**
This behavior is also typical for the checkbox.
In Chrome blur is set.

### Angular version

16.2.0

### Taiga UI version

3.48.0

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Goodzonchik** [comment]
Hey, I check this issue from windows and mac, open 4.x docs version and 3.x docs version. This issue is not reproducible in both versions. 😬

**Comment by waterplea** [comment]
Yep, seems like it is now fixed as the StackBlitz provided works correctly
