### ISSUE TITLE
🐞 - Active FeedItem element show separators

### ISSUE THREAD

**Issue by mbogomazov** [taiga-family/taiga-ui#5847]
### Description

When you click on FeedItem element its separators become visible, but it unexpected behaviour because if element is hovered they are always hidden

![image](https://github.com/taiga-family/taiga-ui/assets/23421487/6c4684ac-91f2-413a-bf72-365f36f0f93d)

### Taiga UI version

3.52.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by vladimirpotekhin** [comment]
will be fixed in next release (proprietary)
