### ISSUE TITLE
🐞 - ERROR TypeError: createDOMPurify is not a function

### ISSUE THREAD

**Issue by Addeo** [taiga-family/taiga-ui#5917]
### Description

Hi! I try use Angular SSR with taiga UI, but I catch error after open page in browser - compilation is fine.
After ope page, I see this error:
```
ERROR TypeError: createDOMPurify is not a function
    at constructor (./node_modules/@tinkoff/ng-dompurify/fesm2015/tinkoff-ng-dompurify.js:73:26)
    at factory (./node_modules/@tinkoff/ng-dompurify/fesm2015/tinkoff-ng-dompurify.js:105:136)
    at callback (./node_modules/@angular/core/fesm2022/core.mjs:9454:43)
    at runInInjectorProfilerContext (./node_modules/@angular/core/fesm2022/core.mjs:798:9)
    at hydrate (./node_modules/@angular/core/fesm2022/core.mjs:9453:17)
    at get (./node_modules/@angular/core/fesm2022/core.mjs:9323:33)
    at injectInjectorOnly (./node_modules/@angular/core/fesm2022/core.mjs:842:40)
    at Module.ɵɵinject (./node_modules/@angular/core/fesm2022/core.mjs:848:60)
    at factory (./node_modules/@taiga-ui/core/fesm2015/taiga-ui-core-services.js:32:107)
    at <anonymous> (./node_modules/@angular/core/fesm2022/core.mjs:9454:43)
```
I think it's type error? Maybe you have good solution - change version or add types to server config)
I don't catch any error in standard usage.

### Angular version

16.2.0

### Taiga UI version

3.53.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Could you add your reproduction repo?

**Comment by splincode** [comment]
We haven't problem with dompurify
https://github.com/taiga-family/preview-landing-components/blob/main/apps/demo/src/app/home/home.component.ts#L51

**Comment by waterplea** [comment]
> We haven't problem with dompurify https://github.com/taiga-family/preview-landing-components/blob/main/apps/demo/src/app/home/home.component.ts#L51

We have a module, but do we actually use it anywhere?

**Comment by splincode** [comment]
@waterplea 
https://github.com/taiga-family/preview-landing-components/blob/main/apps/demo/src/app/home/home.component.html#L14
https://github.com/taiga-family/preview-landing-components/blob/main/apps/demo/src/app/home/home.component.ts#L90

**Comment by waterplea** [comment]
Ok. Well, probably should be a pipe there, but still seems to work for us :) Let's wait for @Addeo to respond for a few days.

**Comment by Addeo** [comment]
Thank you, guys! I'll check and write

**Comment by Addeo** [comment]
<img width="914" alt="Screenshot 2023-11-13 at 14 01 27" src="https://github.com/taiga-family/taiga-ui/assets/7202575/4b32cff1-84c2-413b-bb61-30dff2f22d89">

**Comment by Addeo** [comment]
https://github.com/Addeo/angular-ssr-test.git

**Comment by Addeo** [comment]
I run command 
```
    "dev:ssr": "ng run web-oborona-admin:serve-ssr",
    "serve:ssr": "node dist/web-oborona-admin/server/main.js",
    
```
it's not work when the app inside <tui-root>
but if I delete this tag - compilation is fine

**Comment by splincode** [comment]
@Addeo just update that line

<img width="522" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/288be1cc-ef08-433c-a5b6-dac1d143e18d">

and

<img width="552" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/cc54a270-e58d-45af-9f4e-058b18b3b749">

**Comment by Addeo** [comment]
Thanks! now it's work!!
