### ISSUE TITLE
🚀 - Consider alternatives of `text-mask-core` and `dompurify`

### ISSUE THREAD

**Issue by weilueluo** [taiga-family/taiga-ui#5923]
### Description

Hi I just started using `taigu-ui` and getting some warnings in console when using `taigu-ui`:
```
Warning: .../node_modules/@taiga-ui/kit/fesm2015/taiga-ui-kit-directives-mask.js depends on 'text-mask-core'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: .../node_modules/@tinkoff/ng-dompurify/fesm2015/tinkoff-ng-dompurify.js depends on 'dompurify'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

- [text-mask-core](https://github.com/text-mask/text-mask/tree/master) is no longer maintained, alternatives:
	- https://github.com/uNmAnNeR/imaskjs
	- https://github.com/JsDaddy/ngx-mask
	- https://github.com/Tinkoff/maskito
- [dompurify](https://github.com/cure53/DOMPurify), alternatives not sure.

**Comment by splincode** [comment]
if you really want, you can add
https://angular.io/guide/build#configuring-commonjs-dependencies

```json
 "allowedCommonJsDependencies": [
        "@taiga-ui/kit",
        "@tinkoff/ng-dompurify"
     ]
```

**Comment by waterplea** [comment]
`text-mask-core` is bundled only for backwards compatibility, it is no longer used. Taiga UI uses `maskito` everywhere.

There are no alternatives for `dompurify` and it is also not a required library for Taiga UI. I think once we move to the new `tui-icon` component it would only be recommended for `tui-editor`, which is a separate project now.
