### ISSUE TITLE
🐞 - `.t-mark` in `tui-radio` disappears after toggling `tui-expand`

### ISSUE THREAD

**Issue by dzolotarova** [taiga-family/taiga-ui#5946]
### Playground Link

https://stackblitz.com/edit/angular-8j7kq1?file=src%2Fapp%2Fapp.component.ts

### Description

If the `tui-radio` is inside the `tui-expand` and content projection is used, the `.t-mark` has zero width and height after toggling the `tui-expand`. This bug only occurs when using content projection. If `ng-template` is used, everything works fine

I guess it might be related to animation, but I'm not sure

**Steps to reproduce:**
1. Open `tui-expand`
2. Select some radio
3. Close `tui-expand`
4. Open `tui-expand` again

**Result:** The selected radio doesn't have a white circle inside

![image](https://github.com/taiga-family/taiga-ui/assets/36307205/ecd21bcf-a1da-4276-938f-d5c091df67d4)

### Angular version

16.2.7

### Taiga UI version

3.42.1

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
As a workaround for now, you can start switching to the new radio component which is planned to replace current one:
https://taiga-ui.dev/experimental/radio

**Comment by EricPoul** [comment]
But it's a workaround only for plain radion. Labeled radio and radio block still use non-experimental radion under the hood.

**Comment by waterplea** [comment]
Sure. We will fix this bug before moving to 4.0 and new controls. It's just a tip for those who need it now.

**Comment by Drogenix** [comment]
@waterplea I can try to fix this one. Do we know any possible reasons of why this bug happens?

**Comment by waterplea** [comment]
> @waterplea I can try to fix this one. Do we know any possible reasons of why this bug happens?

This is most likely a bug with Angular animations. You can try removing angular animation from radio and instead use CSS transform to scale it.

**Comment by Drogenix** [comment]
> You can try removing angular animation from radio and instead use CSS transform to scale it.

This is work. And i also found that `tuiParentAnimation` cause this bug. I don't know exactly why, for some reason it's just blocks child animation. I removed `tuiScaleAnimation`, CSS animation looks like this:

```css
@keyframes fadeIn {
    0%{
        transform: scale(0);
    }
    100%{
        transform: scale(1);
    }
}
```

https://github.com/taiga-family/taiga-ui/assets/101005283/0be7cc96-613f-4993-9321-052d35e0d60f

**Comment by Drogenix** [comment]
> Parent animation is there to kick in :leave animations — it's a long standing Angular bug. What if you add the same line to kick in :enter animations in TUI_PARENT_ANIMATION? Would that fix the issue? Not that it's better than CSS solution, just want to fix tuiParentAnimation as well, if possible.

Yeah, i know about this bug. I added this in TUI_PARENT_ANIMATION, but it has zero effect:

```js
transition(`:enter`, [query(`* <=> *`, [animateChild()], {optional: true})]),
```

And also, what is the `:scope` selector? I see this for the first time

```js
transition(`:leave`, [query(`:scope > *`, [animateChild()], {optional: true})]),
```

**Comment by waterplea** [comment]
Yeah, I meant to try that. Ok, if it doesn't work then let's leave it at that. `:scope` selector is kinda like `this` in CSS:
https://developer.mozilla.org/en-US/docs/Web/CSS/:scope

**Comment by waterplea** [comment]
As for the CSS animation — remove `ngIf` so this `.t-mark` is always there and just toggle some class like `.t-mark_visible` and use transition instead of animation. This way to would work both ways.
