### ISSUE TITLE
🚀 - Input Inline Autocomplete 

### ISSUE THREAD

**Issue by 1zaboy** [taiga-family/taiga-ui#5953]
### Description

**Text field or Textarea field** with template text for autocomplete after pres button of keyboard. For example key of keyboard TAB.
Probably, this can be implemented as directive.

I found link to React library Demo: https://kyuch4n.github.io/react-inline-autocomplete/
![image](https://github.com/taiga-family/taiga-ui/assets/33203144/6ca9bc44-3dac-41bb-a14c-84b951c72a4a)

**Comment by waterplea** [comment]
This is not something we plan on adding, since it can be implemented already with a few lines of code:
https://stackblitz.com/edit/angular-rjhczr
