### ISSUE TITLE
🐞 - Move of Tiles and Move mark view

### ISSUE THREAD

**Issue by 1zaboy** [taiga-family/taiga-ui#5954]
### Playground Link

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Description

Move video tile to other position (left) so difficult.
![image](https://github.com/taiga-family/taiga-ui/assets/33203144/ed94d44d-13d7-40a6-a9c3-e940e5f257e6)

If we move mouse to touch mark on video tile we see strange touch mark.
![image](https://github.com/taiga-family/taiga-ui/assets/33203144/b363f95f-b71c-442c-999f-a124e9cd2a85)

### Angular version

12.2.17

### Taiga UI version

3.54.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I'm not sure what you mean by "difficult". You just move your cursor above tile and grab that marker, then move your pointer over another tile to switch place with it:
![image](https://github.com/taiga-family/taiga-ui/assets/11832552/6b964266-0f1d-4ba8-a371-47b8a8fc719d)
As for the "strange marker" — that's just a basic demo, you can design it any way you want. Feel free to clarify if I'm missing something.
