### ISSUE TITLE
🐞 - Error of scroll on documentation website

### ISSUE THREAD

**Issue by 1zaboy** [taiga-family/taiga-ui#5955]
### Description

Error of scroll on documentation website
I can not scroll to end of list
![image](https://github.com/taiga-family/taiga-ui/assets/33203144/8790f504-39de-455b-b9dd-907410718e37)

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I'm not able to reproduce. What Chrome version are you using?

**Comment by 1zaboy** [comment]
Version 119.0.6045.124 (Official build), (64 bit)
Judging by DOM, block wrapper not recalculate height for block of list

**Comment by waterplea** [comment]
I have the same version 🤔 Do you, by any chance, have some extensions enabled that might mess with CSS transitions/animations? Does this reproduce for you every time on current taiga-ui.dev when you open a subcategory, such as Utils? Or Utils specifically?

**Comment by 1zaboy** [comment]
![image](https://github.com/taiga-family/taiga-ui/assets/33203144/c4cee916-c3bc-46a5-9741-9d4694d606e6)
I have same situation on clear Firefox
![image](https://github.com/taiga-family/taiga-ui/assets/33203144/4796c998-f5f8-4651-afb2-749a878da590)
Firefox: 119.0.1 (64-разрядный)
If I open About Firefox and click close window, this problem goes away
I can write video with this If need
