### ISSUE TITLE
🐞 -  providerAnimation instead of provideAnimations

### ISSUE THREAD

**Issue by benjaminforras** [taiga-family/taiga-ui#5993]
### Description

When I added taiga-ui using the **ng add taiga-ui** command it updated the **app.config.ts** file and added the required providers, however it added the animations provider wrong.

It imported **providerAnimation** instead of **provideAnimations**

### Angular version

17.0.0

### Taiga UI version

3.54.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Fixed by https://github.com/taiga-family/taiga-ui/pull/5975
