### ISSUE TITLE
🚀 - InputPhoneInternational & tuiFormatPhone pipe

### ISSUE THREAD

**Issue by akanellis** [taiga-family/taiga-ui#6009]
### Description

InputPhoneInternational component is great. It takes `[countries]` as parameter in the ISO country code format ('US', 'CA" etc).
But the `tuiFormatPhone` pipe takes `countryCode` which is the country dial prefix ('+1', '+44' etc).

This raises the problem that if I want to use the InputPhoneInternational component, I need to store somewhere the ISO country code so that the next time the phone edit form opens, will display the country correctly and at the same time when I want to just display a formatted phone number, I need to have the country dial prefix stored somewhere separately as well (which is not possible just from looking at an international phone number without using 3rd party lib, because country dial prefixes are not fixed in length). Because if I don't provide a country dial prefix, then the phone number is formatted with the +7 by default.

I propose as solution that you modify `tuiFormatPhone` pipe so that it takes as parameter the ISO country code as well.

**Comment by waterplea** [comment]
Thank you for your suggestion. Let's revisit this once we move input phone to @maskito/phone in 4.0

**Comment by nsbarsukov** [comment]
New version of `InputPhoneInternational` is coming in `Taiga@v4`.
It will be based on [`@maskito/phone`](https://maskito.dev/addons/phone) and [`libphonenumber-js`](https://www.npmjs.com/package/libphonenumber-js) library.


## Legacy `tuiFormatPhone` utility
https://github.com/taiga-family/taiga-ui/blob/5fc4e5ce7c5166255593037aaec0303d7ea6b146/projects/legacy/utils/format-phone.ts#L31-L35

It can be replaced with the following code:

```ts
import {maskitoTransform} from '@maskito/core';
import {maskitoPhoneOptionsGenerator} from '@maskito/phone';
import metadata from 'libphonenumber-js/max/metadata';

const options = maskitoPhoneOptionsGenerator({countryIsoCode: 'US', metadata});
maskitoTransform('12125552368', mask); // +1 (212) 555-2368
```

or 

```ts
import {maskitoTransform} from '@maskito/core';

const mask = {
    mask: ['+', '1', ' ', /\d/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/],
};
maskitoTransform('12125552368', mask); // +1 (212) 555-2368
```

## Legacy `tuiFormatPhone`-pipe
https://github.com/taiga-family/taiga-ui/blob/5fc4e5ce7c5166255593037aaec0303d7ea6b146/projects/legacy/pipes/format-phone/format-phone.pipe.ts#L7-L11

It can be replaced with the following code:
```ts
import {maskitoTransform} from '@maskito/core';
import {maskitoPhoneOptionsGenerator} from '@maskito/phone';
import metadata from 'libphonenumber-js/max/metadata';

@Component({
    standalone: true,
    imports: [MaskitoPipe],
    template: `
        Phone: ${{'12125552368' | maskito: options}}
        <!-- Phone: +1 (212) 555-2368 -->
    `,
})
export class YourComponent {
    options = maskitoPhoneOptionsGenerator({countryIsoCode: 'US', metadata});
}
```

___

Learn more:
* https://github.com/taiga-family/taiga-ui/pull/7518
