### ISSUE TITLE
🚀 - Add a TOKEN to configure base url for relative urls in TuiStaticRequestService

### ISSUE THREAD

**Issue by VictorienTardif** [taiga-family/taiga-ui#6099]
### Description

When using `TuiSvg` with relative paths to svg file in `/assets` folder, it does not work when using SSR as urls need to be absolute on server side. 

 For any other assets, I use an `HttpInterceptor` to add the right base url in regards of the current env but I don't have control on the calls made by the `TuiStaticRequestService` for the svgs.

One solution would be to check if the url is relative or absolute in the service and to add a base url set in a token like you already do with `TUI_BASE_HREF`.

**Comment by splincode** [comment]
Possible solution
https://github.com/taiga-family/taiga-ui/pull/5653/files

**Comment by splincode** [comment]
@waterplea Is`tui-svg` deprecated?

**Comment by waterplea** [comment]
Not yet, we will still have it on 4.0, but we will need to reassess if we want to support it after we migrate everything to `tui-icon`.

**Comment by splincode** [comment]
@waterplea is it relevant?
