### ISSUE TITLE
🐞 - bug in running project with taiga 

### ISSUE THREAD

**Issue by yasinsiadat** [taiga-family/taiga-ui#6111]
### Description

we have a project in Angular and use Taiga UI after a month we clone the project but we facing error , we use the same previous node version and don't change the package.json file of project

system feature:

os : ubuntu 22.0.4

node version 18.18.2

package.json code :
```
{
"name": "project",
"version": "0.0.0",
"scripts": {
"ng": "ng",
"start": "ng serve",
"build": "ng build",
"watch": "ng build --watch --configuration development",
"test": "ng test"
},
"private": true,
"dependencies": {
"@angular/animations": "^16.0.4",
"@angular/cdk": "^16.0.0",
"@angular/common": "^16.0.4",
"@angular/compiler": "^16.0.4",
"@angular/core": "^16.0.4",
"@angular/forms": "^16.0.4",
"@angular/platform-browser": "^16.0.4",
"@angular/platform-browser-dynamic": "^16.0.4",
"@angular/router": "^16.0.4",
"@fortawesome/fontawesome-free": "^6.4.0",
"@metamask/detect-provider": "^2.0.0",
"@taiga-ui/addon-mobile": "^3.38.0",
"@taiga-ui/cdk": "^3.38.0",
"@taiga-ui/core": "^3.38.0",
"@taiga-ui/icons": "^3.38.0",
"@taiga-ui/kit": "^3.38.0",
"@tinkoff/ng-dompurify": "3.0.0",
"@tinkoff/ng-polymorpheus": "^4.1.0",
"@types/node": "^20.2.5",
"angular-svg-icon": "^16.0.0",
"angularx-qrcode": "^16.0.0",
"dompurify": "2.2.9",
"ngx-resize-observer": "^2.5.2",
"primeflex": "^3.3.1",
"rxjs": "~7.8.1",
"ts-node": "^10.9.1",
"tslib": "^2.5.2",
"zone.js": "~0.13.0"
},
"devDependencies": {
"@angular-devkit/build-angular": "^16.0.4",
"@angular/cli": "~16.0.4",
"@angular/compiler-cli": "^16.0.4",
"@types/dompurify": "2.2.3",
"@types/jasmine": "~4.3.2",
"@types/qrcode": "^1.5.1",
"jasmine-core": "~4.6.0",
"karma": "~6.4.2",
"karma-chrome-launcher": "~3.2.0",
"karma-coverage": "~2.2.0",
"karma-jasmine": "~5.1.0",
"karma-jasmine-html-reporter": "~2.0.0",
"typescript": "~5.0.4"
}
}
```
and image of the error :
![image](https://github.com/taiga-family/taiga-ui/assets/80845770/6e66a577-0389-4226-b5a9-b5849182925b)
![Screenshot from 2023-11-27 18-28-55](https://github.com/taiga-family/taiga-ui/assets/80845770/317139c7-0a34-498f-862b-a69065da1acd)
![Screenshot from 2023-11-27 18-29-32](https://github.com/taiga-family/taiga-ui/assets/80845770/a4cc1455-ee98-4ed9-8eb6-eeb29f5558d1)

### Angular version

16.0.4

### Taiga UI version

3.38.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@yasinsiadat Hello!

1. Remove `@tinkoff/ng-polymorpheus` from your `dependencies`.
2. Delete `node_modules` and `package-lock.json`.
3. Run `npm i`.

**Comment by nsbarsukov** [comment]
If problem still persists, try to update to the latest `3.56.0`-version.
And then repeat this algorithm https://github.com/taiga-family/taiga-ui/issues/6111#issuecomment-1829766233.
