### ISSUE TITLE
Combo Box with empty string option is not working properly

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#6166]
### Discussed in https://github.com/orgs/taiga-family/discussions/6162

<div type='discussions-op-text'>

<sup>Originally posted by **erzenhaxhi** December  5, 2023</sup>
Hi, when combo box has one empty string option that value is selected by default and if we select another option and we open the dropdown again the previous value is overridden by empty string.

Can we handle this? Or this need to be reported as bug?

[here is the example](https://stackblitz.com/edit/angular-9atujt)</div>

**Comment by waterplea** [comment]
Basically, the fix is if we have empty `search` inside combobox, but have some native input value we shouldn't match empty string option. Should be easy for external contributors to fix so I'll mark it accordingly.
