### ISSUE TITLE
🐞 - `<svg>` inside `tui-svg` not displayed on iOS/macOS devices

### ISSUE THREAD

**Issue by boarderlicious** [taiga-family/taiga-ui#6250]
### Playground Link

https://stackblitz.com/edit/angular-p1ky3v-xb1md3?file=src%2Fapp%2Fapp.component.html

### Description

Some _svg_-s are not visible, while there's no problem with others. I pinned different examples in the playground.

`<svg>`'s parent `.t-src` is a flex-container. If you change it to `display: block`, _svg_ is displayed (with broken layout, obviously).

Setting `<svg>`'s `min-width`/`width` to some value (e.g. `100%`) also helps, but I doubt it's a universal solution.

### Angular version

16.2.7

### Taiga UI version

3.59.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by waterplea** [comment]
Unfortunately that's just Safari being Safari:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width#svg
Specs say missing `width`/`height` are interpreted as `auto` which should be treated as `100%` which other browsers properly implement, but Safari does not. You need to add explicit `width="100% height="100%"` to your SVG source if you want them to be scalable, or a fixed size of you want fixed size.
