### ISSUE TITLE
🐞 - Internationalization not working with standalone components

### ISSUE THREAD

**Issue by RyanReyMorris** [taiga-family/taiga-ui#6269]
### Description

Please, can you help me with this issue. Trying to change ui language to russian but face these problem: language doesn't change with standalone app component. What am I doing wrong? Works when I use NgModel. Is it a bug or my fault?
![app_component](https://github.com/taiga-family/taiga-ui/assets/107992000/1a5c683b-071a-4f83-8ada-d50df72020f1)
![image](https://github.com/taiga-family/taiga-ui/assets/107992000/e7ad5cb6-44a2-4666-8350-e1c61340ab5a)
![image](https://github.com/taiga-family/taiga-ui/assets/107992000/4647d26a-e05c-4976-8ef6-2716331f3230)

### Angular version

17.0.0

### Taiga UI version

3.59.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Try moving global providers out of the component scope and into the global scope where you bootstrap your app.

**Comment by RyanReyMorris** [comment]
Thank you sooo much, it works!
For others:
1)
`
export const appConfig: ApplicationConfig = {
    providers: [
        {
            provide: TUI_LANGUAGE,
            useValue: of(TUI_RUSSIAN_LANGUAGE),
        }
    ]
};
`
2)
`
bootstrapApplication(AppComponent, appConfig)
  .catch((err) => console.error(err));
`
