### ISSUE TITLE
🐞 - Wrong CODE_OF_CONDUCT.md link after refactoring

### ISSUE THREAD

**Issue by furevor** [taiga-family/taiga-ui#6302]
### Playground Link

https://github.com/taiga-family/taiga-ui/blob/main/CONTRIBUTING.md

### Description

Hello, I've decided to contribute some useful things in taiga-ui library and opened contribution guide for check specific contribution details about this process and found "404 - page not found" for the first link ([Code of Conduct](https://github.com/taiga-family/taiga-ui/blob/main/CODE_OF_CONDUCT.md)) of this guide.

After some research I understand that this file was moved to another repository at 10 of November without link fix (e485e20a)

Let me please make this small fix as my first step to contribution journey in taiga-ui

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Sure, go ahead and update the link 👍
