### ISSUE TITLE
🐞 - `TuiPointerHintModule` not found module in v3+

### ISSUE THREAD

**Issue by volvachev** [taiga-family/taiga-ui#6341]
### Playground Link

https://taiga-ui.dev/directives/hint-pointer/Setup

### Description

The documentation says that for `HintPointer` to work, you need to connect the `TuiPointerHintModule` - now this module does not exist, just connect the `TuiHintModule`.
![image](https://github.com/taiga-family/taiga-ui/assets/34657605/d8b983bd-0c65-438f-8fd1-756cad59aa1d)

Also not-valid url to the source code (https://github.com/taiga-family/taiga-ui/tree/main/projects/core/directives/hint-pointer). Page not found

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Right, that's from 2.x, we refactored that in 3.x

Would you like to make a PR?
