### ISSUE TITLE
🐞 - Error when trying to translate tui-select options using ngx-translate

### ISSUE THREAD

**Issue by atoyansk** [taiga-family/taiga-ui#6349]
### Playground Link

[StackBlitz](https://stackblitz.com/edit/stackblitz-starters-vmhklf?file=src%2Fapp%2Fapp.component.html)

### Description

When I try to use ngx-translate to translate options from tui-select, I faced an error:

`error TS2322: Type 'string' is not assignable to type 'readonly any[]'.`

![image](https://github.com/taiga-family/taiga-ui/assets/12189750/938ebfa2-16de-4e1d-8baf-089c3fb1325f)

My template:

```
<tui-select formControlName="method">
    {{ 'EVENTSFORM.PAYMETHOD' | translate }}
    <select tuiSelect items="{{'EVENTSFORM.' + methods | translate}}"></select>
</tui-select>
```

In TS file:

`methods = [ 'CASH', 'CARD' ];`

And the Json language file:

```
"EVENTSFORM":{
    "CASH": "Cash Payment",
    "CARD": "Credit Card / Debit Card"
}
```

### Angular version

14.0.0

### Taiga UI version

3.50.0

### Which browsers have you used?

-  Chrome
- Firefox

### Which operating systems have you used?

- Windows

**Comment by splincode** [comment]
Do you have source code for example?

**Comment by atoyansk** [comment]
I just updated the issue

**Comment by atoyansk** [comment]
I found the solution:

```
<tui-select formControlName="method" [valueContent]="content">
    {{ 'EVENTSFORM.PAYMETHOD' | translate }}
    <tui-data-list-wrapper *tuiDataList [itemContent]="content" [items]="methods">
    </tui-data-list-wrapper>
</tui-select>

<ng-template #content let-data>
    <div class="name">{{ 'EVENTSFORM.' + data | translate }}</div>
</ng-template>
```
