### ISSUE TITLE
🚀 - Internationalization - Add Hebrew

### ISSUE THREAD

**Issue by atoyansk** [taiga-family/taiga-ui#6359]
### Description

Add Hebrew as a supported language in the i18n Taiga module. 

In some components, it may be necessary to adjust positioning of elements to the RTL direction (e.g. calendar component).

**Comment by nsbarsukov** [comment]
@atoyansk Hello!

Almost all already supported languages by Taiga UI are contributed by community. Feel free to add it too)

Use this tutorial:
https://github.com/taiga-family/taiga-ui/tree/main/projects/i18n#how-to-add-a-language
