### ISSUE TITLE
🐞 - Textarea - error "No value accessor for form control with name"

### ISSUE THREAD

**Issue by atoyansk** [taiga-family/taiga-ui#6374]
### Description

When I try to include the tui-textarea component, it displays the following error:

```
core.mjs:9171 ERROR Error: No value accessor for form control with name: 'textnote'
    at _throwError (forms.mjs:3204:11)
    at setUpControl (forms.mjs:2992:13)
    at FormGroupDirective.addControl (forms.mjs:4858:9)
    at FormControlName._setUpControl (forms.mjs:5417:43)
    at FormControlName.ngOnChanges (forms.mjs:5362:18)
    at FormControlName.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1526:14)
    at callHook (core.mjs:2508:18)
    at callHooks (core.mjs:2467:17)
    at executeInitAndCheckHooks (core.mjs:2418:9)
    at refreshView (core.mjs:12026:21)
```

the TS file

```
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import {
  FormGroup,
  FormBuilder,
  Validators,
  FormControl,
} from '@angular/forms';

@Component({
  selector: 'myapp',
  templateUrl: './app.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements OnInit {
  custDetailForm!: FormGroup;

  constructor(public fb: FormBuilder) {}

  ngOnInit(): void {
    this.custDetailForm = this.fb.group({
      textnote: new FormControl('Here'),
    });
  }
}
```

and the template file:

 ```
 <form [formGroup]="custDetailForm">
    <div class="tui-row tui-space_bottom-10">
      <div class="tui-col_12">
        <div class="tui-form__row">
          <tui-textarea formControlName="textnote" [expandable]="true" [maxLength]="250">
            Type a note here
          </tui-textarea>
        </div>
      </div>
    </div>
  </form>
```

### Angular version

14.0.0

### Taiga UI version

3.50.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by vladimirpotekhin** [comment]
Hi! I can't reproduce the problem on stackblitz https://stackblitz.com/edit/angular-wjvvrm?file=src%2Fapp%2Fapp.component.html

Can you please provide more details or reproduction repo?

**Comment by atoyansk** [comment]
I did realize that you installed the 3.61.0 Taiga version on Stackblitz. Cuurently, my app has a 3.50.0 Taiga version.
Would updating it solve the problem I'm facing?

**Comment by vladimirpotekhin** [comment]
> I did realize that you installed the 3.61.0 Taiga version on Stackblitz. Cuurently, my app has a 3.50.0 Taiga version. Would updating it solve the problem I'm facing?

I’m not sure, I didn’t find any changes in textarea from 3.50 to 3.61 
But anyway, try updating to the latest version and make sure you have imported all the necessary modules (TuiTextareaModule, ReactiveFormsModule).

If the problem persists, try creating a repository with reproduction and provide a link please

**Comment by waterplea** [comment]
Yes, just use small «a». We changed the name since native textarea is written in one word and we wanted our component to be written similarly as tui-textarea.

**Comment by atoyansk** [comment]
Now it's working!
