### ISSUE TITLE
🐞 - extra shadow in dropdown if data list is empty

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#6423]
### Playground Link

https://taiga-ui.dev/components/input-year/API?max=2020&min=2070

### Description

<img width="658" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/fdcee9cd-af66-423b-9ffe-eb14e908f687">

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Is that a bug? I think it's just an empty dropdown with the border.

**Comment by splincode** [comment]
if this is expected behavior, got it
