### ISSUE TITLE
🐞 - Focus Shift Issue in tui-radio-block After Uploading Document with tui-input-files in Form

### ISSUE THREAD

**Issue by em-sargsyan** [taiga-family/taiga-ui#6437]
### Playground Link

https://stackblitz.com/edit/angular-bkyhfx-p92ydw

### Description

Precondition: A form containing both tui-radio-block and tui-input-files components.
After uploading a document, the focus is shifted to the tui-radio-block
Can be reproduced - https://stackblitz.com/edit/angular-bkyhfx-p92ydw

### Angular version

12.2.17

### Taiga UI version

3.61.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by em-sargsyan** [comment]
Uploading Screen Recording 2024-01-11 at 5.27.08 PM (1) (1).mov…

**Comment by em-sargsyan** [comment]
Uploading Screen Recording 2024-01-11 at 5.27.08 PM (1) (1).mov…

**Comment by waterplea** [comment]
It is not moved, it goes back to it. The underlaying issue is clicking input-files does not focus it. Would you like to make a PR?

**Comment by waterplea** [comment]
This is fixed in v4
