### ISSUE TITLE
🐞 - Web Components - `TuiRootComponent` applies a style that affects the host application

### ISSUE THREAD

**Issue by mouadennaciri** [taiga-family/taiga-ui#6473]
### Description

To use Taiga UI in a web component (Angular Elements) that will be used on Angular and non-Angular applications, we need to put the `TuiRootComponent` at the top level of the web component as it's necessary for the other Taiga UI components.

The issue is that `TuiRootComponent` applies CSS styles to the body element ([root.style.less#L21](https://github.com/taiga-family/taiga-ui/blob/v3.62.0/projects/core/components/root/root.style.less#L21)) which breaks the style of the host application.

My suggestion is to add the `data-tui-theme` attribute to the `body {}` selector: `body[data-tui-theme] {}`. 

### Angular version

17.0.9

### Taiga UI version

3.62.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
what about `html`

<img width="219" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/d9251866-4642-4b3c-bc98-e37c3ed3af58">

**Comment by waterplea** [comment]
We should probably move data-tui-theme on HTML. But that might cause some issues for our proprietary projects so this change should be done in 4.0

**Comment by mouadennaciri** [comment]
> We should probably move data-tui-theme on HTML. But that might cause some issues for our proprietary projects so this change should be done in 4.0

Great! Can someone from the core team do that?
