### ISSUE TITLE
🐞 - TuiMultiSelectGroup - control remains pristine after value set 

### ISSUE THREAD

**Issue by r0ss0neri** [taiga-family/taiga-ui#6522]
### Playground Link

https://stackblitz.com/edit/angular-yb1ojs?file=src%2Fapp%2Fapp.component.html

### Description

Form control remains pristine after setting options from multi select group. Seems problem is [here](https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/components/multi-select/multi-select-group/multi-select-group.directive.ts#L30).

https://github.com/taiga-family/taiga-ui/assets/24474497/eb3bb1d4-0e3e-4758-a982-80b8f8c01f7f

### Angular version

17.0.1

### Taiga UI version

3.63.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Let's keep that in mind for 4.0 when all controls will get refactored.

**Comment by damirsaifut** [comment]
There is also such a bug. Control has updateOn: 'blur'. 

https://github.com/user-attachments/assets/188ed8ad-afdf-49b3-bc3d-4f8e5ce3239d

**Comment by damirsaifut** [comment]
There is also no check set to true on the checkbox if we select an item from the list when update: onBlur is enabled.
