### ISSUE TITLE
🐞 - [TuiHostedDropdown] Test logs: "Can't bind to '$.class._hosted_dropdown_focused' since it isn't a known property of 'tui-hosted-dropdown'"

### ISSUE THREAD

**Issue by wh0lesome** [taiga-family/taiga-ui#6524]
### Description

I am using Angular version 17 and the newest Taiga-Ui Version 3.63.0 and get the following error on testing components that use the HostedDropdown Component.

Side note, I have updated Taiga-Ui from version 3.48.0 and the following came in (https://github.com/taiga-family/taiga-ui/blob/main/projects/core/components/hosted-dropdown/hosted-dropdown.component.ts#L96) from the change which I think is the problem.

Following is the logs from the unit-test (simple expect(component).toBeTruthy()).

```ts
NG0303: Can't bind to '$.class._hosted_dropdown_focused' since it isn't a known property of 'tui-hosted-dropdown' (used in the 'MyComponent' component template).
    1. If 'tui-hosted-dropdown' is an Angular component and it has the '$.class._hosted_dropdown_focused' input, then verify that it is a part of an @NgModule where this component is declared.
    2. If 'tui-hosted-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

As I said before, this happends to all unit-tests of the components that use TuiHostedDropdown.

Do I have to provide more than the imported TuiHostedDropdownModule? Can someone help me out here?

### Angular version

17.0.0

### Taiga UI version

3.63.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by loxy** [comment]
We have same problems. Updating from 3.43.0 to 3.60.0 leads to same output when running tests. We are on Angular 15...

**Comment by wh0lesome** [comment]
@waterplea Thank youu!! it works now!
