### ISSUE TITLE
🐞 - DialogService

### ISSUE THREAD

**Issue by MRustem** [taiga-family/taiga-ui#6582]
### Description

1. В мобильном браузере на IOS в диалоге криво работает выделение текста. Можно выделить только один раз, потом ползунки выделения не перемещаются

2. В ComponentDialog на IOS также нелзя двигать ползунки, если в Dialog присутствуют поля зполнения (input, select, etc)

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by MRustem** [comment]
https://github.com/taiga-family/taiga-ui/assets/17471228/052df71b-782c-4a3c-ab39-5d3f9eee5e1b

Воспроизводится в ComponentDialog. В DialogFromString все норм

**Comment by MRustem** [comment]
Если это поможет, то выделения текста начинает работать если закомментить router-outlet в app.component

**Comment by waterplea** [comment]
Will be fixed in the upcoming 4.0
