### ISSUE TITLE
🐞 - Dropdown in card large

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#6615]
### Playground Link

card-large

### Description

https://github.com/taiga-family/taiga-ui/assets/12021443/d07dd26d-1a0b-4164-9f42-fec1f6ad9318

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by splincode** [comment]
@waterplea what do you think, it's a critical?

**Comment by waterplea** [comment]
There's no way to handle it otherwise. Sided should be false on mobile, there's no space for horizontal dropdown.

**Comment by waterplea** [comment]
Let's either update the example or close this as not planned.
