### ISSUE TITLE
🐞 - how to style component in table

### ISSUE THREAD

**Issue by Addeo** [taiga-family/taiga-ui#6669]
### Playground Link

https://github.com/Addeo/test-taiga

### Description

I have the problem with styles input component in table.
Maybe I do something wrong, but if I put my form in the table - all default styles aren't work correct
<img width="908" alt="Screenshot 2024-02-02 at 10 11 27" src="https://github.com/taiga-family/taiga-ui/assets/7202575/220dcb72-8201-473e-b6af-20fa6c0ae56e">
<img width="908" alt="Screenshot 2024-02-02 at 10 11 21" src="https://github.com/taiga-family/taiga-ui/assets/7202575/705492a4-d3d0-43c5-b31d-b1b0502ae0d9">
<img width="908" alt="Screenshot 2024-02-02 at 10 11 13" src="https://github.com/taiga-family/taiga-ui/assets/7202575/1193a1a8-35f6-4ade-b64d-af799f6d3e2a">

### Angular version

17

### Taiga UI version

3.63.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Addeo** [comment]
If I use the form outside the table - the styles are default, but inside the table my form is without border, label(the label is outside the visible area)

**Comment by waterplea** [comment]
Try adding tuiTextfieldAppearance="textfield" on your form. Table provides table appearance, and that's how Angular DI works — it spills into dialog. Don't forget TuiTextfieldControllerModule.

**Comment by Sergey111991KV** [comment]
Thanks! It's help!!
