### ISSUE TITLE
🐞 - TuiCheckboxBlock gets focused state after click and change tabs

### ISSUE THREAD

**Issue by k-tar-t** [taiga-family/taiga-ui#6719]
### Playground Link

https://taiga-ui.dev/components/checkbox-block

### Description

After check/uncheck value via click component doesn't show focused state, but gets focused border after switching browser tab and switching back.

After some investigation found that can be related with changes in tuiIsNativeFocused in this commit https://github.com/taiga-family/taiga-ui/commit/31a94838

### Angular version

14

### Taiga UI version

3.63+

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This will get fixed in 4.0 once we move to `:focus-visible` across the entire library.

**Comment by waterplea** [comment]
Fixed in 4.0, we will not fix this in v3.
