### ISSUE TITLE
🐞 - cannot control chevron rotation programatically in treeview component

### ISSUE THREAD

**Issue by martypitt** [taiga-family/taiga-ui#6834]
### Playground Link

https://taiga-ui.dev/components/tree

### Description

When using programmatic control to define which nodes are expanded, the chevron does not update.

In this video from the taiga website, notice that the chevron does not rotate when the node is expanded / collapsed programatically, but does rotate when toggled by clicking

![Peek 2024-02-20 04-59](https://github.com/taiga-family/taiga-ui/assets/348852/28494f38-e5cf-41ab-a7e5-67f3ea78decc)

### Angular version

16

### Taiga UI version

3.66.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Good catch
