### ISSUE TITLE
[FEATURE] Showcase bundled Angular Animations

### ISSUE THREAD

**Issue by waterplea** [taiga-family/taiga-ui#684]
# 🚀 Feature request

We have a list of animations in `@taiga-ui/core`:
https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/core/animations/animations.ts

They are helpful for projects using Taiga UI, we need to add a page on demo portal showcasing all those animations.

**Comment by AGundak** [comment]
@waterplea @MarsiBarsi Hi, Is it relevant?

**Comment by splincode** [comment]
https://taiga-ui.dev/animations
