### ISSUE TITLE
Tiles 🚀 - rerender tiles after change items array 

### ISSUE THREAD

**Issue by zavod008** [taiga-family/taiga-ui#6852]
### Description

Привет, спасибо за либу.
Неплохо было бы менять верстку, если меняешь w и h в массиве.
В данный момент приходится хакать через использование внутренних методов компонента.
Ну по крайней мере другого способа я не нашел.

**Comment by waterplea** [comment]
Привет. Спасибо! Не очень понял вопрос. Tiles — это по сути просто CSS grid с возможность драг энд дропа. W и H — просто особенности конкретного примера. Сможешь сделать стэкблиц для пояснения того, чего ты хочешь добиться?

**Comment by zavod008** [comment]
https://stackblitz.com/edit/angular-fzjpty?file=src%2Fapp%2Fapp.component.ts

чего то такого, щас чтобы ширина поменялась нужно мышкой туда навести, у меня в проекте оно работает но и как бы в гриде все становится нормально, но в t-wrappere высота и ширина в пикселях не меняются

**Comment by zavod008** [comment]
Что то типо такого 
![image](https://github.com/taiga-family/taiga-ui/assets/20419214/f01eaa07-ed24-4d02-83e8-71097f133e94)

**Comment by zavod008** [comment]
И если выбрать драг иконку то сервис все пересчитает и ширина станет нормальной

**Comment by zavod008** [comment]
Ладно отбой я убрал из примера онпуш и в редакторе, все работает нормально, пойду у себя в коде копаться(

**Comment by zavod008** [comment]
@waterplea я еще в дискуссию писал вопрос про виртуал скролл можешь глянуть?
