### ISSUE TITLE
🐞 - Artifact in experimental navigation component

### ISSUE THREAD

**Issue by yigsvnsla** [taiga-family/taiga-ui#6873]
---
### Description

Hello everyone, I am using the documentation of the experimental components, to be specific the navigation component and this in your example # 1 has a detail that is very noticeable to the user, it is simply a black line that is floating and that is not represented in any of the DOM components to be able to target it and perform a hot modification and that is also displayed in my local development environment

![image](https://github.com/taiga-family/taiga-ui/assets/55502763/79992dc8-3bad-4b5d-bf90-5717f7cfdcf3)

![image](https://github.com/taiga-family/taiga-ui/assets/55502763/1a5af1d2-eeb4-4654-9af7-77e489359035)
---

Playing for a while with the dom, its styles and reading the source code of the components, I found that this detail is shown because it has a "tui-scrollbar" component wrapping the content of the "aside" component, since it has a opacity effect to make the component next to the scrollbar visually attractive

[Aside Source Code](https://github.com/taiga-family/taiga-ui/blob/main/projects/experimental/components/navigation/aside.component.ts#L12)

![image](https://github.com/taiga-family/taiga-ui/assets/55502763/5e5653f4-ffe7-42ca-abcd-4605215b3945)
---
It's funny (not hate) that to have the content encapsulated within aside the footer component has a "margin-top:auto", without taking into consideration the visual characteristic of the "tui-scrollbar" component

![image](https://github.com/taiga-family/taiga-ui/assets/55502763/8e70b96a-adfb-4d2f-9b7c-6e7b8e198344)
---
A quick solution that can be done as a hot fix is for this component that surrounds the content scroll to take the entire height of the component, and thus be able to move the blur effect along with that visual artifact to the bottom in the case of not having more elements overloading the content of the aside and that in this case, if the content is made scrollable, the artifact may be less noticeable in the user's view.
![image](https://github.com/taiga-family/taiga-ui/assets/55502763/92f325b6-4974-4a85-b108-bfc8093e7953)

![image](https://github.com/taiga-family/taiga-ui/assets/55502763/43326720-cff7-41c6-ba3e-719ccc5e3cd2)
[Style sheet file the Aside Navigation Experimental Component](https://github.com/taiga-family/taiga-ui/blob/main/projects/experimental/components/navigation/aside.style.less#L72
)

### Angular version

^17.2.0

### Taiga UI version

^3.67.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Thank you for investigating it. Seems to be Chrome rendering bug. We'll see what can be done about it.
