### ISSUE TITLE
🐞 - tui-input-password does not display the view/hide password button

### ISSUE THREAD

**Issue by NickMih** [taiga-family/taiga-ui#6973]
### Playground Link

https://stackblitz.com/edit/angular-n6jrjp?file=src%2Fapp%2Fapp.component.html

### Description

Can you add [showButtons] directory in 3-th version? Because readOnly attribute can't work with dynamic form.

### Angular version

17

### Taiga UI version

3.69

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Disabled element is meant to be completely non-interactive. It is missing from the form, it is missing from accessibility tools, browsers typically ignore pointer events on it. I believe we should only show this icon for readonly controls as you can focus them, select and copy content etc.

**Comment by Debxit** [comment]
> Disabled element is meant to be completely non-interactive. It is missing from the form, it is missing from accessibility tools, browsers typically ignore pointer events on it. I believe we should only show this icon for readonly controls as you can focus them, select and copy content etc.

Hi, can you clarify what should be done? I want to try to contribute, but didn't get the final idea.

**Comment by waterplea** [comment]
@Debxit right now `InputPassword` does not display eye icon for `disabled` and `readOnly` state. It should display icons for `readOnly` and only hide icons for `disabled` state.
