### ISSUE TITLE
🚀 - Defining the style of the yes button in prompt

### ISSUE THREAD

**Issue by martypitt** [taiga-family/taiga-ui#6986]
### Description

We're using [prompt](https://taiga-ui.dev/components/prompt) to show confirmation dialogs.

However, sometimes the action is destructive, and we feel like the [secondary destructive or accent](https://taiga-ui.dev/components/button#appearance) styles would be more appropriate.

It'd be great to be able to configure this.  

Looking at the source for the [prompt.template.html](https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/components/prompt/prompt.template.html) it doesn't appear that this appearance is configurable.

**Comment by waterplea** [comment]
Hello there. Current workaround would be to replace `TUI_PROMPT` with an underlying component so we can override providers and change the default appearance of the button:
```ts
new PolymorpheusComponent(
  TuiPromptComponent,
  Injector.create({
    providers: [tuiButtonOptionsProvider({ appearance: 'destructive' })],
    parent: this.injector,
  })
),
```
Admittedly it's not as easy as passing the appearance but it would work for you right now.

**Comment by waterplea** [comment]
It will be added in 4.0 along with the component rename in PR above. Feel free to add PR for 3.x or use the workaround I gave.
