### ISSUE TITLE
🐞 - File input "drag over" stops working when zone.js `eventCoalescing` is enabled

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#7004]
### Description

- Enable zone.js `enventCoalescing`:
Standalone apps:
```ts
export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({
      eventCoalescing: true
    })
  ]
};
```
NgModule based apps:
```ts
platformBrowserDynamic()
  .bootstrapModule(AppModule, { ngZoneEventCoalescing: true })
  .catch(err => console.error(err));
```
- Try to drag files over Taiga file input.
- The file input style doesn't change

Angular folks say it's not an issue on their end: https://github.com/angular/angular/issues/54856
Can be reproduced on Chrome, but not on Firefox.

### Angular version

17.3.0

### Taiga UI version

3.70.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like we can be storing `dataTransfer.files` instead of the entire `DataTransfer` object. Should be an easy fix, would you like to contribute a PR? For both v3.x and main, file structure has changed a bit.

**Comment by hakimio** [comment]
Ok, I can try to fix this.

**Comment by hakimio** [comment]
`v4` seems uneffected by the bug: https://github.com/taiga-family/taiga-ui/blob/7d00e9e82ff1a7f91b60b2c2e8b674397d324748/projects/kit/components/files/input-files/input-files.component.ts#L48
I have opened a PR for `v3`: https://github.com/taiga-family/taiga-ui/pull/7031
