### ISSUE TITLE
Use of `ngProjectAs`

### ISSUE THREAD

**Issue by ronniebarker** [taiga-family/taiga-ui#7012]
There is `ngProjectAs` in a bunch of `ng-content` elements (like `TuiInputComponent`), but the [angular documentation](https://angular.io/guide/content-projection) only seems to cover that directive in `ng-container` (not `ng-content`). Is this a mistake or is there something else going on I can't see?

**Comment by splincode** [comment]
https://medium.com/ignite-ui/using-ng-content-ngprojectas-1664d7c1d3b
