### ISSUE TITLE
🐞 - Stepper: autoscroll to selected element not working after updating stepper state

### ISSUE THREAD

**Issue by n1k1t0ss** [taiga-family/taiga-ui#7017]
### Playground Link

https://stackblitz.com/edit/angular-fasgvr?file=src%2Fapp%2Fapp.component.html

### Description

https://github.com/taiga-family/taiga-ui/assets/1676900/7d41e751-b7fa-41fa-8792-da71f935cb0e

In the example it looks at steps$ observable, and the autoscroll works perfectly, both when switching the stepper itself and when navigating through pages. But as soon as I update the steps$ value (in my example it happens after buttons click), the autoscroll doesn't move anymore.

### Angular version

12.2

### Taiga UI version

3.70.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Found the issue. `getNativeElements` should not be memoized. In fact, it should just be removed, it is used in 2 places, one does not need the entire array and can be replaced with `this.steps.get(index)?.nativeElement` and another can be replaced with `toArray()`:
```ts
const stepElements = this.getNativeElements(this.steps);
const index = stepElements.findIndex(item => item === current);

// changed to
const index = this.steps.toArray().findIndex(item => item.nativeElement === current);
```
I'll leave this issue open for external contribution, a PR is welcome.
