### ISSUE TITLE
🐞 - incorrect tui-table-pagination with empty data

### ISSUE THREAD

**Issue by arukuskus999** [taiga-family/taiga-ui#7025]
### Playground Link

https://stackblitz.com/edit/angular-f6hcsv?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.less&hideExplorer=1

### Description

When table is empty we need to look pagination phrase "Lines per page 0 of 0".

But now is "Lines per page 1–0 of 0".

Also can we have to border under thead with phrase with image - no data? Table looks bad with only headers.
![image](https://github.com/taiga-family/taiga-ui/assets/161805803/ef705fd5-c866-4bbc-881b-e08bb8fb5c55)

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
As for your second question, you can just add
```html
<tr *ngIf="!data.length">
  <td tuiTd colspan="3" style="text-align: center">No data</td>
</tr>
```
Keep in mind not to use `tuiTr` — it is only needed for rearrangeable columns.
