### ISSUE TITLE
🐞 - The slide `index` changing randomly when you trying to flip through the slide by dragging

### ISSUE THREAD

**Issue by sapienc** [taiga-family/taiga-ui#7036]
### Playground Link

https://stackblitz.com/edit/angular-udfro8?file=src%2Fapp%2Fapp.component.html

### Description

When you try to flip a slide by dragging, you may notice that sometimes the slides flip randomly.

If you try to display the current `index` of the carousel, you will notice that this `index` acquires unexpected values, which leads the wrong slide flip.

Here you can see it in action:

https://github.com/taiga-family/taiga-ui/assets/55036936/4bbf23d6-20cd-40ab-a6de-d54848e96397

<hr/>

Also what i noticed is that it occurs in `Chrome` only, in `Firefox` & `Safari` it works very well

<hr/>

Reproducing the issue in `Firefox`:

https://github.com/taiga-family/taiga-ui/assets/55036936/cd1d47a9-175f-424f-888e-95d7026fa2d3

<hr/>

Reproducing the issue in `Safari`:

https://github.com/taiga-family/taiga-ui/assets/55036936/55e6faa2-5fbb-48a7-aafc-7e2ddf837666

### Angular version

16.2.12

### Taiga UI version

3.70.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by vladimirpotekhin** [comment]
Fixed in 3.x, needs to be fixed in main
