### ISSUE TITLE
🐞 -  `text-align` style doesn't work with `tui-notification`

### ISSUE THREAD

**Issue by costarev** [taiga-family/taiga-ui#7043]
### Description

I use `tui-notification` component with `text-align: center`, but it doesn't work after updating tui from 3.64 to 3.71

![image](https://github.com/taiga-family/taiga-ui/assets/42897227/88734a37-6c11-4c4c-831a-9263c6599097)

### Angular version

15.2.0

### Taiga UI version

3.71.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
https://github.com/taiga-family/taiga-ui/pull/7042
