### ISSUE TITLE
🚀 - cvc code should be hidden for InputCardGrouped

### ISSUE THREAD

**Issue by tinkoffspectrum** [taiga-family/taiga-ui#7052]
### Description

We need to add an option to hide cvc code input for the component.
Some clients request this feature

Thank you

**Comment by waterplea** [comment]
I suppose we can add a flag to hide value using this CSS rule:
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-security
It is now finally supported by Firefox.
