### ISSUE TITLE
🐞 - InputCopy returns incorrect copy hint

### ISSUE THREAD

**Issue by SeregaZnam** [taiga-family/taiga-ui#7073]
### Description

If you click on the copy button before the tooltip appears, the tooltip will show up after the click displaying the text "Copy", seemingly prompting the user to click it a second time.

https://github.com/taiga-family/taiga-ui/assets/18699867/7e75ba2a-ea62-4b38-b4bf-904db06a93ed

### Angular version

15.2.0

### Taiga UI version

3.71.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by vladimirpotekhin** [comment]
@chipaza will take it
