### ISSUE TITLE
🐞 - input-date-multi error after edit chips

### ISSUE THREAD

**Issue by AlexeyPortnyagin** [taiga-family/taiga-ui#7076]
### Playground Link

https://taiga-ui.dev/components/input-date-multi

### Description

After doubleclick in chips, the date selection is broken for the selected date

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I think it was not supposed to be editable in the first place. Let's disable editing functionality in 3.x at all since at the moment there's no way to pass mask to the edited tag. In 4.x we might add this support because it will be reworked completely. @splincode please disable doubleclick editing.

**Comment by splincode** [comment]
@waterplea what about https://github.com/taiga-family/taiga-ui/pull/7080

**Comment by waterplea** [comment]
> @waterplea what about https://github.com/taiga-family/taiga-ui/pull/7080

There's no masking on the tag. Could you try to add it with Maskito directly on the chip?
