### ISSUE TITLE
🐞 - Strange scrollbar width

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#7138]
### Playground Link

https://taiga-family.github.io/tui-editor/starter-kit

### Description

I don't have multiple tui-root

<img width="188" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/3f952e52-3a0f-419f-8a9c-1f7479ca60bd">

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
There are 2 `tui-root`:
![image](https://github.com/taiga-family/taiga-ui/assets/11832552/665509b5-8d60-4a2e-a4da-c7ff1da55417)
