### ISSUE TITLE
🐞 - Still active element in tiles

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#7157]
### Playground Link

https://taiga-ui.dev/next/components/tiles

### Description

Try reorder

<img width="344" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/745444d9-af85-4628-a8af-d15eb3eb9ac1">

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by mdlufy** [comment]
separately, the problem does not play in tiles, the problem when playing in demo affects [tui-tabs-with-more](https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/components/tabs/tabs-with-more.component.ts) which is inside `<tui-doc-example />`

https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/components/tabs/tabs-with-more.component.ts#L131-L133
it is called very often (with each movement of the cursor, for example, and with drag even more often)

resource-intensive access to [get activeElement](https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/components/tabs/tabs-with-more.component.ts#L275 ) blocks the end of animation event [transitionend](https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/components/tiles/tile.template.html#L4 ) -> the `_dragged` class is not being deleted

of the possible solutions: 
1) wrap refresh in requestAnimationFrame/setTimeout(, 0) 
2) refuse to call refresh in afterViewChecked (if possible)
3) make get activeElement more productive?
