### ISSUE TITLE
🐞 - ExpressionChangedAfterItHasBeenCheckedError occurs when navigating via the dropdown menu in `TuiTabsWithMore`

### ISSUE THREAD

**Issue by ShmatEugene** [taiga-family/taiga-ui#7181]
### Playground Link

https://stackblitz.com/edit/angular-t8ebht?file=src%2Fapp%2Fapp.component.html

### Description

When pages are switched using tabs, everything works fine. However, when switching via the dropdown menu in TuiTabsWithMore, `NG0100: ExpressionChangedAfterItHasBeenCheckedError` error occurs.
The error is present if `a` is used in the markup. However, if `button` is used instead, everything works correctly.
The error occurs within this template (https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/components/tabs/tabs-with-more.template.html#L63C17-L63C42), where the `shouldShow` method initially returns `false` and then `true`.

### Angular version

12.2.17

### Taiga UI version

3.73.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Not reproducible in v4 using the same code
