### ISSUE TITLE
📚 - Replace all hard-coded documentation relative links with `DemoRoute`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#7186]
### Description

1. Find all relative links
```html
<a
    routerLink="/relative-link/to/another/page"
    tuiLink
></a>
```
2. Replace hard-coded value with `DemoRoute`.

See example:
* https://github.com/taiga-family/taiga-ui/pull/7185

**Comment by PranavJayachandran** [comment]
Hey, can I take up this issue?
I am new to this, I can fork it and raise a PR from there right ?

**Comment by splincode** [comment]
@PranavJayachandran yes, of course
