### ISSUE TITLE
🐞 - browser address bar jumps on ComboBox value select

### ISSUE THREAD

**Issue by saburovser** [taiga-family/taiga-ui#7202]
### Playground Link

https://taiga-ui.dev/components/combo-box

### Description

When selecting value from ComboBox dropdown (Safari iOS), address bur twitches up and down

https://github.com/taiga-family/taiga-ui/assets/40900817/f50d9472-a333-419a-82cf-41dd96c6f65c

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by waterplea** [comment]
Should be fixed on latest version

**Comment by vladimirpotekhin** [comment]
#7193
