### ISSUE TITLE
🐞 - Dialog jumps when closing after scrolling

### ISSUE THREAD

**Issue by al-march** [taiga-family/taiga-ui#7219]
### Playground Link

https://taiga-ui.dev/components/dialog

### Description

The dialog scrolls up after attempting to close it. Presumably, this is related to the wrapper being assigned the CSS rule `overflow: clip`:

https://github.com/taiga-family/taiga-ui/assets/42899726/4433d3cd-06bb-4373-8f2b-924412d6d797

This can be fixed by removing line 38 in animations.ts, as it forces the browser to clip the content by height:

https://github.com/taiga-family/taiga-ui/assets/42899726/e942e1ef-8bef-4fe1-931b-35d124cab530

I can create a pull request with the fix, if this solution works for you.

### Angular version

16.2.12

### Taiga UI version

3.59.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
https://github.com/taiga-family/taiga-ui/pull/7220

**Comment by splincode** [comment]
@waterplea what do you think?

**Comment by waterplea** [comment]
I'll take a look. Clip was added exactly to address jumping because during animation scroll bar will appear and disappear otherwise.

**Comment by waterplea** [comment]
Apparently `clip` was used to prevent jumpy scroll on autofocus. I removed it from closing animation only, seems like it should be enough.
