### ISSUE TITLE
🐞 - Calendar not opening in InputDateRange when user-agent is switched to mobile

### ISSUE THREAD

**Issue by misha-ann** [taiga-family/taiga-ui#7227]
### Description

- In Chrome Devtools the device type is switched to mobile, screen resolution is set to 1360 x 677
- There's an InputDateRange component inside a hosted dropdown.
- After we open the dropdown and try to set the date range the dropdown closes, there's screen blinking - but no calendar.
TuiMobileCalendarDialogModule is imported, works well with smaller resolution.

https://github.com/taiga-family/taiga-ui/assets/167076330/01f52560-00bd-4403-913a-fd2fd66d148f

### Angular version

17.0.0

### Taiga UI version

3.70.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Fixed with https://github.com/taiga-family/taiga-ui/pull/7254
