### ISSUE TITLE
🚀 - TuiFiles should show a File Preview button or action

### ISSUE THREAD

**Issue by baijudodhia** [taiga-family/taiga-ui#7239]
### Description

Currently <tui-file> doesn't provide any way to preview the file once it is added via the <tui-input-file>.

Option should be provided to preview the added files.

**Comment by waterplea** [comment]
`tui-file` with `size="l"` already shows the preview of an image. You can also pass any content you want inside the file:
```html
<tui-file>
  <button>My action</button>
</tui-file>
```
Creating your own previews can be done with `URL.createObjectURL(file)` so you can later show it anywhere with `img` tag, for example, using `tui-preview` upon clicking "My action".

**Comment by splincode** [comment]
@waterplea could we add example in documentation about your approach?

**Comment by waterplea** [comment]
It would be a welcomed addition 👍 But at the moment I'm trying to direct all my efforts on pushing 4.0 closer to release.
