### ISSUE TITLE
🐞 - In mobile tui-hint has no center vertical align

### ISSUE THREAD

**Issue by o-korost** [taiga-family/taiga-ui#7259]
### Description

![Снимок экрана 2024-04-18 в 14 43 45](https://github.com/taiga-family/taiga-ui/assets/18615985/f921eec7-ce85-4e66-9e61-169fe054e356)

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like mobile fonts line height issue.
