### ISSUE TITLE
🐞 - Too strict peer dependency requirements in Taiga `v3`

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#7267]
### Description

After updating `@tinkoff/ng-event-plugins` in my app, I get the following warning:
```
@tinkoff/ng-event-plugins is listed by your project with version 3.2.0, which doesn't satisfy what @taiga-ui/core requests (3.1.1).
```

Taiga `v4` correctly accepts any `@tinkoff/ng-event-plugins` `v3` minor release:
https://github.com/taiga-family/taiga-ui/blob/dd48fac5b0929877250f22b13a67f3ddbb8c957b/projects/core/package.json#L31
while `v3` only accepts `v3.2.0`:
https://github.com/taiga-family/taiga-ui/blob/709acdcc9bbcdaca7fce7993dd6542c5724df4f5/projects/core/package.json#L31

Can the version range be widened in Taiga `v3`?

EDIT: same for `@ng-web-apis` peer dependency.

### Angular version

17.3.5

### Taiga UI version

3.75.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
sure, I will fix it

**Comment by waterplea** [comment]
It was increased because we added a new plugin and that new plugin is used in Taiga UI 3.x so previous version is no longer compatible.

**Comment by hakimio** [comment]
@waterplea `@tinkoff/ng-event-plugins` version bump is not an issue.
