### ISSUE TITLE
🐞 - Caret in InputPassoword works instable while clicking show/hide password button

### ISSUE THREAD

**Issue by viktorzdanovich** [taiga-family/taiga-ui#7281]
### Description

When starting randomly hitting "show" or "hide" buttons in InputPassword component, the caret can change its position to the beginning of the field though initially it was set to other place.

The behavior can be reproduced on https://taiga-ui.dev/.

See attachment
![Kapture 2024-04-22 at 11 42 01](https://github.com/taiga-family/taiga-ui/assets/19538300/24dc99f8-e9e3-44cb-a4f9-fc81821269cb)

### Angular version

17.1.0

### Taiga UI version

3.68.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by ankiitkumar07** [comment]
Hi @viktorzdanovich 
let me know if I can work on this.

**Comment by splincode** [comment]
@viktorzdanovich sure, go ahead

**Comment by viktorzdanovich** [comment]
@splincode  is there any updates on this issue?

**Comment by splincode** [comment]
@viktorzdanovich 
https://github.com/taiga-family/taiga-ui/pull/7343#pullrequestreview-2040889208
