### ISSUE TITLE
🐞 - [v3] `addon-commerce` still requires `maskito` `^1.9.0`

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#7340]
### Description

Maskito version requirement should be updated in `addon-commerce` v3:
https://github.com/taiga-family/taiga-ui/blob/3499731441325c164fc58423d2d36abc7dfec168/projects/addon-commerce/package.json#L21

### Angular version

17.3.6

### Taiga UI version

3.76.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
We cannot use Taiga@v3 and Maskito@v2. They are incompatible – Taiga@v3 is based on assumption that maskito has initial calibration (only Maskito@v1 has the such behavior).

Learn more:
* https://github.com/taiga-family/taiga-ui/pull/6663

Maskito's version will be bumped later in upcoming Taiga@v4.

**Comment by nsbarsukov** [comment]
Upcoming Taiga@v4
https://github.com/taiga-family/taiga-ui/blob/99ab5ab6c1b79b03d8b8a25e2e78cccb1d277e76/projects/addon-commerce/package.json#L20-L22
