### ISSUE TITLE
🐞 - TUI Editor | Mention. Ошибка: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite.

### ISSUE THREAD

**Issue by Qxfile** [taiga-family/taiga-ui#7377]
### Description

При вводе символа @ и выборе юзера из списка падает ошибка `Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite.`
![image](https://github.com/taiga-family/taiga-ui/assets/102025481/1f56ad7d-2bb4-4927-afef-ccf7d8085a16)

### Angular version

17.3.0

### Taiga UI version

1.25.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
`tui-editor` has its own repository: https://github.com/taiga-family/tui-editor

**Comment by splincode** [comment]
I can't reproduce on the last editor alpha version
