### ISSUE TITLE
🐞 - Scroll and zoom on preview

### ISSUE THREAD

**Issue by Deuteriy** [taiga-family/taiga-ui#7436]
### Description

Have some problems on https://taiga-ui.dev/components/preview
When you zoom, scrolling doesn't work. 
Zoom use transform, it does not stretch the container and simply crawls out of its frame

### Angular version

17.0

### Taiga UI version

3.77.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
We decided to close this as not planned. Preview component is not meant for scrollable content. If you need to preview PDF, perhaps PDFViewer is a more suitable UI component?
