### ISSUE TITLE
🐞 - Different styles between light and dark themes for radio-block groups

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#7452]
### Playground Link

https://taiga-ui.dev/components/radio-block#groups

### Description

Light

<img width="507" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/25c5942d-3f0c-46a7-a1c3-354e7c822d3f">

Dark

![image](https://github.com/taiga-family/taiga-ui/assets/12021443/6017ac27-fdb8-4438-be95-44d4898e5766)

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Closing this as it is no longer applicable to 4.0
