### ISSUE TITLE
🐞 - `TuiMultiSelectModule` does not export `TuiTextfieldDirective`

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#7461]
### Description

Unlike all the rest of Taiga input modules, `TuiMultiSelectModule` does not export `TuiTextfieldDirective`.
So, if you are using `ComboBox`, you can do the following:
```html
<tui-combo-box
    [formControl]="myControl"
>
    My Label
    <input
        autocomplete="new-password"
        tuiTextfield
    />
</tui-combo-box>
```

But the following will give you an error:
```html
<tui-multi-select
    [formControl]="myControl"
>
    My Label
    <input
        autocomplete="new-password"
        tuiTextfield
    />
</tui-multi-select>
```

### Angular version

17.3.8

### Taiga UI version

3.77.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Thanks for pointing it out. Would you be willing to make a PR into the v3 branch?

**Comment by hakimio** [comment]
I am quite busy right now, but might be able to take a look at this at the end of next week. If someone wants to take this before that, feel free to go ahead.

**Comment by hakimio** [comment]
Quickly took a look at this and it seems to me that for `multi-select` to accept `input[tuiTextfield]`, `input-tag` template needs some major changes which include replacing simple `input` with `primitive-textfield`.
If someone wants to take this, feel free to do it.

**Comment by waterplea** [comment]
I'm closing this as it would definitely be a part of specs for the refactored multi-inputs and it is not coming to legacy controls anyway.
