### ISSUE TITLE
tui-input-number with [step] directive doesn't work correct in table🐞 -

### ISSUE THREAD

**Issue by NickMih** [taiga-family/taiga-ui#7502]
### Playground Link

https://stackblitz.com/edit/angular-rxaoyh?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Description

step directive shows plus and minus buttons, but the icons are not responsive.

### Angular version

17.3

### Taiga UI version

3.61

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by vladimirpotekhin** [comment]
The error is no longer reproducible since at least version 3.79.0 (see stackblitz)
