### ISSUE TITLE
🐞 - TuiClickOutside directive unexpected behaviour

### ISSUE THREAD

**Issue by haoksam** [taiga-family/taiga-ui#7509]
### Playground Link

https://stackblitz.com/edit/angular-bn3yi1

### Description

tuiClickOutside is not working as expected if the component, in which it's used, is multiplied.

For example, I have a simple card component:

```
<div
  class="card"
  [class.active]="active"
  (click)="active = true"
  (tuiClickOutside)="active = false"
>{{ label }}</div>
```

There are 3 card components on the page. On click the card is set as active, on outer click it becomes inactive.

Each card is changing it's status as expected if I click on the card then somewhere else on the page.
Each card is changing it's status as expected if I click on each card from last to first.
But if I click on each card consecutively from first to last, each previously clicked card doesn't become inactive.
 
![ePG4marzeb](https://github.com/taiga-family/taiga-ui/assets/9367778/a9162347-ab2f-4ce9-8f95-06548ff07160)

### Angular version

14.2.2

### Taiga UI version

3.79.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
`tuiClickOutside` is undocumented for a reason :) It is specifically designed for a particular hack we needed internally. You should use `ActiveZone`:
https://taiga-ui.dev/directives/active-zone
