### ISSUE TITLE
🐞 - TuiError produce an error with PolymorpheusComponent

### ISSUE THREAD

**Issue by EricPoul** [taiga-family/taiga-ui#7525]
### Playground Link

https://stackblitz.com/edit/angular-mwny1a?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts&hideExplorer=1

### Description

When I provide the `TUI_VALIDATION_ERRORS` object with `PolymorpheusComponent` as a value in it an error occurs `Error: Cannot create a proxy with a non-object as target or handler`. It's because `required` error has `true` value [here](https://github.com/taiga-family/taiga-ui/blob/v3.x/projects/kit/pipes/field-error/field-error-pipe.ts#L85). Also, I haven't seen any examples with components on the [Taiga.ui](https://taiga-ui.dev/) and this issue hadn't been faced with before but since `TUI_VALIDATION_ERRORS` allows `PolymorpheusContent` I'm expecting it works properly with `PolymorpheusComponent`.

### Angular version

12.2.17

### Taiga UI version

3.79.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like the only way to fix it would be to wrap primitive values into objects, but that would be breaking change 🤔

**Comment by EricPoul** [comment]
It can be wrapped only for components and templates but if it didn't work before could it be considered as a breaking change?😄

**Comment by waterplea** [comment]
If we manage to do it only for components and templates — it won't be breaking :)

**Comment by waterplea** [comment]
It would work but you won't be able to get value of the error since templates can only access keys of the context object:
```html
<ng-template #tmp let-value="key">{{ value }}</ng-template>
```

**Comment by EricPoul** [comment]
Yep, so the goal is to try to wrap a primitive with the object for templates and components. It shouldn't be a breaking change for templates since it didn't work properly before(did work only if you hadn't reached a context). Is it a priority bug for you or should I consider making a PR?

**Comment by waterplea** [comment]
We are currently working very hard to finish 4.0 so this won't be on our radar for a while. You can think on the fix in the meantime. I wonder if it's better to fix it in polymorpheus so it works everywhere. Current `main` in polymorpheus is the upcoming major release, fyi.

**Comment by hakimio** [comment]
Why not just use [@ngneat/error-tailor](https://github.com/ngneat/error-tailor/) and avoid the `tui-error` boilerplate altogether?

**Comment by waterplea** [comment]
Moving it to ng-polymorpheus: https://github.com/taiga-family/ng-polymorpheus/issues/449
