### ISSUE TITLE
🐞 - Cannot select text in nested hint

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#7579]
### Playground Link

https://taiga-ui.dev/directives/hint#nested

### Description

![image](https://github.com/taiga-family/taiga-ui/assets/12021443/4200af92-78c2-4f71-ad82-3ab3aeed3fe8)

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by keshavlingala** [comment]
When a mouse click or selection occurs, the hint disappears and prevents the user from copying it. Is that the issue?

**Comment by splincode** [comment]
@keshavlingala yes
