### ISSUE TITLE
🐞 - Incorrect tui-input-date-time value after several clicks 

### ISSUE THREAD

**Issue by ZhukAnna** [taiga-family/taiga-ui#7584]
### Playground Link

https://stackblitz.com/edit/angular-eqzw9r-nbmcuf?file=src%2Fapp%2Fapp.component.ts

### Description

[Screencast from 31.05.2024 10:45:57.webm](https://github.com/taiga-family/taiga-ui/assets/7803506/030da86a-d7ab-4def-b610-f3658e1c4194)
Date becomes incorrect with several clicks on the input. Occurs if the [max] value is specified as [TuiDay, TuiTime]

### Angular version

17.0.8

### Taiga UI version

3.60.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
Duplicates:
* https://github.com/taiga-family/taiga-ui/issues/7586
