### ISSUE TITLE
🚀 - `TuiDialogService.open()` should be properly typed

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#7617]
### Description

Try to supply some `data` to `dialog.open()` method.
```ts
this.dialogService
    .open<MyOutputType>(new PolymorpheusComponent(MyComponent), {
        label: 'Star wars. Episode III',
        size: 's',
        // "data" here has type "any"
        data: {button: 'Do it!'},
    })
    // "result" here has proper typing
    .subscribe(result => this.myService.process(result));
```
Notice how dialog `data` is typed as `any` and there is no obvious way to set correct type.
The only way to fix the data type is to use the following ugly workaround:
```ts
private dialogService: AbstractTuiDialogService<TuiDialogOptions<MyDataType>> = inject(TuiDialogService);
```

The `open()` method should accept a second generic to properly type dialog data.

### Angular version

17.3.10

### Taiga UI version

3.81.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Link: https://github.com/taiga-family/taiga-ui/pull/6115/files

**Comment by hakimio** [comment]
@waterplea why did you close the PR?

**Comment by hakimio** [comment]
@splincode the mentioned PR doesn't fix the issue. We need second generic on the `open()` method, not a way to pass any Angular component to `open()`. I am fine with just passing `PolymorpheusComponent`.

**Comment by waterplea** [comment]
For now you can type options as a const:
```ts
const options: TuiDialogOptions<{ button: string }> = {
  label: 'Star wars. Episode III',
  size: 's',
  data: {button: 'Do it!'},
}

this.dialogService
    .open<MyOutputType>(new PolymorpheusComponent(MyComponent), options)
    .subscribe(result => this.myService.process(result));
```
In theory we wanted to extract data type from content, because it has typed context, at least in case of templates and functions, but so far I haven't been able to figure that out fast enough and backlogged it.

**Comment by hakimio** [comment]
`Context` also has `output` type. Why should `input` type be treated differently than `output`. The generic on the abstract class is totally useless from consumer's point of view. Both `context` and `open()` should have their own generics.
Right now typing dialog context looks sth like this:
```ts
protected context = inject(POLYMORPHEUS_CONTEXT) as TuiDialogContext<MyOutputType, MyInputType>;
```
I don't see where the generic on the class is useful in this case.

**Comment by hakimio** [comment]
Your workaround doesn't seem to work:

![TS error](https://github.com/taiga-family/taiga-ui/assets/768105/3c58e751-4576-47c3-9153-2acdfd8a98a9)

**Comment by waterplea** [comment]
Sorry, my mistake. `Partial<TuiDialogOptions<...>>`

**Comment by hakimio** [comment]
`Partial<TuiDialogOptions<MyDataType>>` is almost as long as `AbstractTuiDialogService<TuiDialogOptions<MyDataType>>` and not that much better workaround.
`open()` definitely needs a second generic and, honestly, I don't see how that can break anything.

**Comment by splincode** [comment]
@hakimio do you mean about second generic like that https://github.com/taiga-family/taiga-ui/pull/6175/files ?

**Comment by hakimio** [comment]
Almost, just instead of `this.dialogs.open<TuiDayRange, TuiDialogOptions<TuiMobileCalendarData>>`, I would like to simply use `this.dialogs.open<TuiDayRange, TuiMobileCalendarData>`. Basically, I don't think `TuiDialogOptions` should be mandatory.

**Comment by hakimio** [comment]
Maybe `DialogService` could override the `open()` method from the abstract class to set different generics.

**Comment by splincode** [comment]
@hakimio what do you think?
https://github.com/taiga-family/taiga-ui/pull/7621

**Comment by hakimio** [comment]
Not a fan, to be honest. 
- You still have to declare dialogs like `dialogs = inject(TuiDialogService<TuiDialogOptions<TuiMobileCalendarData>>)`
- It looks like it would break `MobileDialogService.open()` typings and it doesn't fix `MobileDialogService` `data` property type which is still `any`.

Ideally, `DialogService` class generic could look like this:
```ts
export class TuiDialogService<T = any> extends TuiPopoverService<TuiDialogOptions<T>> {}
```

And `DialogService` should override it's `open()` method. Sth like this:
```ts
// "T" generic here comes from the class definition
public override open<G = void, V extends T = T>(
        content: PolymorpheusContent<T & TuiPopoverContext<K extends void ? G : K>>,
        options: Partial<TuiDialogOptions<V>> = {},
    )
```
Sth similar could be done for `MobileDialogService` where `open()` is already overriden.
I don't think you should change the `open()` method in the base `PopoverService`.

**Comment by splincode** [comment]
@hakimio I think, you can make contribution PR

**Comment by hakimio** [comment]
Only if @waterplea is willing to accept the changes I mentioned.

**Comment by waterplea** [comment]
At the moment I'm focusing on 4.0 and unable to properly assess the suggestion. From the brief look, generic in class definition makes no sense since this generic is relative to `open` method only and a particular content you pass to it, that expects particular data type. That's why ideally it would be inferred from the content passed. I'll get back to it when we finish first release candidate. In the meantime you can define a type if you dislike long workaround:
```ts
export interface WithData<T> extends Partial<TuiDialogOptions<T>> {}
```
And define options as const like I suggested earlier.

**Comment by waterplea** [comment]
You can now use new `tuiDialog` factory and a component with public context property to enable strong typing:
https://taiga-ui.dev/components/dialog#data

**Comment by hakimio** [comment]
It only remains an issue if you don't want to define your dialog as a property of the component and instead instantiate it in a method. Or if you don't control the dialog component and can't define the context there or you don't want to make the context public.

**Comment by waterplea** [comment]
You can use [runInInjectionContext](https://angular.dev/api/core/runInInjectionContext) if you don't want to define it as a property. As for public context – that will remain a limitation for now, I believe this is good enough for this feature at the moment and we can focus on other things. Perhaps in v5 we will rework our dialogs a bit.
