### ISSUE TITLE
🐞 -  tinkoff_ng_dompurify_createDOMPurify is not a function on Angular 17 SSR

### ISSUE THREAD

**Issue by hduy1201** [taiga-family/taiga-ui#7704]
### Description

The application fails to run in the server-side rendering (SSR) environment on Angular 17. The error message encountered is:
tinkoff_ng_dompurify_createDOMPurify is not a function

### Angular version

17.3.7

### Taiga UI version

3.61.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Are you using latest versions of `dompurify`, `@tinkoff/ng-dompurify` and `@types/dompurify`?

**Comment by hduy1201** [comment]
Oh thanks, I have solved it. 

But i have another problem: "ERROR ReferenceError: MutationObserver is not defined". 
It is a sub-library of @ng-web-apis, do you know how to solve it ? Thanks

**Comment by waterplea** [comment]
Add `@ng-web-apis/universal` package and following line to your server side main file:
```ts
import '@ng-web-apis/universal/mocks';
```

**Comment by hduy1201** [comment]
Thanks for your help!

But my app still not response and there are no error on console log or on server. It just loading and loading...

**Comment by waterplea** [comment]
If there is no error it might be some kind of never completed observable stream that is stuck
