### ISSUE TITLE
🐞 - tuiAccordionItemContent SSR issue during hydration

### ISSUE THREAD

**Issue by KhaledGabr** [taiga-family/taiga-ui#7733]
### Description

![image](https://github.com/taiga-family/taiga-ui/assets/17038667/f0b8156f-4785-4cc2-acea-7912b663ddc8)

As you notice in the picture, the accordion item content gets repeated twice. (It's created once in the server, and once in the browser, and thus fails to reconcile during hydration). 

```html
  @for (item of value().questions; track $index) {
    <tui-accordion [rounded]="false">
      <tui-accordion-item [borders]="null" [open]="true">
        <p class="tui-text_h4 question">
          {{ item.question }}
        </p>
        <ng-template tuiAccordionItemContent>
          <p class="tui-text_body-m answer">
            {{ item.answer }}
          </p>
        </ng-template>
      </tui-accordion-item>
    </tui-accordion>
  }

``` 

### Angular version

18.0.3

### Taiga UI version

3.83.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
I can't reproduce on https://taiga-family.github.io/preview-landing-components/
