### ISSUE TITLE
🐞 - `Textarea` does not display emoji in `Safari`

### ISSUE THREAD

**Issue by datebackk** [taiga-family/taiga-ui#7786]
### Description

`Textarea` does not display emoji in `Safari`. I tried to change the `font-size` from `inherit` to a specific value for textarea and the emojis started to display.

Safari version:  17.5 (19618.2.12.11.6)

| Chrome | Safari |
|--------|--------|
| <img width="1200" alt="Chrome" src="https://github.com/taiga-family/taiga-ui/assets/26503585/8ca358ef-f112-40ca-905b-841aab61c6f6"> | <img width="1200" alt="Safari" src="https://github.com/taiga-family/taiga-ui/assets/26503585/35cecd8e-1296-4472-8a8d-38fbaa26c14a"> | 

### Angular version

12.2.17

### Taiga UI version

3.83.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
I can't reproduce

<img width="610" alt="image" src="https://github.com/taiga-family/taiga-ui/assets/12021443/0a387bcb-7964-433f-b691-620402dad1d1">

**Comment by anarchyologist** [comment]
@waterplea I have the same issue on some iphone models still. (like iPhone 15 (not max) ) on my project. I cant test it somehow to fix it. 
Taiga version is 4.54,  Angular 20+

**Comment by waterplea** [comment]
@anarchyologist please make a stackblitz with reproduction using non-legacy Textarea and tell us the model/ios version with which to see it.
