### ISSUE TITLE
🐞 - `ItemsWithMore` is not compatible with items with `pointer-events: all`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#7793]
### Playground Link

https://stackblitz.com/edit/items-with-more-with-removable-tags?file=src%2Fapp%2Fapp.component.ts

### Description

```ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
      <tui-root>
          <tui-items-with-more>
              <ng-container *ngFor="let tag of tags">
                  <tui-tag
                      *tuiItem
                      status="primary"
                      [removable]="true"
                      [value]="tag"
                      (edited)="log(tag)"
                  ></tui-tag>
              </ng-container>
              <ng-template
                  let-index
                  tuiMore
              >
                  ...
              </ng-template>
          </tui-items-with-more>
      </tui-root>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  tags = new Array(10).fill(null).map((_, i) => `_____${i}_____`);

  log(smth: any) {
    console.log(smth);
  }
}
```

Try to click cross sign on the first element:

https://github.com/taiga-family/taiga-ui/assets/35179038/02dc8fc5-1843-4b52-b3e9-c2c5f30ec09c

## Temporary workaround
```less
::ng-deep .t-item_hidden tui-svg {
    pointer-events: auto !important;
}
```

### Angular version

12

### Taiga UI version

3.83.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Since tui-svg is getting deprecated and there's a workaround, I'm closing this as not planned.
