### ISSUE TITLE
🚀 - create TUI_TIME_VALUE_TRANSFORMER for tui-input-time component

### ISSUE THREAD

**Issue by al-march** [taiga-family/taiga-ui#7914]
### Description

I am encountering issues integrating tui-input-time component due to the absence of a token for handling data types. 

I seek the ability to change data types for input and output, similar to what is available in tui-input-date-time. Implementing this feature would greatly improve component flexibility and integration efficiency.

**Comment by waterplea** [comment]
Sounds reasonable. There are already good examples on how to do it, so I'll mark this issue for community contributions, PRs are welcome.

**Comment by reverie3** [comment]
I'd like to submit a PR for this.
