### ISSUE TITLE
🐞 - v.4.0.0-rc.2 Input Phone international error

### ISSUE THREAD

**Issue by KhaledGabr** [taiga-family/taiga-ui#7954]
### Description

![image](https://github.com/taiga-family/taiga-ui/assets/17038667/3839c66c-f51a-4379-8807-4ca6479b28c3)

The error causes the input field not to render.

### Angular version

18.0.4

### Taiga UI version

4.0.0-rc.2

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I wonder if it's because we have this:
```ts
export class TuiSelect extends TuiTextfieldDirective {
```
and `TuiTextfieldDirective` already has `hostDirectives: [TuiNativeValidator, TuiAppearance],`. Strange that it didn't cause issues with Angular 16 in our demo.

**Comment by waterplea** [comment]
This looks like a regression bug with Angular from 16 to 17, which is super bad. We'll see what can be done about it.
16:
https://stackblitz.com/edit/stackblitz-starters-bwkp4z
17:
https://stackblitz.com/edit/stackblitz-starters-q3mj5v
