### ISSUE TITLE
🐞 - TuiDay не корректно парсит дату

### ISSUE THREAD

**Issue by evoytenkoapps** [taiga-family/taiga-ui#7964]
### Description

при дате '2024-1-20'; месяц уходит в дату
при '2024-01-20';  все норм
мне кажется что если есть тире, то это однозначный разделитель дат.
 ```
  it('Должен конвертировать в дату тайги, через тире', () => {
    const data = '2024-1-20';
    const convertedData = {day: 20, month: 0, year: 2024} as TuiDay;

    expect(service.formatTuiDay(data, 'YMD')).toEqual(convertedData);
  });
  ```
  ```
// сам метод
    formatTuiDay(date: string, dateMode?: TuiDateMode): TuiDay {
    return TuiDay.normalizeParse(date, dateMode);
  }
```
<img width="859" alt="Снимок экрана 2024-06-27 в 12 31 48" src="https://github.com/taiga-family/taiga-ui/assets/26488952/6d6cddb5-af18-4bc1-a788-e54e2fad3cde">

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
When you are using `YMD` format, it expects 2 digit day and month: `yyyy-mm-dd`. 
Your `2024-1-20` date doesn't match the format. It should be `2024-01-20` instead.

**Comment by waterplea** [comment]
hakimio is right, you should also see `[parseRawDateString]: wrong date string length` assertion error in console. You are welcome to create a PR if you want to support this format, but currently it is working as planned. As a workaround `TuiDay.fromLocalNativeDate(new Date('2024-1-20')` seems to work.
