### ISSUE TITLE
🐞 - 4.0.0-rc2 - Error when using TUI_NUMBER_FORMAT

### ISSUE THREAD

**Issue by KhaledGabr** [taiga-family/taiga-ui#7975]
### Description

![image](https://github.com/taiga-family/taiga-ui/assets/17038667/0112aa17-4a66-4e08-bbf0-1172cd0cfa13)

```
export class TuiNumberFormat extends Observable<TuiNumberFormatSettings> {
    private readonly settings = new ReplaySubject<Partial<TuiNumberFormatSettings>>(1);
    private readonly parent = inject(TUI_NUMBER_FORMAT, {skipSelf: true});

    constructor() {
        super(subscriber =>
            combineLatest([this.parent, this.settings])
                .pipe(map(([parent, settings]) => ({...parent, ...settings})))
                .subscribe(subscriber),
        );
    }
```

It appears that the error has to do with something there: number-format.directive.ts
The error only happens when I provide the token in my app.component.ts

```
    {
      provide: TUI_NUMBER_FORMAT,
      useValue: { decimalSeparator: '.', thousandSeparator: ',' },
    },
```

### Angular version

18.0.4

### Taiga UI version

4.0.0-rc.2

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That token was changed to `Observable<TuiNumberFormatSettings>` so it can support dynamic i18n. Change your provision to `of({ decimalSeparator: '.', thousandSeparator: ',' })`. I'll add it to the list of migrations so we can cover this case if possible.
