### ISSUE TITLE
@taiga-ui/i18n🐞 - you have published alpha version on npm as @latest

### ISSUE THREAD

**Issue by hheexx** [taiga-family/taiga-ui#8015]
### Description

everything is in the title

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hheexx** [comment]
https://www.npmjs.com/package/@taiga-ui/i18n?activeTab=versions

**Comment by waterplea** [comment]
Seems to be resolved now
