### ISSUE TITLE
🐞 - tui-select broken with SSR

### ISSUE THREAD

**Issue by hheexx** [taiga-family/taiga-ui#8018]
### Description

I am trying to enable SSR for my website.

I have to apply ngSkipHydration to all <tui-select>s. If not i get the error:

NG0502: During serialization, Angular was unable to find an element in the DOM:

  …
  #node(projection)
    <-- AT THIS LOCATION
  …

To fix this problem:
  * check corresponding component for hydration-related issues
  * check to see if your template has valid HTML structure
  * or skip hydration by adding the `ngSkipHydration` attribute to its host node in a template

 Find more at https://angular.dev/errors/NG0502

at nodeNotFoundError
    at calcPathForNode
    at appendSerializedNodePath 
    at conditionallyAnnotateNodePath
    at serializeLView 
    at annotateHostElementForHydration 
    at serializeLView 
    at annotateHostElementForHydration 
    at serializeLView 
    at annotateHostElementForHydration 

Is this something that is known?
I may try to provide reproduction if it is needed.

### Angular version

18.0.4

### Taiga UI version

3.66.0

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hheexx** [comment]
I've also tried with latest 3.x taiga, does not help.

**Comment by splincode** [comment]
@hheexx please add reproduction on github
