### ISSUE TITLE
🐞 - SheetDialog on some device displays additional line

### ISSUE THREAD

**Issue by em-sargsyan** [taiga-family/taiga-ui#8058]
### Playground Link

https://taiga-ui.tcsbank.ru/components/sheet-dialog#basic

### Description

When opening the SheetDialog on the page https://taiga-ui.tcsbank.ru/components/sheet-dialog#basic, the behavior differs between devices. Fo example on an iPhone 14 Pro Max, the SheetDialog opens correctly without any issues. However, on a Blackberry PlayBook, an additional line appears at the top of the dialog, which is not present on the iPhone 14 Pro Max. This discrepancy affects the visual consistency of the component across different devices.

### Angular version

17.3.9

### Taiga UI version

3.84.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by em-sargsyan** [comment]
<img width="581" alt="Screenshot 2024-07-04 at 4 09 40 PM" src="https://github.com/taiga-family/taiga-ui/assets/150824602/0c2feb9e-4d79-42ec-a782-51b0779aa5a4">
![Uploading Screenshot 2024-07-04 at 4.10.19 PM.png…]()

**Comment by em-sargsyan** [comment]
<img width="581" alt="Screenshot 2024-07-04 at 4 09 40 PM" src="https://github.com/taiga-family/taiga-ui/assets/150824602/4d37a4d5-c068-4d37-9f72-696c12d196ff">
<img width="656" alt="Screenshot 2024-07-04 at 4 10 19 PM" src="https://github.com/taiga-family/taiga-ui/assets/150824602/2a7e6c1d-47dd-40bc-a1a6-89b7e17c59fd">

**Comment by vladimirpotekhin** [comment]
The reason is the uneven scale in the chrome emulator. It is recommended to always set the scale to a multiple of 5 (70, 75, 80, 90 e tc) to avoid glitches
