### ISSUE TITLE
🐞 - 4.0.0-rc.4 - TuiInputNumberModule Stepper doesn't work 

### ISSUE THREAD

**Issue by KhaledGabr** [taiga-family/taiga-ui#8066]
### Description
![image](https://github.com/taiga-family/taiga-ui/assets/17038667/c26302a6-8065-426a-8cf2-6fee3cc74e44)

example repo: 
https://github.com/KhaledGabr/ssr-test/tree/main/src/test/number

UPDATE:
Removed unrelated console log error from the post.

### Angular version

18

### Taiga UI version

 4.0.0-rc.4 

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I'm confused as to where this code comes from and why is it relevant to input number when it says `.tui-image-editor-download-btn` 🤔

**Comment by waterplea** [comment]
@KhaledGabr You imported `NG_EVENT_PLUGINS` but didn't add them to app config. It should get added by migration script/ng add, probably an issue with RC not ready yet with all the scripts. How did you create this app, what scripts did you run?
