### ISSUE TITLE
🐞 - region select in InputPhoneInternational size S is displayed wrong

### ISSUE THREAD

**Issue by mcdarkkillerganjubass** [taiga-family/taiga-ui#8124]
### Description

region select in InputPhoneInternational size S is displayed wrong. The arrow disappears and the flag goes beyond the edge of the field
<img width="344" alt="Screenshot 2024-07-17 at 10 41 48" src="https://github.com/user-attachments/assets/07d30407-64b3-451e-8b7f-7ad175427823">

### Taiga UI version

3.87

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Fixed in v4, PRs into v3.x are welcome
