### ISSUE TITLE
🐞 - tui-input-time  sets the correct value but doesn't  Preselect Current value from the dropdown 

### ISSUE THREAD

**Issue by dhawaldenny** [taiga-family/taiga-ui#8198]
### Playground Link

https://stackblitz.com/edit/angular-vj227c-wexvym?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts

### Description

For the Combobox, it preselects values from the dropdown, but it doesn't preselect values from the input time. If a minor change in time is needed, you have to scroll again to the selected value.

![image](https://github.com/user-attachments/assets/844c5ffb-b947-4dfe-9c1d-36786808eb15)

![image](https://github.com/user-attachments/assets/2281fed9-3286-4ea8-83d5-bbe836d69a38)

![image](https://github.com/user-attachments/assets/5534d11e-81fe-42a0-9df5-87194e0eed19)

In the attached stackblitz demo, the Combobox is working fine, but there are issues with the input time.

### Angular version

16.1.4

### Taiga UI version

3.76.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by ShawnDvn** [comment]
Hi,

I am experiencing the same issue with `tui-input-time` not preselecting the current value from the dropdown. 

**Observed Behavior**: The dropdown does not preselect the value from the input time, requiring users to manually scroll to the correct time.

![image](https://github.com/user-attachments/assets/a03f3228-563e-420c-88c9-017bdc237d50)

In this case, the user needs to scroll down from 00:00 to the current value 09:00. It should allow the user to make minor time adjustments such as changing from 09:00 to 08:00 or 10:00.

08:00  
09:00 <= preselected value  
10:00
