### ISSUE TITLE
🐞 - Click on one checkbox makes checked another one

### ISSUE THREAD

**Issue by YuliaTsareva** [taiga-family/taiga-ui#8200]
### Playground Link

https://stackblitz.com/edit/angular-zalema

### Description

Please, check my stackblitz and follow these steps:

1. Click "Next" to switch to second question.
2. Select either second or third checkbox.

When you select second checkbox, third is selected and vice versa.
This issue appears when the form is recreated and new options have same values.

Looks similar to this old issue: https://github.com/taiga-family/taiga-ui/issues/3985

### Angular version

17.3.5

### Taiga UI version

3.84.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
I can't reproduce in last v3.93

https://github.com/taiga-family/taiga-ui/pull/8922

**Comment by splincode** [comment]
@YuliaTsareva https://angular-zalema-x23nud.stackblitz.io use trackBy

**Comment by waterplea** [comment]
Also in 4.x we do not do anything with checkboxes/radiobuttons on our side, only style them, so that shouldn't be an issue unless it's an issue with Angular built-in CVA
