### ISSUE TITLE
🐞 - `InputDateRange` + `[minLength]` / `[maxLength]` has bad support for `MobileCalendar`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#8255]
### Playground Link

https://taiga-ui.dev/components/input-date-range/API?maxLength$=0&minLength$=0

### Description

Open https://taiga-ui.dev/components/input-date-range/API?maxLength$=0 (`[maxLength]={day: 5}`)

**Desktop:**
<img width="780" alt="desktop" src="https://github.com/user-attachments/assets/169a98c3-6c40-4624-b08f-e885805f55e3">

**Mobile:**

https://github.com/user-attachments/assets/8ff5dfac-bdc9-49f3-85f4-ca42cfde9a25

### Angular version

12

### Taiga UI version

3.x.x

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by LarisaGl** [comment]
Hi! I`ll take it
