### ISSUE TITLE
🐞 - Pasting comma-separated values ​​into `MultiSelect` will delete all values

### ISSUE THREAD

**Issue by Nastasiassss** [taiga-family/taiga-ui#8290]
### Playground Link

https://taiga-ui.dev/components/multi-select#ids

### Description

1. Open https://taiga-ui.dev/components/multi-select#ids
2. Insert into the value field: `Yoda, Obi-Wan Kenobi, Han Solo`

**Actual behavior**
Only the following is inserted into the field: `Han Solo`

https://github.com/user-attachments/assets/98c9b67e-1d38-4bce-8884-78c56b150624

### Angular version

17.3.8

### Taiga UI version

3.85.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Also when writing and typing `,` it would clear the value if the entered string did not match any available value.

**Comment by waterplea** [comment]
We should match all coma separated values to possible values. And if they do not match - keep input value as is.

**Comment by spanevin** [comment]
It looks like it uses InputTag or another similar component internally, InputTag has [separator] property, which has ',' as the default value.
So, it is possible to disable separator completely, or change it to another value.
If it's needed to keep this behavior in MultiSelect, then the separator property should be promoted to MultiSelect API and described in docs, I believe.
