### ISSUE TITLE
🐞 - TUI_PULL_TO_REFRESH_LOADED token dose not work when is used in onPull event synchronously

### ISSUE THREAD

**Issue by avrim-tr** [taiga-family/taiga-ui#8327]
### Playground Link

https://stackblitz.com/edit/angular-vzk6s6?file=src%2Fapp%2Fapp.component.ts

### Description

In "tui-pull-to-refresh" component, when user triggers the "pull to refresh", then an indicator is shown.
According to the doc, in order to remove it, simply inject TUI_PULL_TO_REFRESH_LOADED and use "next" method.
The thing here is that if you use it right away synchronously in the "onPull" event, it dose not work, the loading indicator stays.
Using asynchronously solves this (like setTimeout).

This is a breaking change, as in version of taiga 3.5.0 this whole issue did not happen. 

### Angular version

16.2.12

### Taiga UI version

3.80.0 and also latest one.

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nezar-khamidekh** [comment]
I'll take it
