### ISSUE TITLE
🚀 - Support `HostedDropdown` inside "more" section of `TabsWithMore`

### ISSUE THREAD

**Issue by m-aditya** [taiga-family/taiga-ui#837]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Description

Given a `tui-tabs-with-more` containing many `tui-hosted-dropdown`. If the width of the container causes an overflow into the more section, the dropdowns will cease to work.

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by m-aditya** [comment]
Is there some sort of workaround to get this to work?

**Comment by waterplea** [comment]
> Is there some sort of workaround to get this to work?

I didn't get to it yet, sorry. We tend to keep dropdowns to the left of the tabs so they never get into "More" if we even have a case like that in our designs... I will try to look into it in late January.

**Comment by m-aditya** [comment]
Alright, thanks!

**Comment by m-aditya** [comment]
Hi, will you be able to push this in the next release?
