### ISSUE TITLE
🐞 - `InputTime` has redundant assert log (dev mode only) if `maxValues` has non-default values

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#8372]
### Playground Link

https://taiga-ui.dev/components/input-time#options-max

### Description

1. Run development mode of our demo application
2. Open this example locally https://taiga-ui.dev/components/input-time#options-max
3. Enter `33:33`

See devtool console:
```
Assertion failed: Time must be real, but got: 33 33 0 0
```

**Expected behavior:**
Disable this check 
https://github.com/taiga-family/taiga-ui/blob/0d0b40647bc21806bc7927d17ff97dd0085df0d6/projects/cdk/date-time/time.ts#L47
if (or other similar cases)
```ts
tuiInputTimeOptionsProvider({
    mode: 'HH:MM',
    maxValues: {HH: 47, MM: 59, SS: 59, MS: 999},
})
```
(or make it more flexible)

### Angular version

16

### Taiga UI version

4.0.0-rc.8

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Chiorufarewerin** [comment]
I will try it

**Comment by Chiorufarewerin** [comment]
Why do you think that log is redundant? And i'm kinda interested why the `InputTime` has this ability for passing time with hours more that 23 at the first place.

I wonder if we change this behavior (passing time more than 23 hours) it will introduce breaking changes in the `TuiTime` for methods like `isValidTime`, `fromAbsoluteMilliseconds`, `shift`. We could make it flexible if we introduce another parameter `maxHours/unlimitedHours` or kind of like that but it will be looking awful.
I think the current `TuiTime` works as expected.

I think the correct way to introduce the new `TuiTimeDelta` (similar to python [datetime.timedelta](https://docs.python.org/3/library/datetime.html#timedelta-objects)) or `TuiTimeDistance`, and return it from `InputTimeComponent`.
For example: we introduce `returnValue` in the `TuiInputTimeOptions` , that will be accepting `TuiTime` (default) or `TuiTimeDistance` (for hours greater than 23 will be throwing an error in component that acception only `TuiTimeDistance`).

And why `InputTime` is in the legacy section and all `TUI_TIME_OPTIONS` are deprecated?
