### ISSUE TITLE
🐞 - `Multiselect` clears value on press `,`

### ISSUE THREAD

**Issue by vladimirpotekhin** [taiga-family/taiga-ui#8396]
### Playground Link

https://taiga-ui.dev/components/multi-select

### Description

`Multiselect` clears value on press `,` https://taiga-ui.dev/components/multi-select

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
separator is `,`
<img width="736" alt="image" src="https://github.com/user-attachments/assets/269afe82-42d2-4fe9-b378-351f70d64fd1">

**Comment by mdlufy** [comment]
Similar issue - #8290

**Comment by waterplea** [comment]
Closing as a duplicate in favor of https://github.com/taiga-family/taiga-ui/issues/8290
