### ISSUE TITLE
🐞 - calendar does not display cells correctly

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#8444]
### Playground Link

v4.x

### Description

![image](https://github.com/user-attachments/assets/38f1c858-40a9-430c-b3f6-3d988ca18b90)

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by ZvSimon** [comment]
Hello @splincode, I can take it if no one else is on it

ZvSimon

**Comment by mdlufy** [comment]
It's due to picker `right` interval changes from `-0.25rem` to `-0.1875rem`
[Taiga v4](https://github.com/taiga-family/taiga-ui/blob/main/projects/core/styles/mixins/picker.less#L82)
[Taiga v3](https://github.com/taiga-family/taiga-ui/blob/v3.x/projects/core/styles/mixins/picker.less#L82)

**Comment by hakimio** [comment]
Why do we even need that ugly `right: -.1875rem` hack? What was wrong with the `v3` approach?

**Comment by hakimio** [comment]
@waterplea why did you change from `right: -0.25rem` to `right: -0.1875rem` which  now creates a visible gap on 2k and 4k screens?
https://github.com/taiga-family/taiga-ui/commit/43904847ea473b555c87e680ed5da30fcf99d95a#diff-deca66c016fbcd6222924ba01ca4136adc7a8ac87db5c0fb0b3f2bbcedf9a798L81

**Comment by waterplea** [comment]
> @waterplea why did you change from `right: -0.25rem` to `right: -0.1875rem` which  now creates a visible gap on 2k and 4k screens?
> https://github.com/taiga-family/taiga-ui/commit/43904847ea473b555c87e680ed5da30fcf99d95a#diff-deca66c016fbcd6222924ba01ca4136adc7a8ac87db5c0fb0b3f2bbcedf9a798L81

On windows it does not create the gap, but instead prevent visible overlap since colors now have transparency. So far I haven't been able to figure out a solution that works properly on all DPIs, zooms and OSes. I will get on it again next week.

**Comment by hakimio** [comment]
I am on Windows 10 and it looks like this for me (2k screen, 125% windows UI scale):

![image](https://github.com/user-attachments/assets/b83077f9-83d7-4119-8565-40e64c8b6e9b)

If I increase the value to `-0.2rem`, the gaps is gone (at least at 100% browser zoom).

**Comment by waterplea** [comment]
I'm on the same setup and for me it looks ok. 0.2rem also looks ok, though, with no overlap, but that still leaves 1px gap on Mac with double DPI. 0.225rem works, but then an overlap starts to appear on windows when dragging new range.

**Comment by waterplea** [comment]
I think I got a solution that works, I'll try it tomorrow on all the screens I have.
