### ISSUE TITLE
🐞 - tui-root with background does not allow integration with other root elements and causes a white screen (v4.0)

### ISSUE THREAD

**Issue by hatsantos** [taiga-family/taiga-ui#8459]
### Description

After migrating to 4.0, my app starts with a blank screen. After some digging, it seems that the <tui-root> has a pseudo element :before has a white background, which prevents other elements from being visible.

![image](https://github.com/user-attachments/assets/7e1f7bc3-1642-473d-bd0d-e5c55197388c)

Forcing display: none (as suggested by @waterplea and @splincode) seems to do the trick:

![image](https://github.com/user-attachments/assets/adc589ff-46ef-4fbd-bdf7-739ea05734ed)

### Angular version

18.1.4

### Taiga UI version

4.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hatsantos** [comment]
Testing the new 4.0.1. Now there's other css property filling the screen with white:

![image](https://github.com/user-attachments/assets/80992edf-306b-419d-810c-342a3e85e7f8)

If property is disabled other elements can be visible:

![image](https://github.com/user-attachments/assets/5439ed18-c840-4380-bc3f-f17e10e69850)

**Comment by waterplea** [comment]
That property is there so toggling dark mode works across the whole app, even if `tui-root` is shorter than the window. You would need to override it yourself if you want to use different colors — we cannot set it as `html` background because you will not be able to toggle `[tuiTheme]="isDark ? 'dark' : 'light'"` there since it's outside of Angular scope. Do you have other ideas how we can take care of that?

**Comment by hatsantos** [comment]
I left the previous message because I had tried to modify the new attribute via CSS, but contrary to expectations, it wasn't working:

'''
tui-root {
	border-image: none;
}
'''

However, I remembered to set "!important" (which I hadn't done in a while 😄), and now it seems to work.

At the moment, I'm not using dark theme and I don't need to make any customizations related to it, so I think having it like this shouldn't be a major issue, at least I don't know what could be the real implications.
