### ISSUE TITLE
🐞 - TuiSegmented does not change the value

### ISSUE THREAD

**Issue by Aliaksandrzaz** [taiga-family/taiga-ui#8520]
### Playground Link

https://stackblitz.com/edit/angular-scmhzi?file=src%2Fapp%2Fapp.component.ts

### Description

If you set the value for control in `setTimeout`, `Segmented` does not change its activeIndex. It doesn't work without `ChangeDetectionStrategy.OnPush` either

### Angular version

18.1.4

### Taiga UI version

4.1.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by vladimirpotekhin** [comment]
https://github.com/taiga-family/taiga-ui/pull/8605
