### ISSUE TITLE
🐞 - `InputNumber` should not add/remove suffixes if `readOnly=true`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#8528]
### Playground Link

https://taiga-ui.dev/components/input-number/API?readOnly=true&tuiTextfieldPostfix=GBP

### Description

https://github.com/user-attachments/assets/0e72c8c5-329a-48ee-918b-09bcf226b7e6

### Angular version

16

### Taiga UI version

v3, v4

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Andronzi** [comment]
I wanna try it)
