### ISSUE TITLE
🐞 - `v3` docs version switcher broken

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#8530]
### Description

- Navigate to any component description in the documentation site
- Try to switch from `v4` to `v3`
- Instead of redirecting to `/v3/components/button`, it redirects to `/v3/` index page
- Pressing `Browse components` redirects back to `v4` docs

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
Ok, after clearing local storage and hard refresh, seems to be working again.

**Comment by nsbarsukov** [comment]
@hakimio It was my mistake, sorry

**Comment by hakimio** [comment]
No problem. Thanks for quick fix.
