### ISSUE TITLE
🐞 - Ошибка при скролинге в дропдауне. ObjectUnsubscribedErrorImpl

### ISSUE THREAD

**Issue by zavod008** [taiga-family/taiga-ui#8567]
### Description

https://taiga-ui.dev/components/multi-select#virtual

Если очень резво прокручивать список, то дропдаун исчезает, а в консоли появляется ошибка

https://github.com/user-attachments/assets/b52ed006-dced-4c8e-a79f-d72d7464762a

Прикладываю видос с воспроизведением

### Angular version

18.2.0

### Taiga UI version

4.2.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
I can't reproduce on MacOS
