### ISSUE TITLE
🐞 - Strange behavior on Safari with `tui-icon`

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#8577]
### Playground Link

taiga-ui.dev

### Description

https://github.com/user-attachments/assets/3dee42fd-10b5-40e2-a9ed-caa0760079cb

### Angular version

16.x

### Taiga UI version

4.x

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
I am not sure is a real bug

**Comment by waterplea** [comment]
Just to clarify, it is not reproducible on most machines we tested, we managed to only reproduce it on once setup and only on localhost. If you see something like this in real environment — please let us know.
