### ISSUE TITLE
🐞 - The issue with the Angular zone when using tabs-with-more

### ISSUE THREAD

**Issue by v-borodin** [taiga-family/taiga-ui#8586]
### Playground Link

https://stackblitz.com/edit/angular-tpbzsd?file=package.json

### Description

In Angular 17, I encountered the following warning in the console in a situation where the tab's template (by *tuiItem) is recreated according to the condition `*ngIf="index <= lastVisibleIndex; else hidden` (taken from the source):

Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?

https://github.com/user-attachments/assets/7e752087-8da7-4cc9-9941-89e7f784d854

### Angular version

17.3.12

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That's weird. We do not do anything that special there, just create and remove template dynamically and navigation is handled by Angular's routerLink. Might even be Angular issue, not Taiga UI issue. We need to try and reproduce this with just templates and routerLinks
