### ISSUE TITLE
🐞 - Incompatibility of `Chip` (`@taiga-ui/experimental@3`) & `Button` (`@taiga-ui/core@3`)

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#8600]
### Playground Link

https://stackblitz.com/edit/experimental-chip-with-stable-button-error-v3?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

### Description

```ts
import {TuiButtonModule} from '@taiga-ui/core';
import { TuiAvatarModule } from '@taiga-ui/kit';
import { TuiChipModule } from '@taiga-ui/experimental';

// [...]

imports: [
  TuiChipModule, // Comment me to hide error
  TuiButtonModule,
  TuiAvatarModule,
],
```

```html
<button tuiButton [iconRight]="icon">I'm button from @taiga-ui/core@3</button>

<ng-template #icon>
  <tui-avatar
    avatarUrl="https://taiga-ui.dev/v3/assets/images/avatar.jpg"
  ></tui-avatar>
</ng-template>
```

It throws 
```
Type 'TemplateRef<any>' is not assignable to type 'string'.
```

If import of `TuiChipModule` if removed – no error.

### Angular version

12

### Taiga UI version

3.90.0

**Comment by waterplea** [comment]
Chip adds icons directive that is applied to buttons too. In 4.x buttons only support strings anyway, so I'll close this as no fix planned as in 4 it is invalid scenario anyway. Avatar should just be inside button after the text.
