### ISSUE TITLE
🐞 - `Textarea` has unexpected content shift in Safari

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#8608]
### Playground Link

https://taiga-ui.dev/components/textarea#base

### Description

1. Open https://taiga-ui.dev/components/textarea#base
2. Replace all content with following one
```
This one can be expanded 1234
```
3. Put caret after the last digit and press backspace

### **Chrome ✅** 

https://github.com/user-attachments/assets/faa386e9-b373-49fb-961f-412b2b79c74c

### Safari Desktop ❌

https://github.com/user-attachments/assets/1ffd2573-0ecb-4959-923f-4ffbe48e8d9a

```
Safari 17.5 (19618.2.12.11.6)
MacBook Pro
Apple M3 Max
Mac OS 14.5 Sonoma
```

https://github.com/user-attachments/assets/32bd6fec-3a89-49c1-9e08-7963b0c658aa

### Angular version

16

### Taiga UI version

v3, v4

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I can already see me ragetweeting after we fix this :D
