### ISSUE TITLE
🐞 - InputPhoneInternational wrong number format for UAE

### ISSUE THREAD

**Issue by rvalitov** [taiga-family/taiga-ui#863]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/8h11fc--run?file=src/app/app.component.ts

### Description

Check the sample at https://taiga-ui.dev/components/input-phone-international#all-countries
A valid UAE phone number is +971-XX-XXX-XXXX
The InputPhoneInternational component thinks that a correct number is one digit less:
+971-X-XXX-XXXX

I'm afraid that a similar bug may happen for other countries. You don't use any verified phone format database here? I mean is there a way to guarantee that it works correctly for other countries?

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by rvalitov** [comment]
Another test is French phone number. It works, but it shows incorrect digit grouping. It must be +33 X XX XX XX XX instead of +33 (XXX) XXX-XXX.

Is there any recommendation how can I override or customize this correctly?

**Comment by nsbarsukov** [comment]
Hi!
We have this [constant](https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/kit/components/input-phone-international/const/countries.ts) with phone number masks.

You can help us and open PR with changes.
But please provide us with your source of correct phone number format.

**Comment by rvalitov** [comment]
@waterplea 
@nsbarsukov 
Checking further, I found out that some countries have different phone length for land line and mobile phones. Is it possible to enter in Taiga both combinations?
