### ISSUE TITLE
🐞 - Reorder issue

### ISSUE THREAD

**Issue by Groxot** [taiga-family/taiga-ui#8644]
### Playground Link

https://taiga-ui.dev/components/reorder

### Description

https://app.screencastify.com/v3/watch/yPpNO1D7HFDNXmM884XV

### Taiga UI version

4.3.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by aleksey-mu** [comment]
FYI it's working fine in v3.92
