### ISSUE TITLE
🐞 - Unknown country in TuiInputPhoneInternational

### ISSUE THREAD

**Issue by AlexFlyme** [taiga-family/taiga-ui#8645]
### Playground Link

https://stackblitz.com/edit/angular-vwhrsb?file=src%2Fapp%2Fapp.component.ts

### Description

Regardless of the selected country code, an error is generated that it does not exist.

![image](https://github.com/user-attachments/assets/bc1006cd-33cb-450c-b5e6-742bd99cf4d5)

![image](https://github.com/user-attachments/assets/6daae2d4-be0f-4351-824b-22a28c74e09d)

### Angular version

18.2.1

### Taiga UI version

4.3.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by AlexFlyme** [comment]
You need to add metadata to providers in the example on StackBlitz.

```
import {
    tuiInputPhoneInternationalOptionsProvider,
} from '@taiga-ui/kit';

providers: [
        tuiInputPhoneInternationalOptionsProvider({
            metadata: defer(async () =>
                import('libphonenumber-js/max/metadata').then((m) => m.default),
            ),
        }),
    ],
```

**Comment by maxpowel** [comment]
I upgraded from 4.2 to 4.3 and suffered the same.
In 4.2 you don't really need `tuiInputPhoneInternationalOptionsProvider` but looks that in 4.3 it is mandatory

**Comment by waterplea** [comment]
Yes, we initially wanted to enable it out of the box, but that was detrimental to tree shaking for those who do not use this component at all, so we had to make it an opt-in. Sorry for unintentional breaking change, there was no other way around it.
