### ISSUE TITLE
🐞 - `InputDateRange` throws `TypeError` if user selects anything from `[items]`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#8655]
### Playground Link

https://taiga-ui.dev/v3/components/input-date-range/API?items$=1

### Description

1. Open https://taiga-ui.dev/v3/components/input-date-range/API?items$=1
2. Click on textfield
3. Select any item (i.e. `Today`)
4. Blur
5. Click on textfield again

It throws
```
TypeError: Cannot read properties of null (reading 'toString')
    at O.isItemActive (main.c72e708eba5d5d22dd59.js:1:1256275)
    at M (main.c72e708eba5d5d22dd59.js:1:1253813)
    at yi (vendor.6b9778fb912286c3d952.js:1:187444)
    at mi (vendor.6b9778fb912286c3d952.js:1:186060)
    at vendor.6b9778fb912286c3d952.js:1:186487
    at mi (vendor.6b9778fb912286c3d952.js:1:186513)
    at vendor.6b9778fb912286c3d952.js:1:186487
    at mi (vendor.6b9778fb912286c3d952.js:1:186513)
    at Mi (vendor.6b9778fb912286c3d952.js:1:192967)
    at vendor.6b9778fb912286c3d952.js:1:186923
``` 

https://github.com/user-attachments/assets/43bc215c-cb50-4203-8a1f-87ed02c77969

### Angular version

12

### Taiga UI version

3.92.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by 40oleg** [comment]
May I take it?

**Comment by splincode** [comment]
@40oleg sure

**Comment by 40oleg** [comment]
@nsbarsukov I cannot reproduce this bug. I see that bug was on macOS but I do not have macbook, so I tried on browserstack. Tried many times but everything works fine. Can you check this on your laptop one more time?

**Comment by 40oleg** [comment]
@nsbarsukov It's seems that this is macos problem because another user reproduce it and open new issue [8820](https://github.com/taiga-family/taiga-ui/issues/8820)
Unfortunately I cannot solve it due to lack of macos.

**Comment by mdlufy** [comment]
@nsbarsukov @40oleg 
Tested on MacOs in Chrome, Safari, Yandex Browser locally and on demo-stand on versions 3.92.0 and 3.93.0 - nothing errors
Maybe there are some specific reproduce conditions ?

**Comment by splincode** [comment]
I can't reproduce
