### ISSUE TITLE
🐞 - `InputDateRange` should show the end of the selected range 

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#8656]
### Playground Link

https://taiga-ui.dev/components/input-date-range/API?items$=1

### Description

1. https://taiga-ui.dev/components/input-date-range/API?items$=1
2. Click on the textfiled
3. Select `For all the time` item (`January 0000` <=> `Today`)
4. Click on the textfield again

**Expected behavior:**
Calendar shows the **end** of the selected period (as it was before in `v3`).

**Actul behavior:**
Calendar shows the **beginning** of the selected period.
<img width="605" alt="date-range-actual" src="https://github.com/user-attachments/assets/675d12c6-b007-44ca-a45a-fe2a36b9ad3c">

### Angular version

16

### Taiga UI version

4.3.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by mdlufy** [comment]
Such behaviour was introduces in https://github.com/taiga-family/taiga-ui/commit/ef0c0f9f55135c8864902ae3cda3e425fb741b17#diff-8fda4881ec9c2cd09a2bf32685bee1e50c9f4880e0fb41586f6e88bc0001e3e7R103-R104
