### ISSUE TITLE
🐞 - ExpressionChangedAfterItHasBeenCheckedError occurs when using tuiLabel

### ISSUE THREAD

**Issue by johnitvn** [taiga-family/taiga-ui#8759]
### Playground Link

https://stackblitz.com/edit/angular-856324?file=src%2Fapp%2Fapp.template.html

### Description

When using tuiLabel console log shows error ExpressionChangedAfterItHasBeenCheckedError. 

![Capture](https://github.com/user-attachments/assets/b82cae3d-6917-48e7-947e-ff9b21a47e0e)

This error makes unit tests unable to run.
![Capture](https://github.com/user-attachments/assets/add0e22f-1e69-4392-9891-d3f397a791de)

### Angular version

18.2.2

### Taiga UI version

4.4.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by mohan-mu** [comment]
May be Related to `ChangeDetection` 

Error Appear When changeDetection is set to `ChangeDetectionStrategy.Default`

**Comment by mohan-mu** [comment]
Hi @splincode ,

I'm happy to take this bug , Any Idea/Gudelines on what could be wrong & how can i Investigate & how to fix it ?

**Comment by johnitvn** [comment]
> May be Related to `ChangeDetection`
> 
> Error Appear When changeDetection is set to `ChangeDetectionStrategy.Default`

I tried set changeDetection: ChangeDetectionStrategy.OnPush and it worked fine. Is this a bug? I don't see any mention in the documentation that this setting is required.
