### ISSUE TITLE
🚀 - Add Card Holder Name for InputCardGrouped

### ISSUE THREAD

**Issue by emiryumak** [taiga-family/taiga-ui#8775]
### Description

Some countries regulations or payment solutions APIs require cardHolderName. In this case, a field is required for the card holder name and the component is rendered unusable.

**Comment by waterplea** [comment]
I don't think there's anything to be done here to warrant a whole new component, you can just add autofill="cc-name" input to the same form and it should work.

Example for v4
```html
<tui-textfield>
  <label tuiLabel>Card holder</label>
  <input
    tuiTextfield
    formControlName="holder"
    autocomplete="cc-name"
  />
</tui-textfield>
```
https://stackblitz.com/edit/angular-scw1un
