### ISSUE TITLE
🚀 - option for required sorter in `Table`

### ISSUE THREAD

**Issue by waterplea** [taiga-family/taiga-ui#8785]
### Description

Sometimes we need sorter to be required in `Table`, so it must not be resettable by 3rd click.

https://stackblitz.com/edit/angular-tgs8kx

**Comment by 40oleg** [comment]
May I take it? But, Im not quite understand concept completely, can you clarify it a little bit?

**Comment by splincode** [comment]
@40oleg assigned

**Comment by 40oleg** [comment]
@splincode waterplea meant that sort in some column required and cannot be changed except 1 or -1? or it would be better if I wait for his answer?

**Comment by 40oleg** [comment]
@waterplea can you clarify the task a little bit?

**Comment by Aleksandr-Bondarev** [comment]
@40oleg We expect sorter value as string | number | symbol.

When clicking on the same sorter several times, we get a reset of the value to null. Although we want to see only ascending/descending sorting in the code.
