### ISSUE TITLE
🐞 - `TuiFilterByInput`: variable of type `TuiStringMatcher<T>` is not assignable as `TuiFilterByInput` pipe argument

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#8844]
### Description

Trying to do the following:
```html
[items]="items | tuiFilterByInput: itemMatcher"
```
where item matcher is defined as the following:
```ts
protected readonly itemMatcher: TuiStringMatcher<T> =
        (item: T, search: string): boolean => (item[this.displayProperty] as string).toLowerCase().startsWith(search.toLowerCase());
```
results in `Angular` compiler type error when Angular `strictTemplates` option is enabled.

### Angular version

18.2

### Taiga UI version

4

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Could you please provide a stackblitz or repo for reproduce
