### ISSUE TITLE
🐞 - tui-icon not working for none transparency svg, result in a black block instead

### ISSUE THREAD

**Issue by daihere1993** [taiga-family/taiga-ui#8881]
### Playground Link

https://stackblitz.com/edit/angular-smhfdt?file=src%2Fmain.ts

### Description

I've been migrating from v3.x.x to v4.x.x. Then I found out that there are some svgs can not display correctly when migrated from `<tui-svg>` to `<tui-icon>`. 

I've check the corresponding source code, seems the way of display svg has changed to use `mask` to point out where the svg is then display it. But this way seems can not display none transparency svg which would result in a black block as I showed below:

```html
<!-- good one -->
<tui-icon icon="@tui.accessibility"></tui-icon>
<!-- black block -->
<tui-icon icon="NoItemsCart"></tui-icon>
```
<img width="440" alt="image" src="https://github.com/user-attachments/assets/0b887555-ae83-4448-b963-f78fbe8b3187">

Example: https://stackblitz.com/edit/angular-smhfdt?file=src%2Fmain.ts

Seems this `<tui-icon>` is designed for simple icon only(I see there is a default size for each tui-icon which is 24px). Is there any expert can clarify it? As there is nothing related I can find in official docs.

### Angular version

18.2.0

### Taiga UI version

4.5.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This is expected. If your icons are already colored — there's no need to use `tui-icon`, you can just use `img`. As for the size — `tui-icon` will scale icons to fit its size, you can control it with `font-size` in a single rule or with `width`/`height`
