### ISSUE TITLE
🐞 - Number input не следит за курсором при вводе большого числа в инпут с маленькой шириной

### ISSUE THREAD

**Issue by o-korost** [taiga-family/taiga-ui#8899]
### Description

При вводе большого числа курсор уходит за пределы видимой области инпута 

https://github.com/user-attachments/assets/454c8b61-389d-41f0-9bb8-ae597bdacccf

### Angular version

17.1.3

### Taiga UI version

3.93.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
Relates:
* https://github.com/taiga-family/maskito/issues/917

This issue can closed after updating to Maskito to `>=3.0.2`

**Comment by nsbarsukov** [comment]
https://github.com/taiga-family/maskito/releases/tag/v3.0.2
