### ISSUE TITLE
🐞 - `v4` `BadgedContent`: icon is positioned incorrectly when it's shown with a delay

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#8907]
### Playground Link

https://stackblitz.com/edit/angular-phczdh?file=src%2Fapp%2Fapp.template.html,src%2Fapp%2Fapp.component.ts

### Description

`tui-icon` added to `tui-badged-content` with a delay is positioned incorrectly.

![image](https://github.com/user-attachments/assets/535537cc-041e-4e26-b219-f6560dc4d866)

### Angular version

18.2

### Taiga UI version

4.5.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like resize observer is triggered without change detection since it's not patched by zone.
