### ISSUE TITLE
🐞 - `CardLarge` contours invisible in `dark` mode

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#8936]
### Description

Even on a monitor with good color reproduction it's almost impossible to see card contours in dark mode:

![image](https://github.com/user-attachments/assets/35aa0801-8518-476e-a587-85b989d006fd)

### Angular version

18.2

### Taiga UI version

4.5.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
We need to update `--tui-background-elevation-1` to be `#292929` in dark mode

**Comment by hakimio** [comment]
Was this already fixed in #8825?
https://github.com/taiga-family/taiga-ui/pull/8825/files#diff-c7d6dca19e9b81e5c6c3c786c41693b728d5bb6b76707518c6112ed170a8365dL14

**Comment by hakimio** [comment]
Fixed in #8825.
