### ISSUE TITLE
🐞 - `CardLarge` mobile paddings are not applied

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#8939]
### Description

Mobile card paddings are not applied because of CSS specificity:

![image](https://github.com/user-attachments/assets/f9ff3ca5-87c1-46a8-80bd-5b41f22b6352)

### Angular version

18.2

### Taiga UI version

4.5.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by waterplea** [comment]
Specificity of this file need to be bumped:
https://github.com/taiga-family/taiga-ui/blob/main/projects/addon-mobile/styles/common/card-large.less
