### ISSUE TITLE
🐞 - Switch, Checkbox, Radio - appearance defined through input parameter is overridden internally

### ISSUE THREAD

**Issue by r0ss0neri** [taiga-family/taiga-ui#8944]
### Playground Link

https://stackblitz.com/edit/angular-bg223u-wn1sab?file=src%2Fapp%2Fapp.template.html

### Description

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/886b6a37-647f-4153-9a3d-e27fd5a85f8e">

Problem is [here](https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/components/switch/switch.component.ts#L50) 

### Angular version

18.2.2

### Taiga UI version

4.5.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by r0ss0neri** [comment]
Actually the same problem is for [Radio](https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/components/radio/radio.component.ts#L43) and [Checkbox](https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/components/checkbox/checkbox.component.ts#L72) components

**Comment by waterplea** [comment]
This is expected behavior, we exposed appearance just so you can control other things like state or focus manually. If you want a different appearance you should use DI:
https://taiga-ui.dev/components/switch#same-color

**Comment by r0ss0neri** [comment]
I see thanks, but having input parameter `appearance` is confusing https://github.com/taiga-family/taiga-ui/blob/main/projects/core/directives/appearance/with-appearance.ts#L11 wdyt?

**Comment by waterplea** [comment]
It works for other components we use that directive for. Just wanted to add it with one line for slightly smaller bundle and easy reading of the code, but in switch, checkbox and radio it can be rewritten as:
```ts
  {
    directive: TuiAppearance,
    inputs: ['tuiAppearanceState', 'tuiAppearanceFocus'],
  },
```
If you feel this would be beneficial — we'd be glad if you added a PR and we can reopen this issue with that fix.

**Comment by r0ss0neri** [comment]
Sure, will do!
