### ISSUE TITLE
🐞 - Clicking on Tooltip changes the read-only input

### ISSUE THREAD

**Issue by spahich** [taiga-family/taiga-ui#8966]
### Playground Link

https://stackblitz.com/edit/angular-ga7vqr

### Description

Если в `tui-checkbox-labeled` или `tui-radio-block` (а возможно еще что-то) положить внутрь `tui-tooltip`, то, несмотря на ридонли родителя, клик по тултипу меняет значение инпута.

### Angular version

15.0.2

### Taiga UI version

3.66.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by afferenslucem** [comment]
Guys, i'll fix this

**Comment by waterplea** [comment]
> Guys, i'll fix this

Great, go for it :+1: It's in the v3 branch only.
