### ISSUE TITLE
🐞 - Stackblitz is broken

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#8971]
### Description

<img width="780" alt="image" src="https://github.com/user-attachments/assets/990644d1-ca48-4955-a8dc-ac08b52c42fa">

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by mdlufy** [comment]
<img width="448" alt="image" src="https://github.com/user-attachments/assets/49bf32ea-6832-49db-a49d-53cf3282b5d7">
And `Stepper`

**Comment by splincode** [comment]
Will be fixed after release
