### ISSUE TITLE
🐞 - `Segmented` incorrect hover style when used with radio inputs

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#8980]
### Playground Link

https://taiga-ui.dev/navigation/segmented#content

### Description

Go to the [content demo](https://taiga-ui.dev/navigation/segmented#content), then try to hover over segmented components buttons in the **Buttons** and **Controls** sections.
You should see that the hover styles both for selected and unselected buttons are incorrect in the **Controls** section.

### Angular version

18.2

### Taiga UI version

4.6.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Oops, wrong. The background should stay transparent. I'll fix it.
