### ISSUE TITLE
🐞 - Rating Component - readOnly attribute not working

### ISSUE THREAD

**Issue by Rares212** [taiga-family/taiga-ui#8994]
### Playground Link

https://taiga-ui.dev/components/rating

### Description

Creating a simple tui-rating component, with [readOnly]="true" does not lead to expected behaviour. While the component no longer shows a hover effect, it still allows the user to modify the displayed rating value (which may be different than the tracked ngModel value).

You can see this issue in the official TaigaUI documentation as well (https://taiga-ui.dev/components/rating - Static example)

### Angular version

18.2.3

### Taiga UI version

4.5.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Could you clarify how? I tried using mouse and keyboard and it didn't allow me to change value. Although I did notice that for some reason the underlying input has value of 9 instead of 8.5, maybe because the step attribute is missing and browser rounded it to 9?

**Comment by Rares212** [comment]
Test machine:
- Desktop, Win 10, Version 22H2 (OS Build 19045.4894)
- Browser: Firefox 130.0 (64-bit) and Chrome Version 128.0.6613.138
- Steps to recreate (didn't create a playground link as the issue was reproducible in the TaigaUI docs):

1. Go to https://taiga-ui.dev/components/rating - Static section
2. This is the default rating shown on the webpage:
![image](https://github.com/user-attachments/assets/6c0df986-60f0-4342-b0bb-c181d545e112)
3. This is what happens after I mouse click on the 4 star rating:
![image](https://github.com/user-attachments/assets/16e6f93d-04ea-406c-88ad-cdcac9c701e7)

Expected behavior: given the [readOnly]=true attribute, I expected not to be able to change the rating.

PS: I just tested this on my Macbook M2 Pro (Sonoma 14.5), on Chrome version 119.0.6045.149 (arm64). It seems to work just fine over there. This issue perhaps only affects Windows machines, or specific browser versions.

**Comment by waterplea** [comment]
I'm unable to reproduce it anywhere, neither on Windows 10 Chrome 128/Firefox 130, nor on Mac. It uses plain old `pointer-events: none;` to ignore all clicks, I highly doubt it stops working all of a sudden. Could you try changing `label` to `div` in devtools to see if maybe it's label that is messing with the clicks somehow? Do you have something special about your windows machine such as plugins, assistive technology tools etc?

**Comment by Rares212** [comment]
I just upgraded my angular project to the latest versions, along with TaigaUI 4.7, and I can no longer reproduce this issue on the same chrome/firefox + Windows 10 configuration.

Thanks for your help, I'm going to try to dive in a bit more in depth with the old version to see if I can get down to the root cause of things.
