### ISSUE TITLE
🐞 - Криво показывается инфа о InputCardGroup

### ISSUE THREAD

**Issue by evoytenkoapps** [taiga-family/taiga-ui#9054]
### Description

в витрине InputCardGroup, в API, при установке icon, в селекте показывается какой-то код

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by evoytenkoapps** [comment]
по словам Инкина - "это там шаблон на самом деле, так выглядит его toString. Хорошо бы поправить там отображение. "

**Comment by hakimio** [comment]
That's intended. It's the stringified `ng-template`: https://github.com/taiga-family/taiga-ui/blob/bee65c930fb845c3983ef44c9f3b5d9d7d867086/projects/demo/src/modules/components/input-card-group/index.html#L44

**Comment by waterplea** [comment]
> That's intended. It's the stringified `ng-template`:
> 
> https://github.com/taiga-family/taiga-ui/blob/bee65c930fb845c3983ef44c9f3b5d9d7d867086/projects/demo/src/modules/components/input-card-group/index.html#L44

Yes, the idea here is to just show "TemplateRef" there instead of a stringified version of it since it does not provide anything meaningful anyway.
