### ISSUE TITLE
🐞 - broken gap

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#9060]
### Playground Link

/components/push

### Description

<img width="589" alt="image" src="https://github.com/user-attachments/assets/bc062b4f-a6e6-432f-8ec1-74cb8786ae85">

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Missing `background: var(--tui-background-elevation-3);` on `.wrapper` in a demo example
