### ISSUE TITLE
🐞 - tuiCell bottom and top margins are not equal

### ISSUE THREAD

**Issue by MSonini** [taiga-family/taiga-ui#9077]
### Code Example URL

https://stackblitz.com/edit/angular-abf6bb?file=src%2Fapp%2Fapp.template.html,src%2Fapp%2Fapp.component.ts,package.json&hideExplorer=1

### Description

tuiCell bottom and top margins are not equal
![image](https://github.com/user-attachments/assets/e00f448e-b0c4-41d3-af03-93e6b0a3115b)

### Taiga UI version

3.93.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Working by design, this is for cards with headings and multiple cells. For one cell shown as card put it on the same tag:
```html
<div tuiCardLarge tuiCell tuiSurface="elevated" class="requisities">
  <tui-avatar class="icon" src="tuiIconHeartLarge" />
  <div tuiTitle tuiFade>
    <div tuiSubtitle>Some Text</div>
    <div class="address" automation-id="address">Some Text</div>
  </div>
</div>
```

**Comment by mdlufy** [comment]
Also need add to v3
