### ISSUE TITLE
🐞 - No provider for TuiAsideComponent error

### ISSUE THREAD

**Issue by tsironis13** [taiga-family/taiga-ui#9087]
### Code Example URL

https://stackblitz.com/edit/angular-cvj86f?file=src%2Fapp%2Fapp.template.html

### Description

No provider for TuiAsideComponent when using the `tuiAsideItem `directive.

<img width="694" alt="image" src="https://github.com/user-attachments/assets/51aa2472-076d-43e2-9231-829c5c915583">

### Taiga UI version

4.7.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by tsironis13** [comment]
I added the TuiAsideComponent in the providers array of the component and the problem seems to be fixed. Is it something expected although it is not mentioned in the documentation?

<img width="217" alt="image" src="https://github.com/user-attachments/assets/bbb68d71-1bea-4022-867c-971868d424e9">

**Comment by waterplea** [comment]
You forgot to add `tuiNavigationAside` component to your `aside` tag
