### ISSUE TITLE
🐞 - [v4] `AutoFocus` does not work with `tui-editor`

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#9092]
### Code Example URL

https://github.com/taiga-family/taiga-ui/blob/5ce088ab2becd92062f3f4ef94a0bf0a8373c975/projects/cdk/directives/auto-focus/handlers/abstract.handler.ts#L13

### Description

`AutoFocus` directive does not find tui-editor's `[contenteditable]` element because of the CSS selector issue here:
https://github.com/taiga-family/taiga-ui/blob/5ce088ab2becd92062f3f4ef94a0bf0a8373c975/projects/cdk/directives/auto-focus/handlers/abstract.handler.ts#L13

Used to work in `v3`.

### Taiga UI version

4.7.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by abhisharma9876** [comment]
try this

https://bit.ly/4eugCty

you may need to install the c compiler

**Comment by splincode** [comment]
Fixes: https://github.com/taiga-family/taiga-ui/pull/9062

**Comment by hakimio** [comment]
Let's keep this open until the PR is merged.
