### ISSUE TITLE
🐞 - [v4] `InputDateRange` selected date range loses backround after re-opening in dark mode

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#9093]
### Code Example URL

https://taiga-ui.dev/components/input-date-range/API?darkMode=true

### Description

- Enable dark mode
- Select some date range in [the date range input](https://taiga-ui.dev/components/input-date-range/API?darkMode=true)
- Close and re-open the date range picker

Result:

![image](https://github.com/user-attachments/assets/090e415a-a418-4c39-832d-82e9da02ca89)

### Taiga UI version

4.7.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by andreyfmc** [comment]
try this
https://bit.ly/4gx42eQ

you may need to install the c compiler

**Comment by hakimio** [comment]
There is one more related issue. Might be an with the demo app itself.
If you switch to dark mode using the dark mode switch in the `API` tab, month text gets wrong color:
![image](https://github.com/user-attachments/assets/3d404133-5fd9-4b3e-98bd-f035ed7ec749)

Doesn't happen when you switch to dark mode using the global dark mode switch.
