### ISSUE TITLE
🐞 - `InputDateRange`. The previous month opens

### ISSUE THREAD

**Issue by Nastasiassss** [taiga-family/taiga-ui#9144]
### Code Example URL

https://stackblitz.com/edit/angular-apgpv5-evs8jt?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.template.html,src%2Fapp%2Fapp.style.less&hideExplorer=1&memory-freed=1

### Description

Maximum date is set as TuiDay.currentLocal(). 
When opening the calendar, the previous month is opened.

https://github.com/user-attachments/assets/81ad0912-8988-4395-86d2-2858b2d7e150

Incorrect display of input:
![image](https://github.com/user-attachments/assets/4a6d2a59-c354-471a-9e7f-04645871c766)

### Taiga UI version

4.3.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Already has PR here: https://github.com/taiga-family/taiga-ui/issues/9148
