### ISSUE TITLE
🐞 - `InputDateRange` incorrect display of input

### ISSUE THREAD

**Issue by mdlufy** [taiga-family/taiga-ui#9157]
### Code Example URL

https://stackblitz.com/edit/angular-apgpv5-evs8jt?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.template.html,src%2Fapp%2Fapp.style.less&hideExplorer=1&memory-freed=1

### Description

Incorrect display of input:
![image](https://github.com/user-attachments/assets/4a6d2a59-c354-471a-9e7f-04645871c766)

![image](https://github.com/user-attachments/assets/bc370cb8-5a52-4fbc-bfe3-85392db8ed78)

### Taiga UI version

4.7.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Working as expected, in legacy inputs you need to either provide a label or use `[tuiTextfieldLabelOutside]="true"`, like in v3.x
