### ISSUE TITLE
🐞 - Double scrollbar

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#9176]
### Code Example URL

https://taiga-ui.dev/

### Description

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/7c023b20-dd82-429d-9cec-b08ec8a9db91">

When `Show always scrollbar` is enabled 
<img width="546" alt="image" src="https://github.com/user-attachments/assets/c0bf936f-d2b5-4461-a550-e5e2da8e9371">

### Taiga UI version

latest

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Needs `margin: 0` on `body`
