### ISSUE TITLE
🐞 - Strange dropdown behavior

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#9186]
### Code Example URL

https://taiga-ui.dev/viewport

### Description

https://github.com/user-attachments/assets/0d7e45eb-d53c-42f7-9d44-503bf0673f77

### Taiga UI version

latest

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Closing in favor of one with stackblitz:
https://github.com/taiga-family/taiga-ui/issues/9683
