### ISSUE TITLE
🐞 - missing scss

### ISSUE THREAD

**Issue by ng-state** [taiga-family/taiga-ui#9199]
### Code Example URL

no

### Description

Hi,

i would love to add thi UI library to our upcoming huge project (and accross the company) but i would really like to use SCSS (I dropped already candidates like NG ZORRO because of sticking to less) and i thought that Taiga supports boths but for some reason there are only few sccs files up in node_modules folder but misssing files like 

 "@taiga-ui/core/styles/taiga-ui-theme.less",
  "@taiga-ui/core/styles/taiga-ui-fonts.less",
  
  is there a specific reason? Can I use it still or should i investigate other UI libraries?

### Taiga UI version

latest

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
You can use it with SCSS, these are global styles and you can just add them to `styles` array in `angular.json`, Angular CLI will mix it with the rest of you SCSS styles just fine :)

**Comment by ng-state** [comment]
when Angular is set to SCSS will it understand less files?
Also how then from within SCSS i can override less variables and themes?

**Comment by waterplea** [comment]
Angular will understand it, yes. We do not use less variables, we use CSS variables and you can override them in CSS/SCSS, just make sure your overrides are added after our styles so they take precedence.

**Comment by waterplea** [comment]
For example, add this CSS file to the end of `styles` array:
```css
[tuiTheme="dark"] {
  --tui-text-primary: red;
}

:root,
[tuiTheme="light"] {
  --tui-text-primary: pink;
}
```

**Comment by ng-state** [comment]
ok then 
sry for asking questions here but there is not much documentations outside...
should whole app content should be wrapped into 	<tui-root> and why? this is somehow feels starnge because i was expecting only to import components and use them. Is this because of overlayes like modal, notifications and others or?

**Comment by waterplea** [comment]
Yes, it's for overlays and global scrollbar. Here's an article about it:
https://angular.love/demystifying-taiga-ui-root-component-portals-pattern-in-angular
It's a bit dated since we no longer have modules and cannot have `NG_EVENT_PLUGINS` built-in, but it will give you an overview of it. You can use `Discussions` section here for questions in the future, it's a better fit than issues ;)

**Comment by ng-state** [comment]
Thank you for quick response. Looking forward to use.

btw i thought variables can be manipulated within styles.scss but appereantly only in app.component.scss because of taiga-root or?

**Comment by waterplea** [comment]
It's really nothing special, just default CSS variables. Here's what you get in theme file that you hook up:
https://github.com/taiga-family/taiga-ui/blob/main/projects/core/styles/theme/palette.less
So if you do what I said above and add your styles **after** the theme in `angular.json` they would override built-in values. `tui-root` sets `font: var(--tui-font-text-s)`, you can override it by anything you want, all of this is not really Taiga UI related, just basic HTML/CSS

**Comment by ng-state** [comment]
Thanks

**Comment by ng-state** [comment]
do you have input for password? cannot see it on your list...

**Comment by ng-state** [comment]
one more thing - i have included default htema but after adding input i have this view
![Screenshot 2024-09-26 at 12 52 31](https://github.com/user-attachments/assets/9e8499d6-c0bc-45a7-a75c-c50190d27f00)

as you can see it is completely hidden until not focused and in css --tui-height-l is not defined.
Any suggestions how to fix it would be awesome :)

**Comment by waterplea** [comment]
CSS variables for colors are listed here:
https://taiga-ui.dev/colors

Input for password is here:
https://taiga-ui.dev/components/textfield#interactive-icons

Textfields are currently being refactored so the documentation is not yet in its final form. Not sure about issues with links you speak of.

As for your last screenshot, maybe you've forgotten `tuiTextfield` directive on `input`?

**Comment by ng-state** [comment]
no my last screen code looks like thi:

<form [formGroup]="form">
                    <tui-textfield>
                      <input formControlName="userName" />
                    </tui-textfield>
                    <tui-textfield>
                      <input formControlName="userName" />
                    </tui-textfield>
                </form>
                
                p.s. will refactor be significant?

**Comment by waterplea** [comment]
Add `tuiTextfield` directive to `input` tags. 

Refactor is rewriting all controls from "legacy" package to that new `tui-textfield`.

**Comment by ng-state** [comment]
Thanks

**Comment by ng-state** [comment]
I have tried to override --tui-duration variable but it is overriden by inline style from tui-root. Any suggestions?

![Screenshot 2024-09-26 at 15 01 15](https://github.com/user-attachments/assets/b9eb9ad6-e1a2-42a2-aca8-d449d8862cd6)

**Comment by waterplea** [comment]
`--tui-duration` is a special case because it is used in both CSS and Angular Animations. To change speed of animations provide `TUI_ANIMATIONS_SPEED`, default is `1`. We need to add that to the docs.

**Comment by ng-state** [comment]
one more bug (i think)

i hav provider for button: tuiButtonOptionsProvider({ appearance: 'parama-button', size: 'm' }),
with size - m, but in style scheets i see

![Screenshot 2024-09-26 at 15 49 45](https://github.com/user-attachments/assets/f9750696-1f72-416e-9373-8e5bf267a1ee)

**Comment by ng-state** [comment]
Please advice how to do password input with clickable icon (i cannot find in your exzmples). Thanks
![Screenshot 2024-09-26 at 17 51 53](https://github.com/user-attachments/assets/e42f5244-7f75-43dd-8a5a-3a7b7dcb9c00)

**Comment by vytautas-pranskunas-** [comment]
?  I have asked about how to place clickable icon to  textfield 🙂

**Comment by vytautas-pranskunas-** [comment]
Upps. Missed that. Thank you.

**Comment by ng-state** [comment]
please suggest appeareance for hint
i cannot find it here

https://github.com/taiga-family/taiga-ui/tree/main/projects/core/styles/theme/appearance

**Comment by vytautas-pranskunas-** [comment]
Also do you have solution for error labels under tui-textfield or it should be added manually? 
If needs to be added manually  (not like tui-label inherits error styling) then maybe tui-textfield can emit state is it error or not?

**Comment by vytautas-pranskunas-** [comment]
can <tui-error [error]="computedError" /> automatically get erro from reactive form or from text-field state or i have to do manual map from form errors

`
protected error = new TuiValidationError('An error');
 
    protected get computedError(): TuiValidationError | null {
        return this.enabled ? this.error : null;
    }
`

**Comment by waterplea** [comment]
Here's how you link `tui-error` to control:
```html
<tui-error 
  formControlName="myControl"
  [error]="['first-priority-error', 'second-priority-error', ...] | tuiFieldError | async"
/>
```
You can use empty array `[]` if you do not care about what error takes precedence. You can use any control directive to link error to control, `[formControl]`/`formArray`/`formGroup`...

**Comment by waterplea** [comment]
Let's move each separate question to its own discussion from now on so it can help others and not throw it all into this issue.

**Comment by vytautas-pranskunas-** [comment]
And this first-priority-error i assume like required, min-length etc?

**Comment by waterplea** [comment]
Yes, in case it has multiple errors – which one you should show in that order

**Comment by vytautas-pranskunas-** [comment]
thats strange. After i added 

` <tui-textfield class="gap-1-5x">
                        <input tuiTextfield formControlName="username" />
                    </tui-textfield>
                    <tui-error formControlName="username" />
`

i got this error
`
core.mjs:7188 ERROR RuntimeError: NG01203: No value accessor for form control name: 'username'. Find more at https://angular.dev/errors/NG01203
    at _throwMissingValueAccessorError (forms.mjs:3419:9)
    at setUpControl (forms.mjs:3201:29)
    at _FormGroupDirective.addControl (forms.mjs:5319:5)
    at _FormControlName._setUpControl (forms.mjs:6010:39)
    at _FormControlName.ngOnChanges (forms.mjs:5959:28)
    at _FormControlName.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:3978:10)
    at callHookInternal (core.mjs:5007:10)
    at callHook (core.mjs:5034:5)
    at callHooks (core.mjs:4991:9)
    at executeInitAndCheckHooks (core.mjs:4946:5)
`

p.s. without tui-error it works.. am i missing something?

**Comment by waterplea** [comment]
Because you forgot `[error]="[] | tuiFieldError | async"`. The `tuiFieldError` pipe is the consumer of `formControlName`, you cannot use reactive control with some sort of value accessor.

**Comment by vytautas-pranskunas-** [comment]
i did not just thought since it is empty then not nessecarry.|
it solves error problem but styling is not applied:
`
<tui-error formControlName="username" [error]="[] | tuiFieldError | async" />

tuiHintOptionsProvider({ appearance: 'parama-hint' }),

[data-appearance='parama-hint'] {
    @include transition(all, var(--duration));

    color: #fff;
    background: linear-gradient(43deg, #4158d0 0%, #c850c0 46%, #ffcc70 100%);
    font-weight: bold;
}
`

what am i missing?

**Comment by waterplea** [comment]
Probably your styles have lower specificity. This isn't really Taiga UI related, you would need to investigate in devtools. Here's a demo for your case:
https://stackblitz.com/edit/angular-m95psp
