### ISSUE TITLE
🐞 - `Scrollbar` resets vertical scroll position when scrolling horizontally with slider

### ISSUE THREAD

**Issue by scrolltex** [taiga-family/taiga-ui#9216]
### Code Example URL

https://taiga-ui.dev/components/scrollbar#all

### Description

When you scroll the slider in one direction, the scroll position in the other direction is reset. 
There are no problems when scrolling on a mobile device or by pressing the middle mouse button.

The issue is reproduced in https://taiga-ui.dev/components/scrollbar#all
But in 3.95.1 there are no problems: https://taiga-ui.dev/v3/components/scrollbar#all

### Taiga UI version

4.8.1

### Browser Used

Chrome

### OS Used

Windows

**Comment by waterplea** [comment]
Also looks like scroll jumps depending on the coordinate of the press inside the bar 🤔
