### ISSUE TITLE
🐞 - Select - dropdown content is not shown if initial state is opened

### ISSUE THREAD

**Issue by r0ss0neri** [taiga-family/taiga-ui#9224]
### Code Example URL

https://stackblitz.com/edit/angular-az8rzh?file=src/app/app.template.html,src/app/app.component.ts

### Description

Use case is to open a dropdown menu for select automatically. I used `[tuiDropdownOpen]` which is coming from `TuiDropdownOpenLegacy` directive but for some reason it's not working (sorry didn't have time to debug more). 

In provided example the problem is that dropdown open state is updated automatically to `false`. And also interesting example where `tuiDropdownOpenChange` is not used, please check here https://stackblitz.com/edit/angular-az8rzh-auyhbj?file=src%2Fapp%2Fapp.template.html.

In this case select is focused and arrow icon remains in the position when dropdown is opened, but dropdown content is not shown

<img width="673" alt="image" src="https://github.com/user-attachments/assets/7b496644-1dd0-45ce-ae5f-31a1cb63e023">

### Taiga UI version

4.8.1

### Browser Used

Chrome

### OS Used

macOS

**Comment by mohan-mu** [comment]
Here is Working Example . 

moved `tuiDropdownOpen` to `AfterViewInit` Lifecycle

https://stackblitz.com/edit/angular-az8rzh-ugvdqf?file=src%2Fapp%2Fapp.component.ts

**Comment by waterplea** [comment]
Dropdowns automatically close if the host is out of sight. Could be that if it is set to true initially it gets processed even before the element is properly added to DOM so it thinks that it's not visible and immediately closes. Would workaround by @mohan-mu work for you?

**Comment by r0ss0neri** [comment]
Actually I provided a minimum reproducible example, in case if component will be instantiated later (e.g. hidden by `ngIf`) it will not work. Please check https://stackblitz.com/edit/angular-az8rzh-pztsag?file=src/app/app.template.html,src/app/app.component.ts

**Comment by r0ss0neri** [comment]
This approach is working on stackblitz, but not in our application:) https://stackblitz.com/edit/angular-az8rzh-km4nwq?file=src%2Fapp%2Fapp.template.html,src%2Fapp%2Fapp.component.ts

**Comment by r0ss0neri** [comment]
@waterplea do you guys have any insight on when this bug might be fixed? We use this feature a lot in our application and our current workaround is not ideal for users, it takes 1s to open a menu (we use a setTimeout function). Thanks.
