### ISSUE TITLE
🐞 - Need more space between tui-chip and header

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#9231]
### Code Example URL

any

### Description

<img width="298" alt="image" src="https://github.com/user-attachments/assets/a6a8a1c4-b102-4349-919c-24c81de3fe03">

### Taiga UI version

latest

### Browser Used

Chrome

### OS Used

macOS

**Comment by galanggg** [comment]
hi @splincode , can i get more information about this bug? is it only when using chinese characters? Thanks.

**Comment by splincode** [comment]
`is it only when using chinese characters? ` when I use google translate page for Chinese

**Comment by galanggg** [comment]
aaa I can also reproduce when changing the language. Does that mean in this issue we need to add a `margin-left`? because I see the `margin-right` is already there. @splincode

**Comment by splincode** [comment]
@waterplea I don't know, maybe that issue isn't relevant
