### ISSUE TITLE
🐞 - Hydration error while configuring Table component

### ISSUE THREAD

**Issue by tsironis13** [taiga-family/taiga-ui#9278]
### Code Example URL

https://stackblitz.com/

### Description

<img width="284" alt="image" src="https://github.com/user-attachments/assets/7adeecbf-8d67-4c3b-a494-3ffac78591ef">

```
@Component({
  selector: 'nx-suite-ui-table',
  standalone: true,
  imports: [
    AsyncPipe,
    NgTemplateOutlet,
    TuiTablePagination,
    TuiLet,
    TuiReorder,
    TuiTable,
    ToStringPipe,
    FormsModule,
    NgForOf,
    NgIf,
    ReactiveFormsModule,
    TuiButton,
    TuiChevron,
    TuiDropdown,
    TuiInputModule,
    TuiInputNumberModule,
    TuiLoader,
    TuiTextfieldControllerModule,
  ],
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NxSuiteUiTableComponent<T> implements TableComponent<T> {
  public readonly size = input.required<TableSize>();
  public readonly columns = input.required<TableColumnType<T>[]>();
  public readonly data = input.required<T[]>();
  public readonly contextMenu = input<any>();

  protected readonly sorter$ = new BehaviorSubject<any>('name');

  protected columns1 = ['id', 'name', 'description', 't'];

  protected readonly mappedColumns = computed(() =>
    this.columns().map((i) => i.field)
  );

  protected page = 3;
  protected size1 = 10;

  protected onPagination({ page, size }: TuiTablePaginationEvent): void {
    this.page = page;
    this.size1 = size;
  }
}
```
I am getting the following error with the defined structure:
<img width="794" alt="image" src="https://github.com/user-attachments/assets/b1cbcc07-fbf8-4032-86a5-3e1018e67eab">

I am using AnalogJS with SSR enabled.

### Taiga UI version

4.7.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by splincode** [comment]
Could you provide mini github repo? I can't reproduce on here https://github.com/taiga-family/taiga-playground

**Comment by tsironis13** [comment]
This is the repo you could use: https://github.com/tsironis13/nx-suite
After installing npm dependencies, run npx nx serve eshop-admin and
navigate to /categories.
The error will be shown on the console.

Στις Δευ 7 Οκτ 2024 στις 1:45 μ.μ., ο/η Maksim Ivanov <
***@***.***> έγραψε:
