### ISSUE TITLE
🐞 - Mobile InputDateRange breaks page when single date is selected

### ISSUE THREAD

**Issue by stanislav-osipov** [taiga-family/taiga-ui#9351]
### Reproduction url

https://taiga-ui.dev/v3/components/input-date-range#base

### Description

Can be reproduced in taiga v3 and v4

1. Go to https://taiga-ui.dev/v3/components/input-date-range#base with mobile emulation
2. **Important:** clear the value of input without opening calendar
3. Click on any date (only one) once
4. Click Done

Result: 

TypeError: value.getFormattedDayRange is not a function is thrown multiple times so **page is broken and has to be reloaded**

Expected:

No value is set in control when only one date is selected - similar to desktop

### Taiga UI version

3.94.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by stanislav-osipov** [comment]
Hi,
will this fix be applied to v3?

**Comment by nsbarsukov** [comment]
> Hi @nsbarsukov, will this fix be applied to v3?

I'll cherry-pick this fix to `v3` today 👍
