### ISSUE TITLE
🐞 - InputCardGroup wrong autofill behaviour

### ISSUE THREAD

**Issue by Kringiner** [taiga-family/taiga-ui#9410]
### Reproduction url

https://stackblitz.com/edit/angular-7e9kl3?file=src%2Fapp%2Fapp.template.html,src%2Fapp%2Fapp.component.ts&hideExplorer=1

### Description

On Safari, when use credit card autofill (pan + expire date) focus dont move from expire input (stay on the end of date) to cvc. On Firefox, same case but focus remains on PAN input. 

P.S. on demo page https://taiga-ui.dev/components/input-card-group - when use autofill card on Chome card data paste to all inputs examples (maybe its problem). Example also reproduce on demo page.

Safari after autofill: 
![Снимок экрана 2024-10-09 в 14 37 23](https://github.com/user-attachments/assets/be6c7d47-8673-4549-8c72-7a47d04db9ce)

### Taiga UI version

4.10.0

### Browser Used

Safari

### OS Used

macOS

**Comment by mdlufy** [comment]
> ### Reproduction url
> https://stackblitz.com/edit/angular-7e9kl3?file=src%2Fapp%2Fapp.template.html,src%2Fapp%2Fapp.component.ts&hideExplorer=1
> 
> ### Description
> On Safari, when use credit card autofill (pan + expire date) focus dont move from expire input (stay on the end of date) to cvc. On Firefox, same case but focus remains on PAN input.
> 
> P.S. on demo page https://taiga-ui.dev/components/input-card-group - when use autofill card on Chome card data paste to all inputs examples (maybe its problem). Example also reproduce on demo page.
> 
> Safari after autofill: ![Снимок экрана 2024-10-09 в 14 37 23](https://private-user-images.githubusercontent.com/55991290/374899070-be6c7d47-8673-4549-8c72-7a47d04db9ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTAxMDcsIm5iZiI6MTcyOTQ4OTgwNywicGF0aCI6Ii81NTk5MTI5MC8zNzQ4OTkwNzAtYmU2YzdkNDctODY3My00NTQ5LThjNzItN2E0N2QwNGRiOWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA1NTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZGNlOGQ5MDBlNGU3Y2UzNTUyMWYyZTFmMWU4NjM4ZmUyZmZlNTU4OTA1NTZjMzdiMTIwYmI1NzIwNGNjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ODfdXFb_W8zLbyj5kEIwQ8mt1zgWs4MC0sHqMuVl_7g)
> 
> ### Taiga UI version
> 4.10.0
> 
> ### Browser Used
> Safari
> 
> ### OS Used
> macOS

Safari fixed. For Firefox, please, create another issue if it's actual. Demo don't reproduce
