### ISSUE TITLE
🐞 - NgControl not injected

### ISSUE THREAD

**Issue by jimyhdolores** [taiga-family/taiga-ui#9478]
### Reproduction url

https://stackblitz.com/edit/angular-juvzbq?file=src%2Fapp%2Fapp.template.html

### Description

When I use the tui-input component it throws the following error in the browser console:
![image](https://github.com/user-attachments/assets/0160fa43-bff9-4ac3-8307-9907363d3882)
It seems to me that I must use a [(ngModel)] or [formControl] or formControlName. But this should not be mandatory, that does not happen with Angular Material for example. In any case, I put it as a "suggestion" because they are currently throwing an "error" and a less experienced developer may think "I'm doing something wrong or the component doesn't work"

### Taiga UI version

4.10.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by waterplea** [comment]
This is working as expected, our controls are meant to work with Angular forms.
