### ISSUE TITLE
🐞 - `Chip` has non-interactive text label

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#9501]
### Reproduction url

https://taiga-ui.dev/components/chip#interactive

### Description

1. Open https://taiga-ui.dev/components/chip#interactive
2. Try to click on the text at the center of the chip

https://github.com/user-attachments/assets/7c828ba1-4fee-416b-bc9a-fa7b2914851f

### Taiga UI version

4.11.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
I suppose the demo is broken, it shouldn't be `tui-chip`, it should be `label tuiChip`. Input is purposefully sank with z-index, in case it has an appearance with non-transparent background.
