### ISSUE TITLE
🚀 - `InputPhoneInternational` mask separator customisation

### ISSUE THREAD

**Issue by FranckG28** [taiga-family/taiga-ui#9518]
### Description

Maskito provide an option to customise the phone mask separator (as seen [here](https://maskito.dev/addons/phone/API))
![image](https://github.com/user-attachments/assets/9bd0e723-4679-4579-ae1b-614eccbe0abe)
This is very useful because in France for example, we don't use `-` as a separator.

The lack of a way to change the separator in `InputPhoneInternational` leads to an incoherent display between the phone number displayed with MaskitoPipe (where I changed the separator) and within the input (where the separator is still `-`).

![image](https://github.com/user-attachments/assets/b3328e65-3ab6-411f-b36a-f46685e947d2)

From what I've seen in the source code [here](https://github.com/taiga-family/taiga-ui/blob/25494182f7b4b92bb04763d8018e5a828d07fcf6/projects/kit/components/input-phone-international/input-phone-international.component.ts#L231), there is no options provided to change this separator in component `InputPhoneInternational`.

This could be resolved by adding an `[separator]` property on `InputPhoneInternational`, a provider to customise it, or both 😎

PS: Version 4.0 is amazing, keep up the great work 🔥

**Comment by nezar-khamidekh** [comment]
I will take it
