### ISSUE TITLE
🐞 - Using `tuiAutoFocus` on `InputPhoneInternational` doesn't focus the phoneNumber input anymore

### ISSUE THREAD

**Issue by FranckG28** [taiga-family/taiga-ui#9543]
### Reproduction url

https://stackblitz.com/edit/angular-tzfn4f?file=src%2Fapp%2Fapp.component.ts

### Description

Since v4, usage of the `tuiAutoFocus` directive on `InputPhoneInternational` is focusing the countryIsoCode selector, preventing the user to directly start typing a phone number.
![image](https://github.com/user-attachments/assets/61599ac1-f6e9-428d-a27e-c9a5bcabb2f2)

This is a regression from v3 where the phoneNumber input is focused, which I think is the right behavior.
![image](https://github.com/user-attachments/assets/6b6a0c96-19fb-438a-a558-9cae3b809b4f)
[v3 reproduction example here](https://stackblitz.com/edit/angular-uaermf?file=src%2Fapp%2Fapp.component.html)

### Taiga UI version

4.11

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
I have an idea to turn it into regular textfield, rather than specific tui-input-phone-international so people will have access to native input:
```html
<tui-textfield>
  <input tuiInputPhoneInternational />
</tui-textfield>
```
That would fix this issue.

**Comment by waterplea** [comment]
My idea above is not available from experimental package and therefore I'm closing this ticket since that syntax is what we will be moving forward with.
