### ISSUE TITLE
🐞 - The text in the notification on the Android and iOS platforms is not aligned relative to the icon

### ISSUE THREAD

**Issue by lld4n** [taiga-family/taiga-ui#9556]
### Reproduction url

https://stackblitz.com/edit/angular-bjy2eq?file=src%2Fapp%2Fapp.template.html

### Description

The text in the notification on the Android and iOS platforms is not aligned relative to the icon

![image (1)](https://github.com/user-attachments/assets/5d632380-3c2d-4dc1-8fb1-a56dac7ac87e)

### Taiga UI version

4.11.1

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Fixed in today's release
