### ISSUE TITLE
🐞 - `InputPhoneInternational` has broken country selector for IOS devices

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#9563]
### Reproduction url

https://taiga-ui.dev/next/components/input-phone-international#countries

### Description

1. Use iPhone, mobile safari
2. Open https://taiga-ui.dev/next/components/input-phone-international#countries
3. Click on country select

<img height="400" src="https://github.com/user-attachments/assets/d42d2115-db4b-4495-906a-8acce5edd1e6" />

https://github.com/user-attachments/assets/820fc5e9-ae3a-415a-9152-2175718cfd99

### Taiga UI version

4.12.0

### Browser Used

Safari

### OS Used

iOS

**Comment by waterplea** [comment]
Apparently the input inside dropdown breaks this. Could be autofocus issue, I'll try to figure it out.
