### ISSUE TITLE
🐞 - DropdownHover is not working correctly.

### ISSUE THREAD

**Issue by damirsaifut** [taiga-family/taiga-ui#9589]
### Reproduction url

https://stackblitz.com/edit/angular-ryjfhw?file=src%2Fapp%2Fapp.template.html

### Description

When tapping on mobile to dropdown hover `:hover` state is not removed from the element when clicking on the overlay so it cannot be opened again until tapped somewhere else. It needs to be fixed in versions 3 and 4 of Taiga.

### Taiga UI version

v3, v4

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Could you clarify the issue, please? I do not understand it from your description and the link seem to work correctly.
