### ISSUE TITLE
🐞 - Animation for the arrow  in TuiMultiSelectComponent it doesn't work correctly

### ISSUE THREAD

**Issue by algashev123** [taiga-family/taiga-ui#9590]
### Reproduction url

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Description

1. Open example;
2. Click on component;
3. Look at the arrow.

Expected result:
The arrow has changed its position

Current result
The arrow remained in its current position. It will turn only after hovering over the list item

### Taiga UI version

4.12.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by algashev123** [comment]
Hello, are there any updates on this task?

**Comment by splincode** [comment]
@algashev123 sorry, could you provide a correct link to your stackblitz repro?

**Comment by algashev123** [comment]
@splincode, I took the link to stackblitz from the examples for the TuiMultiSelectComponent component, the problem is reproduced in all the examples.

**Comment by splincode** [comment]
@algashev123 oh, sorry for disturb
