### ISSUE TITLE
🐞 - `InputPhone` fails to format paste if value has space after plus sign

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#9592]
### Reproduction url

https://taiga-ui.dev/components/input-phone/API

### Description

1. Open https://taiga-ui.dev/components/input-phone/API
2. Insert the following value (there is space after `+` sign)
```
+ 7 (123) 456-78-90
```

**Expected**: `+7 (123) 456-78-90`
**Actual**: `+7 (712) 345-67-89`

### Possible solution
Improve this RegExp (add some `\s?`)
https://github.com/taiga-family/taiga-ui/blob/b4f4f32b43e78a47aa66cdaa6ed411c5ccb02f71/projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts#L21-L27

### Taiga UI version

4.12.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by nezar-khamidekh** [comment]
I will take it
