### ISSUE TITLE
🐞 - Multi-Select - tuiDropdownOpenChange emitting two events

### ISSUE THREAD

**Issue by blendirugova** [taiga-family/taiga-ui#9609]
### Reproduction url

https://stackblitz.com/edit/angular-u8tdmj?file=src%2Fapp%2Fapp.component.html

### Description

When opening and closing the multi-select dropdown two events are being emitted from the tuiDropdownOpenChange output. Check stackblitz for example.

### Taiga UI version

3.96

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
We need to change the output here to pipe:
https://github.com/taiga-family/taiga-ui/blob/main/projects/core/directives/dropdown/dropdown-open-legacy.directive.ts#L14

```ts
private readonly stream$ = new BehaviorSubject(false);  

@Output()
public readonly tuiDropdownOpenChange = this.stream$.pipe(
  distinctUntilChanged(),
  skip(1),
);
```
