### ISSUE TITLE
🐞 - scrolling disappears after close dialog

### ISSUE THREAD

**Issue by expdts** [taiga-family/taiga-ui#9619]
### Reproduction url

https://taiga-ui.dev/components/dialog

### Description

Горизонтальная и вертикальная прокрутка исчезает после закрытия диалогового окна.

### Taiga UI version

4.11.1

### Browser Used

Other

### OS Used

Windows

**Comment by waterplea** [comment]
I think in the latest version we moved tui-scroll-controls in tui-root beneath dialogs overlay so we no longer need to hide it depending on dialogs being present. Maybe this would fix it.

**Comment by expdts** [comment]
> Я думаю, что в последней версии мы переместили tui-scroll-controls в tui-root под диалоговые окна, чтобы нам больше не нужно было скрывать его в зависимости от наличия диалоговых окон. Возможно, это решит проблему.

Можете ли вы исправить ошибку в самое ближайшее время или может есть обходное решение? К сожалению из-за данной ошибки нет возможности пользоваться без горизонтальной прокрутки и пользователям приходится обновлять страницу каждый раз.
