### ISSUE TITLE
🐞 - support MobileCalendar with zoneless

### ISSUE THREAD

**Issue by al-march** [taiga-family/taiga-ui#9662]
### Reproduction url

https://stackblitz.com/edit/ccwfer

### Description

Incorrect Virtual Scroll Behavior in Mobile Calendar with `provideExperimentalZonelessChangeDetection`

https://github.com/user-attachments/assets/2f26e1de-4777-44c7-8200-1cf97010177d

### Taiga UI version

4.13.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Hmmm. I wonder if it might be an issue with Angular CDK virtual scroll? We use it there with our custom height strategy.
