### ISSUE TITLE
🐞 - Search for components on main page stops working after incorrect search query

### ISSUE THREAD

**Issue by alexhawkins94** [taiga-family/taiga-ui#9666]
### Reproduction url

https://stackblitz.com/run?file=src%2Fapp%2Fapp.template.html&hideExplorer=1

### Description

Search for components on your main page stops working after incorrect search query

steps:
-search for accordion - search result pops up
-search for "asd asd" - no search result
-search again for accordion
result: no results, search stops working and not giving any results. need to refresh page

![Image](https://github.com/user-attachments/assets/c04672ba-971c-4b62-be14-1b4511c28b28)

### Taiga UI version

3.96

### Browser Used

Chrome

### OS Used

Windows

**Comment by nsbarsukov** [comment]
Fixed in
* https://github.com/taiga-family/taiga-ui/pull/9881
