### ISSUE TITLE
🐞 - Extra space before link buttons text in `ActionBar`

### ISSUE THREAD

**Issue by KrollikRoddzer** [taiga-family/taiga-ui#9700]
### Reproduction url

https://stackblitz.com/edit/angular-ldb8ux?file=src%2Fapp%2Fapp.template.html

### Description

Extra space before link buttons text in `ActionBar`

### Taiga UI version

4.13.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by 40oleg** [comment]
I will take it

**Comment by vladimirpotekhin** [comment]
Hi @40oleg ! what's your progress on this?

**Comment by 40oleg** [comment]
> Hi [@40oleg](https://github.com/40oleg) ! what's your progress on this?

Hi. sorry, was very busy, but finish it soon

**Comment by 40oleg** [comment]
@vladimirpotekhin finished
