### ISSUE TITLE
🐞 - "Fade In" animation flickers when animation speed is zero

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#9704]
### Reproduction url

https://taiga-ui.dev/animations#tui-fade-in

### Description

The "Fade In" animation flickers at epilepsy inducing rate when animation speed is zero:

![Image](https://github.com/user-attachments/assets/575efba0-180e-4c68-9702-d81383c40da9)

### Taiga UI version

4.14.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by waterplea** [comment]
Is this a documentation page issue or are you seeing any flicker in some of the component use in your app where you disabled animations?

**Comment by hakimio** [comment]
I don't disable animations in my apps. I only noticed this in the docs.

**Comment by waterplea** [comment]
Then we should probably detect if animations are disabled and just show a message instead of animations demo since you won't see them anyway
