### ISSUE TITLE
🚀 - Click outside without overlay for tui-drawer and tui-popup

### ISSUE THREAD

**Issue by Goodzonchik** [taiga-family/taiga-ui#9737]
### Description

In Taiga V4 `tuiClickOutside` is deprecated and I can't use `ActiveZone` from docs like `tuiClickOutside`.

I'm need sidebar without overlay like this [example](https://taiga-ui.dev/components/drawer#full). But I need close sidebar on click outside.

**Comment by waterplea** [comment]
Why can't you use `ActiveZone`?

**Comment by Goodzonchik** [comment]
I couldn't figure out how to make the tui-drawer the active zone after it opens. By default, the application remains the active zone. To make the tui-drawer the active zone, you need to click on it. However, I need to be able to close it by clicking outside the tui-drawer after it opens.

**Comment by waterplea** [comment]
If you open it by a button, you can put active zone on that button and make drawer its child in the DI hierarchy:
https://stackblitz.com/edit/angular-2g8a6jhp
Would that work for you?

**Comment by Goodzonchik** [comment]
Currently, I cannot use the drawer as content for the button. The buttons are in the header component of the application and are formed through a dynamic configuration for each application. The drawer is used as a component within a connected library. Implementing the proposed solution is possible, but it would require redoing the entire mechanism of forming buttons within the header component.

**Comment by waterplea** [comment]
It doesn't have to be inside button, updated my StackBlitz above, you can pass active zone around like that. `tuiClickOutside` is not coming back, it was an undocumented hack for a particular case that we managed to drop during refactor. So if you want to keep it moving forward — copy its source code to your project.
