### ISSUE TITLE
🚀 - Strict CSP policy support (data:)

### ISSUE THREAD

**Issue by tinkoffspectrum** [taiga-family/taiga-ui#9755]
### Description

Now tui contains `data:` pictures for checkboxes in the code.

Usage `data:` Is a reliable place for XSS attacks. Strict CSP policies prohibit the use of `data:`.

Please add the ability to override image with `data`: in code (including on mobile) to support security requirements.

**Comment by waterplea** [comment]
To clarify, often some details not replicable with CSS are stored as SVGs in CSS as `data:image/svg`, such as smooth curves or icons. Allowing `data:` in CSP for `img-src` does not pose risks as XSS is not possible in those, at worst some rogue browser extension can add an obscene image to your website. Risks do not outweigh benefits of being able to store these things without external assets:

![Image](https://github.com/user-attachments/assets/21af6841-ec06-4dd3-96e5-2424ee3b0238)
![Image](https://github.com/user-attachments/assets/6005efff-3a9d-4fc3-8aa3-aaea5243514e)
![Image](https://github.com/user-attachments/assets/9408df9f-d429-4bf3-bc9f-c61ed756196e)
![Image](https://github.com/user-attachments/assets/a4270f23-e77b-4c60-b93a-78f6abc86590)
![Image](https://github.com/user-attachments/assets/c2b3a610-8621-4621-a350-a0f7d3cabb48)
