### ISSUE TITLE
🐞 - TuiSkeleton animation speed slow down after speed up TUI_ANIMATIONS_SPEED

### ISSUE THREAD

**Issue by simonenkof** [taiga-family/taiga-ui#9778]
### Reproduction url

https://stackblitz.com/edit/angular-qoqwp3?file=src%2Fapp%2Fapp.template.html

### Description

When you speed up animations TUI_ANIMATIONS_SPEED, the animation speed of TuiSkeleton (maybe something else) slows down a lot.

### Taiga UI version

4.15.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Looks like we forgot to use `tuiGetDuration` here:
https://github.com/taiga-family/taiga-ui/blob/main/projects/kit/directives/skeleton/skeleton.directive.ts#L42

**Comment by Jonesso** [comment]
I'll take it
