### ISSUE TITLE
Radio button works incorrectly when patch from value

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#9807]
### Discussed in https://github.com/orgs/taiga-family/discussions/9801

<div type='discussions-op-text'>

<sup>Originally posted by **vytautas-pranskunas-** November 20, 2024</sup>
I am attaching a vuideo but it is some kind of tick missing because when i path from value (after 2 seconds as you can see in source code) radio button value changes but animation is not played until the end. It is enough for me click anywhere on the screen and animation is completed. Any ideas why it could happen?

https://github.com/user-attachments/assets/f3bc5a15-96ed-4c5d-be8f-348adc532463

</div>

Repro: https://stackblitz.com/edit/angular-buf4yk?file=src%2Fapp%2Fapp.template.html,src%2Fapp%2Fapp.component.ts&hideExplorer=1

**Comment by waterplea** [comment]
You are using `setTimeout` inside `OnPush` component, it is expected not to work properly in that case.
