### ISSUE TITLE
🐞 - Drag-and-drop functionality for input files not working on Firefox

### ISSUE THREAD

**Issue by phanhung1309** [taiga-family/taiga-ui#9808]
### Reproduction url

https://stackblitz.com/edit/angular-bonkib?file=src%2Fapp%2Fapp.component.ts

### Description

The input-files component does not support drag-and-drop functionality when used on the Firefox browser. While this feature works as expected on other browsers like Chrome, attempting to drag and drop a file on Firefox results in no action.

Steps to reproduce:

1. Open the input-files component example in Firefox.
2. Try dragging a file to the input area.
3. Observe that no files are accepted, and the drag-and-drop event is not triggered.

Firefox:
![Image](https://github.com/user-attachments/assets/6eaabdbb-8d78-4d7b-ad18-89a8e492c6da)

Chrome: 
![Image](https://github.com/user-attachments/assets/6a228404-b45c-4619-adcf-26e990d43cb0)

### Taiga UI version

4.16.0

### Browser Used

Firefox

### OS Used

Windows

**Comment by phanhung1309** [comment]
I am using Windows 11 and Firefox version 132.0.2.
I can still drag and drop files from the Windows file selection window, but if I click to open the dialog box to drag and drop, it doesn't work.
https://github.com/user-attachments/assets/aeb304ed-c2ab-4dc9-b8fc-bce14978bbd4

**Comment by waterplea** [comment]
This is how Firefox and input files work, you can reproduce it with vanilla input:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
