### ISSUE TITLE
🐞 - `Appearance` with `textfield` value does not have `border-radius` customization

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#9812]
### Reproduction url

https://stackblitz.com/edit/content-editable-with-appearance-textfield?file=src%2Fapp%2Fapp.template.html

### Description

```html
<div
    tuiAppearance="textfield"
    contenteditable="true"

>
    Enter something
</div>
```

![Image](https://github.com/user-attachments/assets/9ee5bb61-87ab-4fa3-a4ac-27c6772ca291)
![Image](https://github.com/user-attachments/assets/ae09ba39-9313-4966-81b8-9eb26c1f583f)

**Should we add `border-radius` customization by default ?**
![Image](https://github.com/user-attachments/assets/89274b14-20c6-48fb-b35f-54feb155f85a)

### Taiga UI version

4.16.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by vladimirpotekhin** [comment]
border-radius depends on size of element; appearance should not customize anything that depends on size

**Comment by waterplea** [comment]
Paddings and shape are not part of the appearance in general. Appearance is for color, background color, outline and interactive states, not for shape or content.
