### ISSUE TITLE
🐞 - `TuiTime.shift` doesn't shift higher order units

### ISSUE THREAD

**Issue by DmitryBrovchenko** [taiga-family/taiga-ui#9817]
### Reproduction url

https://stackblitz.com/edit/angular-omavrt?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.template.html&hideExplorer=1

### Description

`TuiTime.shift` doesn't change minutes and hours, when changing seconds should result in their change, or hours when changing minutes.

![Image](https://github.com/user-attachments/assets/157cb24b-9a6d-40b2-9b21-16e47c5856f1)

It complicates time related operations. The expected behavior is similar to `TuiDay.append`, which modifies other units. 

### Taiga UI version

3.98.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by reverie3** [comment]
I'd like to help with this issue.
