### ISSUE TITLE
🐞 - Link "this article" in README.md leads to 404

### ISSUE THREAD

**Issue by klyakh** [taiga-family/taiga-ui#9823]
### Reproduction url

https://github.com/taiga-family/taiga-ui

### Description

Here is a snippet from README.md:

"Read more about Taiga UI main features in [this article](https://indepth.dev/posts/1413/taiga-ui) on inDepth"

https://indepth.dev/posts/1413/taiga-ui - leads to error 404.

### Taiga UI version

4.16.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by hakimio** [comment]
Most of the articles are missing from **indepth.dev**.
