### ISSUE TITLE
🐞 - tui-input-phone Component doesn’t parse phone number if length is less than 13

### ISSUE THREAD

**Issue by Dmi3Iva** [taiga-family/taiga-ui#9834]
### Reproduction url

https://taiga-ui.dev/components/input-phone/API?countryCode=%2B850

### Description

When I paste a phone number with 11 digits (e.g., +850 (555) 591-72) into the tui-input-phone component, the input doesn’t parse it correctly.

Expected Behavior:
The input should display the number exactly as pasted:
+850 (555) 591-72

Actual Behavior:
The component adds extra numbers at the beginning, resulting in:
+850 (850) 555-59-17

### Taiga UI version

4.16.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Looks like the fix would be to consider country code included if the number starts with + here:
https://github.com/taiga-family/taiga-ui/blob/main/projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts
