### ISSUE TITLE
🐞 - `Table` sort icons in table header are reversed

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#9884]
### Reproduction url

https://taiga-ui.dev/components/table

### Description

If you check `th` directive source code, you'll see that the sort icons are reversed:
https://github.com/taiga-family/taiga-ui/blob/76d8d01006481564500ec1e1f328fe748b6d9879/projects/addon-table/components/table/th/th.component.ts#L73

`direction === 1` means `ascending` order and `-1` means `descending` order, but the code is the opposite way:
```ts
this.table?.direction === 1
    ? this.options.sortIcons.desc
    : this.options.sortIcons.asc;
```

### Taiga UI version

4.17.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by waterplea** [comment]
That would be breaking change :( It works right by default showing proper icons because the icons are also reversed. We can fix the default but if you overridden them in your app — this fix would break it for you. Or can this be considered a bugfix and not a breaking change?

**Comment by hakimio** [comment]
It is **a bug** and should be treated as such. You can clearly see in the "Editable" and "With tuiSortBy directive" demos that the sorting icons are reversed.
Switching icons locally is a workaround, not a fix. The bug should be addressed in the library.

**Comment by hakimio** [comment]
Do I only need to fix the TH directive itself or are there some tests that I need to update too? [Should there be some extra tests for this?]

**Comment by waterplea** [comment]
Just the TH, screenshots will fail and that would be expected.
