### ISSUE TITLE
🐞 - Strange behavior in Safari when working with tiles

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#9915]
### Reproduction url

https://taiga-ui.dev/components/tiles

### Description

https://github.com/user-attachments/assets/22b77331-16d8-4b5d-9057-bed90953c948

### Taiga UI version

latest

### Browser Used

Safari

### OS Used

macOS

**Comment by waterplea** [comment]
Looks like tile handler should prevent default behavior of `mousedown` or better yet have `user-select: none` CSS if it would help

**Comment by reverie3** [comment]
I'd like to take this issue, could you assign me?
