### ISSUE TITLE
🐞 - Components Api tab > documentation table - Not responsive (Type & Value column data overlapping)

### ISSUE THREAD

**Issue by shiv9604** [taiga-family/taiga-ui#9966]
### Reproduction url

https://paste.pics/11986acbf07a392ae9de33adf531e892

### Description

This issue should be fixed generically for API documentation columns and tested across all API tabs available at https://taiga-ui.dev/components/alert/API.

Example.
1. Dropdown data list > api tab view - Not responsive for tablet (Type column & value column values overlapping).

### Taiga UI version

All Release versions.

### Browser Used

Chrome

### OS Used

macOS

**Comment by shiv9604** [comment]
HI @splincode or @waterplea, can you please confirm the issue? I am not able to add a `need-triage` label on it.

**Comment by waterplea** [comment]
@shiv9604 I see it looks bad in dark mode. We have a newer documentation components which do not overlap (used, for example, in Button component docs). At some point we want to migrate all pages to that new approach (https://github.com/taiga-family/taiga-ui/issues/9057), but it would take time so if you want, you can submit a PR with `overflow: hidden` added to the type column.

**Comment by shiv9604** [comment]
Thanks, @waterplea, I have assigned this issue to me & will take care of it.
