### ISSUE TITLE
🐞 - Multi-Select - value content is not clickable

### ISSUE THREAD

**Issue by alexchvt** [taiga-family/taiga-ui#9968]
### Reproduction url

https://stackblitz.com/edit/angular-zhyekruf?file=src%2Fapp%2Fapp.template.html

### Description

When passing custom template through multi-select input, click event (maybe others) aren't working.

### Taiga UI version

4.18

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
That is expected, apply `pointer-events: auto` CSS to interactive content.
