### ISSUE TITLE
🐞 - Wrong appearance on checkbox after form.patchValue

### ISSUE THREAD

**Issue by victorien-ffbridge** [taiga-family/taiga-ui#9988]
### Reproduction url

https://stackblitz.com/edit/angular-nsa34rud?file=src%2Fapp%2Fapp.component.ts

### Description

When updating form value after a delay, (e.g. after receiving data from backend), if a checkbox value was initiated to false and is updated to true, the checkbox appearance remains "outline-greyscale" instead of switching to "primary".

### Taiga UI version

4.18.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
This is expected, you need to either disable `OnPush` change detection or call `cdr.markForCheck();`
